// app/form/fields/DualSelectFormField.tsx
import type { FormFieldItems, FormFieldProps } from "../types";
import { FormFieldMessages } from "./FormFieldWrapper";
import { SelectFormField } from "./SelectFormField";

type DualSelectFormFieldProps<V extends string> = Omit<
	FormFieldProps<"dual-select">,
	"clearable" | "name"
> & {
	fields: [
		{ label?: string; items: FormFieldItems<V> },
		{ label?: string; items: FormFieldItems<V> },
	];
	value: [V | null, V | null];
	onChange: (value: [V | null, V | null]) => void;
	clearable?: boolean;
};

export function DualSelectFormField<V extends string>({
	bottomText,
	error,
	onBlur,
	value,
	onChange,
	clearable,
	fields,
}: DualSelectFormFieldProps<V>) {
	return (
		<div className="stack xs">
			<div className="stack horizontal md">
				<SelectFormField
					label={fields[0].label}
					items={fields[0].items}
					value={value[0]}
					onChange={(newValue) => onChange([newValue, value[1]])}
					onBlur={onBlur}
					clearable={clearable}
				/>
				<SelectFormField
					label={fields[1].label}
					items={fields[1].items}
					value={value[1]}
					onChange={(newValue) => onChange([value[0], newValue])}
					onBlur={onBlur}
					clearable={clearable}
				/>
			</div>
			<FormFieldMessages error={error} bottomText={bottomText} />
		</div>
	);
}

// apps/web/src/lib/form/fields/DualSelectFormField.svelte
<script lang="ts">
import type { FormFieldItems } from "../form-types.ts";
import FormFieldMessages from "./FormFieldMessages.svelte";
import SelectFormField from "./SelectFormField.svelte";

type DualValue = [string | null, string | null];

interface Props {
	name: string;
	bottomText?: string;
	error?: string;
	onBlur?: (latestValue?: unknown) => void;
	fields: [
		{ label?: string; items: FormFieldItems<string> },
		{ label?: string; items: FormFieldItems<string> },
	];
	value: DualValue;
	onChange: (value: DualValue) => void;
	disabled?: boolean;
}

let { name, bottomText, error, onBlur, fields, value, onChange, disabled }: Props =
	$props();
</script>

<div class="stack xs">
	<div class="stack horizontal md">
		<SelectFormField
			label={fields[0].label}
			items={fields[0].items}
			value={value[0]}
			onChange={(newValue) => onChange([newValue, value[1]])}
			{onBlur}
			clearable
			{disabled}
		/>
		<SelectFormField
			label={fields[1].label}
			items={fields[1].items}
			value={value[1]}
			onChange={(newValue) => onChange([value[0], newValue])}
			{onBlur}
			clearable
			{disabled}
		/>
	</div>
	<FormFieldMessages {name} {error} {bottomText} />
</div>
