// app/form/fields/InputFormField.tsx
import * as React from "react";
import { useTranslation } from "react-i18next";
import type { FormFieldProps } from "../types";
import { ariaAttributes } from "../utils";
import { FormFieldWrapper } from "./FormFieldWrapper";

type InputFormFieldProps = FormFieldProps<"text-field"> & {
	disabled?: boolean;
	autoFocus?: boolean;
	labelPopover?: React.ReactNode;
	value: string;
	onChange: (value: string) => void;
};

export function InputFormField({
	name,
	label,
	labelPopover,
	bottomText,
	leftAddon,
	transformValue,
	placeholder,
	maxLength,
	error,
	onBlur,
	required,
	inputType = "text",
	disabled,
	autoFocus,
	value,
	onChange,
}: InputFormFieldProps) {
	const id = React.useId();
	const { t } = useTranslation(["forms"]);

	const translatedPlaceholder = placeholder?.includes(":")
		? t(placeholder as never)
		: placeholder;

	return (
		<FormFieldWrapper
			id={id}
			name={name}
			label={label}
			labelPopover={labelPopover}
			required={required}
			error={error}
			bottomText={bottomText}
		>
			<div className={leftAddon ? "input-container" : undefined}>
				{leftAddon ? <span className="input-addon">{leftAddon}</span> : null}
				<input
					id={id}
					className={leftAddon ? "in-container" : undefined}
					type={inputType}
					value={value}
					onChange={(e) =>
						onChange(
							transformValue ? transformValue(e.target.value) : e.target.value,
						)
					}
					onBlur={() => onBlur?.()}
					maxLength={maxLength}
					disabled={disabled}
					// biome-ignore lint/a11y/noAutofocus: opt-in per call site, used for inline edit forms
					autoFocus={autoFocus}
					placeholder={translatedPlaceholder}
					{...ariaAttributes({
						name,
						bottomText,
						error,
						required,
					})}
				/>
			</div>
		</FormFieldWrapper>
	);
}

// apps/web/src/lib/form/fields/InputFormField.svelte
<script lang="ts">
import type { Snippet } from "svelte";
import { ariaAttributes, translateFormText } from "../form-utils.ts";
import FormFieldWrapper from "./FormFieldWrapper.svelte";

interface Props {
	name: string;
	label?: string;
	labelPopover?: Snippet;
	bottomText?: string;
	leftAddon?: string;
	transformValue?: (value: string) => string;
	placeholder?: string;
	maxLength: number;
	error?: string;
	onBlur?: (latestValue?: unknown) => void;
	required?: boolean;
	inputType?: "text" | "number";
	disabled?: boolean;
	autoFocus?: boolean;
	value: string;
	onChange: (value: string) => void;
}

let {
	name,
	label,
	labelPopover,
	bottomText,
	leftAddon,
	transformValue,
	placeholder,
	maxLength,
	error,
	onBlur,
	required,
	inputType = "text",
	disabled,
	autoFocus,
	value,
	onChange,
}: Props = $props();

const id = $props.id();

const translatedPlaceholder = $derived(translateFormText(placeholder));
</script>

<FormFieldWrapper {id} {name} {label} {labelPopover} {required} {error} {bottomText}>
	<div class={leftAddon ? "input-container" : undefined}>
		{#if leftAddon}<span class="input-addon">{leftAddon}</span>{/if}
		<!-- svelte-ignore a11y_autofocus -- opt-in per call site, used for inline edit forms -->
		<input
			{id}
			class={leftAddon ? "in-container" : undefined}
			type={inputType}
			{value}
			oninput={(event) =>
				onChange(
					transformValue
						? transformValue(event.currentTarget.value)
						: event.currentTarget.value,
				)}
			onblur={() => onBlur?.()}
			maxlength={maxLength}
			{disabled}
			autofocus={autoFocus}
			placeholder={translatedPlaceholder}
			{...ariaAttributes({ name, bottomText, error, required })}
		/>
	</div>
</FormFieldWrapper>
