// apps/web-react/app/form/fields/StageSelectFormField.tsx
import type { StageId } from "@sendou/in-game-lists/types";
import { StageSelect } from "~/components/StageSelect";
import type { FormFieldProps } from "../types";
import { FormFieldMessages, useTranslatedTexts } from "./FormFieldWrapper";
import styles from "./StageSelectFormField.module.css";

type StageSelectFormFieldProps = FormFieldProps<"stage-select"> & {
	value: StageId | null;
	onChange: (value: StageId) => void;
	disabled?: boolean;
};

export function StageSelectFormField({
	name,
	label,
	bottomText,
	error,
	required,
	value,
	onChange,
	onBlur,
	disabled,
}: StageSelectFormFieldProps) {
	const { translatedLabel } = useTranslatedTexts({ label });

	return (
		<div className={styles.root}>
			<StageSelect
				label={translatedLabel}
				value={value}
				onChange={(id) => {
					onChange(id);
					onBlur?.(id);
				}}
				isRequired={required}
				isDisabled={disabled}
			/>
			<FormFieldMessages name={name} error={error} bottomText={bottomText} />
		</div>
	);
}

// apps/web/src/lib/form/fields/StageSelectFormField.svelte
<script lang="ts">
import type { StageId } from "@sendou/in-game-lists/types";
import StageSelect from "#lib/components/StageSelect.svelte";
import { translateFormText } from "../form-utils.ts";
import FormFieldMessages from "./FormFieldMessages.svelte";

interface Props {
	name: string;
	label?: string;
	bottomText?: string;
	error?: string;
	required?: boolean;
	onBlur?: (latestValue?: unknown) => void;
	value: StageId | null;
	onChange: (value: StageId) => void;
	disabled?: boolean;
}

let {
	name,
	label,
	bottomText,
	error,
	required,
	onBlur,
	value,
	onChange,
	disabled,
}: Props = $props();

const translatedLabel = $derived(translateFormText(label));
</script>

<div class="root">
	<StageSelect
		label={translatedLabel}
		{value}
		onChange={(stageId) => {
			onChange(stageId);
			onBlur?.(stageId);
		}}
		isRequired={required}
		isDisabled={disabled}
	/>
	<FormFieldMessages {name} {error} {bottomText} />
</div>

<style>
	.root {
		& :global(button[class]) {
			width: 100%;
		}
	}
</style>
