// app/features/badges/routes/badges.tsx
import type { MetaFunction } from "@remix-run/node";
import { NavLink, Outlet, useLoaderData } from "@remix-run/react";
import * as React from "react";
import { useTranslation } from "react-i18next";
import { Badge } from "~/components/Badge";
import { Divider } from "~/components/Divider";
import { Input } from "~/components/Input";
import { Main } from "~/components/Main";
import { SearchIcon } from "~/components/icons/Search";
import { useUser } from "~/features/auth/core/user";
import type { SendouRouteHandle } from "~/utils/remix.server";
import { BADGES_DOC_LINK, BADGES_PAGE, navIconUrl } from "~/utils/urls";
import { metaTags } from "../../../utils/remix";

import { type BadgesLoaderData, loader } from "../loaders/badges.server";
export { loader };

import "~/styles/badges.css";

export const handle: SendouRouteHandle = {
	i18n: "badges",
	breadcrumb: () => ({
		imgPath: navIconUrl("badges"),
		href: BADGES_PAGE,
		type: "IMAGE",
	}),
};

export const meta: MetaFunction = (args) => {
	return metaTags({
		title: "Badges",
		ogTitle: "Splatoon badges (tournament prizes list)",
		location: args.location,
		description:
			"Over 400 badge tournament prizes and counting! Check out the full list including the owners.",
	});
};

export default function BadgesPageLayout() {
	const { t } = useTranslation(["badges"]);
	const data = useLoaderData<typeof loader>();
	const user = useUser();
	const [inputValue, setInputValue] = React.useState("");

	const { ownBadges: allOwnBadges, otherBadges: allOtherBadges } = splitBadges(
		data.badges,
		user,
	);

	const inputValueNormalized = inputValue.toLowerCase();
	const ownBadges = allOwnBadges.filter(
		(b) =>
			!inputValueNormalized ||
			b.displayName.toLowerCase().includes(inputValueNormalized),
	);
	const otherBadges = allOtherBadges.filter(
		(b) =>
			!inputValueNormalized ||
			b.displayName.toLowerCase().includes(inputValueNormalized),
	);

	return (
		<Main>
			<div className="badges__container">
				<Outlet />
				<Input
					className="badges-search__input"
					icon={<SearchIcon className="badges-search__icon" />}
					value={inputValue}
					onChange={(e) => setInputValue(e.target.value)}
				/>
				{ownBadges.length > 0 ? (
					<div className="w-full">
						<Divider smallText>{t("badges:own.divider")}</Divider>
						<div className="badges__small-badges">
							{ownBadges.map((badge) => (
								<NavLink
									className="badges__nav-link"
									key={badge.id}
									to={String(badge.id)}
								>
									<Badge badge={badge} size={64} isAnimated={false} />
								</NavLink>
							))}
						</div>
					</div>
				) : null}
				{ownBadges.length > 0 || otherBadges.length > 0 ? (
					<div className="w-full">
						<div className="badges__small-badges">
							{ownBadges.length > 0 ? (
								<Divider smallText>{t("badges:other.divider")}</Divider>
							) : null}
							{otherBadges.map((badge) => (
								<NavLink
									className="badges__nav-link"
									key={badge.id}
									to={String(badge.id)}
								>
									<Badge badge={badge} size={64} isAnimated={false} />
								</NavLink>
							))}
						</div>
					</div>
				) : (
					<div className="text-lg font-bold my-24">
						{t("badges:noBadgesFound")}
					</div>
				)}
			</div>
			<div className="badges__general-info-texts">
				<p>
					<a href={BADGES_DOC_LINK} target="_blank" rel="noopener noreferrer">
						{t("forYourEvent")}
					</a>
				</p>
			</div>
		</Main>
	);
}

function splitBadges(
	badges: BadgesLoaderData["badges"],
	user: ReturnType<typeof useUser>,
) {
	const ownBadges: BadgesLoaderData["badges"] = [];
	const otherBadges: BadgesLoaderData["badges"] = [];

	for (const badge of badges) {
		if (user && badge.managers.includes(user?.id)) {
			ownBadges.push(badge);
		} else {
			otherBadges.push(badge);
		}
	}

	return { ownBadges, otherBadges };
}

// src/routes/badges/+page.svelte
<script lang="ts">
	import Badge from '$lib/components/badge.svelte';
	import Divider from '$lib/components/divider.svelte';
	import Input from '$lib/components/input.svelte';
	import SearchIcon from '$lib/components/icons/search.svelte';
	import { BADGES_DOC_LINK } from '$lib/utils/urls';
	import Main from '$lib/components/main.svelte';
	import { allBadges, type AllBadgesQuery } from './queries/all-badges.remote';
	import OpenGraphMeta from '$lib/components/open-graph-meta.svelte';

	let { children } = $props();

	let searchInputValue = $state('');

	const { ownBadges: allOwnBadges, otherBadges: allOtherBadges } = $derived(
		splitBadges(await allBadges())
	);

	const inputValueNormalized = $derived(searchInputValue.toLowerCase());

	const ownBadges = $derived(
		allOwnBadges.filter(
			(b) => !inputValueNormalized || b.displayName.toLowerCase().includes(inputValueNormalized)
		)
	);

	const otherBadges = $derived(
		allOtherBadges.filter(
			(b) => !inputValueNormalized || b.displayName.toLowerCase().includes(inputValueNormalized)
		)
	);

	function splitBadges(
		badges: AllBadgesQuery
		// currentUser: typeof $user xxx: TODO current user handling
	) {
		const ownBadges: AllBadgesQuery = [];
		const otherBadges: AllBadgesQuery = [];

		for (const badge of badges) {
			// xxx: TODO
			// if (currentUser && badge.permissions.MANAGE.includes(currentUser.id)) {
			// 	ownBadges.push(badge);
			// } else {
			// 	otherBadges.push(badge);
			// }

			otherBadges.push(badge);
		}

		return { ownBadges, otherBadges };
	}
</script>

<OpenGraphMeta
	title="Badges"
	ogTitle="Splatoon badges (tournament prizes list)"
	description="Over 400 badge tournament prizes and counting! Check out the full list including the owners."
/>

<Main>
	<div class="container">
		{@render children?.()}

		{#snippet searchIcon()}
			<SearchIcon class="search-icon" />
		{/snippet}

		<Input class="search-input" icon={searchIcon} bind:value={searchInputValue} />

		{#if ownBadges.length > 0}
			<div class="w-full">
				<Divider smallText>i18n: own.divider</Divider>
				<div class="small-badges">
					{#each ownBadges as badge (badge.id)}
						<a class="nav-link" href="/badges/{badge.id}">
							<Badge {badge} size={64} isAnimated={false} />
						</a>
					{/each}
				</div>
			</div>
		{/if}

		{#if ownBadges.length > 0 || otherBadges.length > 0}
			<div class="w-full">
				<div class="small-badges">
					{#if ownBadges.length > 0}
						<Divider smallText>i18n: other.divider</Divider>
					{/if}
					{#each otherBadges as badge (badge.id)}
						<!-- xxx: hide conditionally (when viewing the page of it) -->
						<a class="nav-link" href="/badges/{badge.id}">
							<Badge {badge} size={64} isAnimated={false} />
						</a>
					{/each}
				</div>
			</div>
		{:else}
			<div class="text-lg font-bold my-24">i18n: badges:noBadgesFound</div>
		{/if}
	</div>

	<div class="general-info-texts">
		<p>
			<a href={BADGES_DOC_LINK} target="_blank" rel="noopener noreferrer"> i18n: forYourEvent </a>
		</p>
	</div>
</Main>

<style>
	.container {
		display: flex;
		flex-direction: column;
		align-items: center;
		border-radius: var(--rounded);
		background-color: var(--bg-badge);
		color: var(--badge-text);
		gap: var(--s-6);
		padding-block: var(--s-2);
		padding-inline: var(--s-3);
	}

	.small-badges {
		display: flex;
		flex-wrap: wrap;
		justify-content: center;
		gap: var(--s-2);
		margin-block-start: var(--s-1);
	}

	.general-info-texts {
		display: flex;
		justify-content: space-between;
		color: var(--text-lighter);
		font-size: var(--fonts-xs);
		padding-inline: var(--s-1);
	}

	.container :global(.search-input) {
		height: 40px !important;
		margin: 0 auto;
		font-size: var(--fonts-lg);
	}

	.container :global(.search-icon) {
		height: 25px;
		margin: auto;
		margin-right: 15px;
	}
</style>
