// app/components/BuildCard.tsx
import clsx from "clsx";
import { useTranslation } from "react-i18next";
import { Link } from "react-router-dom";
import type { GearType, Tables, UserWithPlusTier } from "~/db/tables";
import { useUser } from "~/features/auth/core/user";
import type { BuildWeaponWithTop500Info } from "~/features/builds/queries/buildsBy.server";
import { useIsMounted } from "~/hooks/useIsMounted";
import type {
	Ability as AbilityType,
	ModeShort,
} from "~/modules/in-game-lists/types";
import type { BuildAbilitiesTuple } from "~/modules/in-game-lists/types";
import { altWeaponIdToId } from "~/modules/in-game-lists/weapon-ids";
import { databaseTimestampToDate } from "~/utils/dates";
import { gearTypeToInitial } from "~/utils/strings";
import {
	analyzerPage,
	gearImageUrl,
	mainWeaponImageUrl,
	modeImageUrl,
	mySlugify,
	navIconUrl,
	userBuildsPage,
	weaponBuildPage,
} from "~/utils/urls";
import { Ability } from "./Ability";
import { FormWithConfirm } from "./FormWithConfirm";
import { Image } from "./Image";
import { LinkButton, SendouButton } from "./elements/Button";
import { SendouPopover } from "./elements/Popover";
import { EditIcon } from "./icons/Edit";
import { LockIcon } from "./icons/Lock";
import { SpeechBubbleIcon } from "./icons/SpeechBubble";
import { TrashIcon } from "./icons/Trash";

import styles from "./BuildCard.module.css";

interface BuildProps {
	build: Pick<
		Tables["Build"],
		| "id"
		| "title"
		| "description"
		| "clothesGearSplId"
		| "headGearSplId"
		| "shoesGearSplId"
		| "updatedAt"
		| "private"
	> & {
		abilities: BuildAbilitiesTuple;
		unsortedAbilities: BuildAbilitiesTuple;
		modes: ModeShort[] | null;
		weapons: Array<{
			weaponSplId: Tables["BuildWeapon"]["weaponSplId"];
			minRank: number | null;
			maxPower: number | null;
		}>;
	};
	owner?: Pick<UserWithPlusTier, "discordId" | "username" | "plusTier">;
	canEdit?: boolean;
	withAbilitySorting?: boolean;
}

export function BuildCard({
	build,
	owner,
	canEdit = false,
	withAbilitySorting = true,
}: BuildProps) {
	const user = useUser();
	const { t } = useTranslation(["weapons", "builds", "common", "game-misc"]);
	const { i18n } = useTranslation();
	const isMounted = useIsMounted();

	const {
		id,
		title,
		description,
		clothesGearSplId,
		headGearSplId,
		shoesGearSplId,
		updatedAt,
		modes,
		weapons,
	} = build;

	const abilities = withAbilitySorting
		? build.abilities
		: build.unsortedAbilities;

	const isNoGear = [headGearSplId, clothesGearSplId, shoesGearSplId].some(
		(id) => id === -1,
	);

	return (
		<div
			className={clsx(styles.card, { [styles.private]: build.private })}
			data-testid="build-card"
		>
			<div>
				<div className={styles.topRow}>
					{modes && modes.length > 0 && (
						<div className={styles.modes}>
							{modes.map((mode) => (
								<Image
									key={mode}
									alt={t(`game-misc:MODE_LONG_${mode}` as any)}
									title={t(`game-misc:MODE_LONG_${mode}` as any)}
									path={modeImageUrl(mode)}
									width={18}
									height={18}
									testId={`build-mode-${mode}`}
								/>
							))}
						</div>
					)}
					<h2 className={styles.title} data-testid="build-title">
						{title}
					</h2>
				</div>
				<div className={styles.dateAuthorRow}>
					{owner && (
						<>
							<Link to={userBuildsPage(owner)} className={styles.ownerLink}>
								{owner.username}
							</Link>
							<div>•</div>
						</>
					)}
					{owner?.plusTier ? (
						<>
							<span>+{owner.plusTier}</span>
							<div>•</div>
						</>
					) : null}
					<div className="stack horizontal sm">
						{build.private ? (
							<div className={styles.privateText}>
								<LockIcon className={styles.privateIcon} />{" "}
								{t("common:build.private")}
							</div>
						) : null}
						<time
							className={clsx("whitespace-nowrap", { invisible: !isMounted })}
						>
							{isMounted
								? databaseTimestampToDate(updatedAt).toLocaleDateString(
										i18n.language,
										{
											day: "numeric",
											month: "long",
											year: "numeric",
										},
									)
								: "t"}
						</time>
					</div>
				</div>
			</div>
			<div className={styles.weapons}>
				{weapons.map((weapon) => (
					<RoundWeaponImage key={weapon.weaponSplId} weapon={weapon} />
				))}
				{weapons.length === 1 && (
					<div className={styles.weaponText}>
						{t(`weapons:MAIN_${weapons[0].weaponSplId}` as any)}
					</div>
				)}
			</div>
			<div
				className={clsx(styles.gearAbilities, {
					[styles.noGear]: isNoGear,
				})}
			>
				<AbilitiesRowWithGear
					gearType="HEAD"
					abilities={abilities[0]}
					gearId={headGearSplId}
				/>
				<AbilitiesRowWithGear
					gearType="CLOTHES"
					abilities={abilities[1]}
					gearId={clothesGearSplId}
				/>
				<AbilitiesRowWithGear
					gearType="SHOES"
					abilities={abilities[2]}
					gearId={shoesGearSplId}
				/>
			</div>
			<div className={styles.bottomRow}>
				<Link
					to={analyzerPage({
						weaponId: weapons[0].weaponSplId,
						abilities: abilities.flat(),
					})}
				>
					<Image
						alt={t("common:pages.analyzer")}
						className={styles.icon}
						path={navIconUrl("analyzer")}
					/>
				</Link>
				{description ? (
					<SendouPopover
						trigger={
							<SendouButton
								variant="minimal"
								icon={<SpeechBubbleIcon />}
								className={styles.smallText}
							/>
						}
					>
						{description}
					</SendouPopover>
				) : null}
				{canEdit && (
					<>
						<LinkButton
							className={styles.smallText}
							variant="minimal"
							size="small"
							to={`new?buildId=${id}&userId=${user!.id}`}
							testId="edit-build"
						>
							<EditIcon className={styles.icon} />
						</LinkButton>
						<FormWithConfirm
							dialogHeading={t("builds:deleteConfirm", { title })}
							fields={[
								["buildToDeleteId", id],
								["_action", "DELETE_BUILD"],
							]}
						>
							<SendouButton
								icon={<TrashIcon className={styles.icon} />}
								className={styles.smallText}
								variant="minimal-destructive"
								type="submit"
							/>
						</FormWithConfirm>
					</>
				)}
			</div>
		</div>
	);
}

function RoundWeaponImage({ weapon }: { weapon: BuildWeaponWithTop500Info }) {
	const { weaponSplId, maxPower, minRank } = weapon;
	const normalizedWeaponSplId = altWeaponIdToId.get(weaponSplId) ?? weaponSplId;

	const { t } = useTranslation(["weapons"]);
	const slug = mySlugify(
		t(`weapons:MAIN_${normalizedWeaponSplId}`, { lng: "en" }),
	);

	const isTop500 = typeof maxPower === "number" && typeof minRank === "number";

	return (
		<div key={weaponSplId} className={styles.weapon}>
			{isTop500 ? (
				<Image
					className={styles.top500}
					path={navIconUrl("xsearch")}
					alt=""
					title={`Max X Power: ${maxPower} | Best Rank: ${minRank}`}
					height={24}
					width={24}
					testId="top500-crown"
				/>
			) : null}
			<Link to={weaponBuildPage(slug)}>
				<Image
					path={mainWeaponImageUrl(weaponSplId)}
					alt={t(`weapons:MAIN_${weaponSplId}` as any)}
					title={t(`weapons:MAIN_${weaponSplId}` as any)}
					height={36}
					width={36}
				/>
			</Link>
		</div>
	);
}

function AbilitiesRowWithGear({
	gearType,
	abilities,
	gearId,
}: {
	gearType: GearType;
	abilities: AbilityType[];
	gearId: number;
}) {
	const { t } = useTranslation(["gear"]);
	const translatedGearName = t(
		`gear:${gearTypeToInitial(gearType)}_${gearId}` as any,
	);

	return (
		<>
			{gearId !== -1 ? (
				<Image
					height={64}
					width={64}
					alt={translatedGearName}
					title={translatedGearName}
					path={gearImageUrl(gearType, gearId)}
					className={styles.gear}
				/>
			) : null}
			{abilities.map((ability, i) => (
				<Ability key={i} ability={ability} size={i === 0 ? "MAIN" : "SUB"} />
			))}
		</>
	);
}

// src/lib/components/build-card/BuildCard.svelte
<script lang="ts">
	import {
		gearImageUrl,
		modeImageUrl,
		navIconUrl,
		userBuildsPage,
		weaponBuildPage
	} from '$lib/utils/urls';
	import Ability from '$lib/components/Ability.svelte';
	import Image from '$lib/components/image/Image.svelte';
	import type {
		Ability as AbilityType,
		BuildAbilitiesTuple,
		MainWeaponId,
		ModeShort
	} from '$lib/constants/in-game/types';
	import type { GearType, Tables, UserWithPlusTier } from '$lib/server/db/tables';
	import { m } from '$lib/paraglide/messages';
	import { modesLongTranslations, weaponTranslations } from '$lib/utils/i18n';
	import WeaponImage from '$lib/components/image/weapon-image.svelte';
	import { altWeaponIdToId } from '$lib/constants/in-game/weapon-ids';
	import { getLocale } from '$lib/paraglide/runtime';
	import Lock from '@lucide/svelte/icons/lock';
	import Popover from '$lib/components/popover/Popover.svelte';
	import PopoverTriggerButton from '$lib/components/popover/PopoverTriggerButton.svelte';
	import ActionsMenu from '$lib/components/build-card/ActionsMenu.svelte';

	interface BuildWeaponWithTop500Info {
		weaponSplId: MainWeaponId;
		minRank: number | null;
		maxPower: number | null;
	}

	interface BuildProps {
		build: Pick<
			Tables['Build'],
			| 'id'
			| 'title'
			| 'description'
			| 'clothesGearSplId'
			| 'headGearSplId'
			| 'shoesGearSplId'
			| 'updatedAt'
			| 'private'
		> & {
			abilities: BuildAbilitiesTuple;
			unsortedAbilities: BuildAbilitiesTuple;
			modes: ModeShort[] | null;
			weapons: Array<{
				weaponSplId: Tables['BuildWeapon']['weaponSplId'];
				minRank: number | null;
				maxPower: number | null;
			}>;
		};
		owner?: Pick<UserWithPlusTier, 'discordId' | 'username' | 'plusTier'>;
		withAbilitySorting?: boolean;
		canEdit?: boolean;
	}

	let { build, owner, withAbilitySorting = true, canEdit: _canEdit = false }: BuildProps = $props();

	const abilities = $derived(withAbilitySorting ? build.abilities : build.unsortedAbilities);
	const isNoGear = $derived(
		[build.headGearSplId, build.clothesGearSplId, build.shoesGearSplId].some((id) => id === -1)
	);
</script>

<div
	class={[
		'card',
		{
			private: build.private
		}
	]}
	data-testid="build-card"
>
	<div>
		<div class="top-row">
			{#if build.modes && build.modes.length > 0}
				<div class="modes">
					{#each build.modes as mode (mode)}
						<Image
							alt={modesLongTranslations[mode]()}
							title={modesLongTranslations[mode]()}
							path={modeImageUrl(mode)}
							width={18}
							height={18}
							data-testid="build-mode-{mode}"
						/>
					{/each}
				</div>
			{/if}
			<h2 class="title" data-testid="build-title">
				{build.title}
			</h2>
		</div>
		<div class="stack horizontal justify-between items-center">
			<div class="date-author-row">
				{#if owner}
					<a href={userBuildsPage(owner)} class="owner-link">
						{owner.username}
					</a>
					<div>•</div>
				{/if}
				{#if owner?.plusTier}
					<span>+{owner.plusTier}</span>
					<div>•</div>
				{/if}
				<div class="stack horizontal sm">
					{#if build.private}
						<div class="private-text">
							<Lock class="private-icon" />
							{m.common_build_private()}
						</div>
					{/if}
					<time class="whitespace-nowrap">
						{build.updatedAt.toLocaleDateString(getLocale(), {
							day: 'numeric',
							month: 'numeric',
							year: 'numeric'
						})}
					</time>
				</div>
			</div>
			<ActionsMenu />
		</div>
	</div>
	<div class="weapons">
		{#each build.weapons as weapon (weapon.weaponSplId)}
			{@render roundWeaponImage(weapon)}
		{/each}
		{#if build.weapons.length === 1}
			<div class="weapon-text">
				{weaponTranslations[build.weapons[0].weaponSplId]()}
			</div>
		{/if}
	</div>
	<div class="gear-abilities {isNoGear ? 'no-gear' : ''}">
		{@render abilitiesRowWithGear('HEAD', abilities[0], build.headGearSplId)}
		{@render abilitiesRowWithGear('CLOTHES', abilities[1], build.clothesGearSplId)}
		{@render abilitiesRowWithGear('SHOES', abilities[2], build.shoesGearSplId)}
	</div>

	{#if build.description}
		<Popover>
			{#snippet trigger()}
				<PopoverTriggerButton class="description-button">
					{build.description}
				</PopoverTriggerButton>
			{/snippet}
			{build.description}
		</Popover>
	{/if}
</div>

{#snippet roundWeaponImage(weapon: BuildWeaponWithTop500Info)}
	{@const normalizedWeaponSplId = altWeaponIdToId.get(weapon.weaponSplId) ?? weapon.weaponSplId}
	{@const isTop500 = typeof weapon.maxPower === 'number' && typeof weapon.minRank === 'number'}

	<div class="weapon">
		{#if isTop500}
			<Image
				class="top-500"
				path={navIconUrl('xsearch')}
				alt=""
				title="Max X Power: {weapon.maxPower} | Best Rank: {weapon.minRank}"
				height={24}
				width={24}
				data-testid="top500-crown"
			/>
		{/if}
		<a href={weaponBuildPage(normalizedWeaponSplId)}>
			<WeaponImage weaponSplId={weapon.weaponSplId} size={36} variant="build" />
		</a>
	</div>
{/snippet}

{#snippet abilitiesRowWithGear(gearType: GearType, abilities: AbilityType[], gearId: number)}
	{#if gearId !== -1}
		<Image
			height={64}
			width={64}
			alt="xxx: TODO"
			title="xxx: TODO"
			path={gearImageUrl(gearType, gearId)}
			class="gear"
		/>
	{/if}
	{#each abilities as ability, i (i)}
		<Ability {ability} size={i === 0 ? 'MAIN' : 'SUB'} />
	{/each}
{/snippet}

<style>
	.card {
		position: relative;
		display: flex;
		flex-direction: column;
		padding: var(--s-3);
		border-radius: var(--radius-box);
		background-color: var(--color-base-card);
		gap: var(--s-3);

		:global(.icon) {
			width: 1.2rem;
			height: 1.2rem;
		}

		:global(.gear) {
			border-radius: 50%;
			background-color: var(--color-base-border);
			overflow: visible;
		}

		:global(.description-button) {
			all: unset;
			background-color: var(--color-base-border);
			text-align: center;
			font-size: var(--fonts-xs);
			border-radius: 0 0 var(--radius-box) var(--radius-box);
			white-space: nowrap;
			text-overflow: ellipsis;
			overflow-x: hidden;
			padding: var(--s-1) var(--s-3);
			margin: -2px -12px -12px -12px;
		}
	}

	.private-text {
		display: flex;
		align-items: center;
		font-weight: var(--semi-bold);
		gap: var(--s-1);

		:global(.private-icon) {
			width: 16px;
		}
	}

	.title {
		overflow: hidden;
		height: 2.5rem;
		font-size: var(--fonts-sm);
		line-height: 1.25;
		word-wrap: break-all;
	}

	.top-row {
		display: flex;
		justify-content: space-between;
	}

	.date-author-row {
		display: flex;
		font-size: var(--fonts-xxs);
		gap: var(--s-1);
	}

	.owner-link {
		white-space: nowrap;
		overflow: hidden;
		text-overflow: ellipsis;
		color: var(--color-primary);
		font-weight: var(--semi-bold);
	}

	.modes {
		position: absolute;
		right: 0;
		display: flex;
		min-width: max-content;
		margin-top: -21px;
		gap: var(--s-1);
	}

	.weapon {
		position: relative;
		padding: var(--s-0-5);
		border-radius: 50%;
		background-color: var(--color-base-border);

		:global(.top-500) {
			position: absolute;
			top: -14px;
			right: 8px;
		}
	}

	.weapon-text {
		padding-left: var(--s-1);
		color: var(--color-base-content-secondary);
		font-size: var(--fonts-xxs);
		font-weight: var(--semi-bold);
	}

	.weapons {
		display: flex;
		flex-wrap: wrap;
		align-items: center;
		justify-content: center;
		gap: var(--s-1);
		padding-block-start: var(--s-2);
	}

	.gear-abilities {
		display: grid;
		gap: var(--s-2) var(--s-1);
		grid-template-columns: repeat(5, max-content);
		place-items: center;
	}

	.no-gear {
		grid-template-columns: repeat(4, max-content);
		margin: 0 auto;
		margin-top: 10px;
		margin-bottom: 1rem;
		row-gap: 28px;
	}
</style>
