// apps/web/src/lib/components/layout/EventsList.svelte
<script lang="ts">
	import { isToday, isTomorrow } from "date-fns";
	import { getLocale } from "#lib/paraglide/runtime.js";
	import { m } from "#lib/paraglide/messages.js";
	import type { SidebarEvent } from "./layout-types.ts";
	import ListLink from "./ListLink.svelte";

	interface Props {
		events: SidebarEvent[];
		onclick?: () => void;
	}

	let { events, onclick }: Props = $props();

	const dateFormatter = $derived(
		new Intl.DateTimeFormat(getLocale(), {
			weekday: "long",
			month: "numeric",
			day: "numeric",
		}),
	);
	const timeFormatter = $derived(
		new Intl.DateTimeFormat(getLocale(), {
			hour: "numeric",
			minute: "2-digit",
		}),
	);

	function formatDayHeader(date: Date) {
		if (isToday(date) || isTomorrow(date)) {
			const rtf = new Intl.RelativeTimeFormat(getLocale(), {
				numeric: "auto",
			});
			const str = rtf.format(isToday(date) ? 0 : 1, "day");
			return str.charAt(0).toUpperCase() + str.slice(1);
		}
		return dateFormatter.format(date);
	}

	function eventTitle(event: SidebarEvent) {
		if (event.scrimStatus === "booked") {
			return m.front_sideNav_scrimVs({ opponent: event.name });
		}
		if (event.scrimStatus === "looking") {
			return m.front_sideNav_lookingForScrim();
		}
		if (event.scrimStatus === "requestPending") {
			return m.front_sideNav_scrimRequestPending();
		}
		return event.name;
	}

	const groupedEvents = $derived.by(() => {
		const groups = new Map<string, SidebarEvent[]>();
		for (const event of events) {
			const key = new Date(event.startsAt * 1000).toDateString();
			const group = groups.get(key) ?? [];
			group.push(event);
			groups.set(key, group);
		}
		return [...groups.entries()];
	});
</script>

{#if events.length === 0}
	<div class="text-lighter text-sm p-2">
		{m.front_sideNav_noEvents()}
	</div>
{:else}
	{#each groupedEvents as [dayKey, dayEvents] (dayKey)}
		<div>
			<div class="dayHeader">
				{formatDayHeader(new Date(dayEvents[0].startsAt * 1000))}
			</div>
			{#each dayEvents as event (`${event.type}-${event.id}`)}
				<ListLink
					to={event.url}
					imageUrl={event.logoUrl ?? undefined}
					user={event.user ?? undefined}
					subtitle={timeFormatter.format(event.startsAt * 1000)}
					{onclick}
				>
					{eventTitle(event)}
				</ListLink>
			{/each}
		</div>
	{/each}
{/if}

<style>
	.dayHeader {
		padding: var(--s-2) var(--s-2) var(--s-1);
		font-size: var(--font-2xs);
		font-weight: var(--weight-bold);
		color: var(--color-text-high);
		text-transform: uppercase;
		letter-spacing: 0.05em;
	}
</style>

// app/components/EventsList.tsx
import { isToday, isTomorrow } from "date-fns";
import { useTranslation } from "react-i18next";
import type { SidebarEvent } from "~/features/sidebar/core/sidebar.server";
import { useDateTimeFormat } from "~/hooks/intl/useDateTimeFormat";
import { useHydrated } from "~/hooks/useHydrated";
import styles from "./EventsList.module.css";
import { Placeholder } from "./Placeholder";
import { ListLink } from "./SideNav";

export function EventsList({
	events,
	onClick,
}: {
	events: SidebarEvent[];
	onClick?: () => void;
}) {
	const { t, i18n } = useTranslation(["front"]);
	const { formatter: dateFormatter } = useDateTimeFormat({
		weekday: "long",
		month: "numeric",
		day: "numeric",
	});
	const { formatter: timeFormatter } = useDateTimeFormat({
		hour: "numeric",
		minute: "2-digit",
	});
	const isHydrated = useHydrated();

	if (events.length === 0) {
		return (
			<div className="text-lighter text-sm p-2">
				{t("front:sideNav.noEvents")}
			</div>
		);
	}

	if (!isHydrated) {
		return <Placeholder />;
	}

	const getDayKey = (timestamp: number) => {
		const date = new Date(timestamp * 1000);
		return date.toDateString();
	};

	const formatDayHeader = (date: Date) => {
		if (isToday(date)) {
			const rtf = new Intl.RelativeTimeFormat(i18n.language, {
				numeric: "auto",
			});
			const str = rtf.format(0, "day");
			return str.charAt(0).toUpperCase() + str.slice(1);
		}
		if (isTomorrow(date)) {
			const rtf = new Intl.RelativeTimeFormat(i18n.language, {
				numeric: "auto",
			});
			const str = rtf.format(1, "day");
			return str.charAt(0).toUpperCase() + str.slice(1);
		}
		return dateFormatter.format(date);
	};

	const groupedEvents = events.reduce<Record<string, typeof events>>(
		(acc, event) => {
			const key = getDayKey(event.startsAt);
			if (!acc[key]) {
				acc[key] = [];
			}
			acc[key].push(event);
			return acc;
		},
		{},
	);

	const dayKeys = Object.keys(groupedEvents);

	return (
		<>
			{dayKeys.map((dayKey) => {
				const dayEvents = groupedEvents[dayKey];
				const firstDate = new Date(dayEvents[0].startsAt * 1000);

				return (
					<div key={dayKey}>
						<div className={styles.dayHeader}>{formatDayHeader(firstDate)}</div>
						{dayEvents.map((event) => (
							<ListLink
								key={`${event.type}-${event.id}`}
								to={event.url}
								imageUrl={event.logoUrl ?? undefined}
								subtitle={timeFormatter.format(event.startsAt)}
								onClick={onClick}
							>
								{event.scrimStatus === "booked"
									? t("front:sideNav.scrimVs", { opponent: event.name })
									: event.scrimStatus === "looking"
										? t("front:sideNav.lookingForScrim")
										: event.scrimStatus === "requestPending"
											? t("front:sideNav.scrimRequestPending")
											: event.name}
							</ListLink>
						))}
					</div>
				);
			})}
		</>
	);
}
