// apps/web/src/lib/components/TimePopover.svelte
<!--
@component
A time rendered as a button that opens a popover with the full date/time
(including time zone) and a shortcut for copying a Discord timestamp code.
-->
<script lang="ts">
import { Check, Clipboard } from "@lucide/svelte";
import { Button, Popover } from "@sendou/components";
import LocaleTime from "#lib/components/LocaleTime.svelte";
import { m } from "#lib/paraglide/messages.js";

const COPY_SUCCESS_DURATION_MS = 2000;

interface Props {
	date: Date;
	options?: Intl.DateTimeFormatOptions;
	underline?: boolean;
	class?: string;
	footerText?: string;
}

let {
	date,
	options = {
		minute: "numeric",
		hour: "numeric",
		day: "numeric",
		month: "numeric",
	},
	underline = true,
	class: className,
	footerText,
}: Props = $props();

let copySuccess = $state(false);
let copyResetTimeout: ReturnType<typeof setTimeout> | undefined;

function copyTimestampForDiscord() {
	navigator.clipboard.writeText(`<t:${date.valueOf() / 1000}:F>`).then(
		() => {
			copySuccess = true;
			clearTimeout(copyResetTimeout);
			copyResetTimeout = setTimeout(() => {
				copySuccess = false;
			}, COPY_SUCCESS_DURATION_MS);
		},
		() => {},
	);
}
</script>

<div>
	<Popover>
		{#snippet trigger(triggerProps)}
			<button
				type="button"
				class={[className, "clickable", "textOnlyButton", { dotted: underline }]}
				{...triggerProps}
			>
				<LocaleTime {date} {options} inline />
			</button>
		{/snippet}
		<div class="stack sm">
			<div class="text-center">
				<LocaleTime
					{date}
					options={{
						timeZoneName: "long",
						hour: "numeric",
						minute: "numeric",
					}}
				/>
			</div>
			<Button size="miniscule" variant="minimal" onclick={copyTimestampForDiscord}>
				{#snippet icon()}
					{#if copySuccess}<Check />{:else}<Clipboard />{/if}
				{/snippet}
				{m.common_actions_copyTimestampForDiscord()}
			</Button>
			{#if footerText}
				<div class="text-lighter text-center mt-2 text-xs">
					{footerText}
				</div>
			{/if}
		</div>
	</Popover>
</div>

<style>
	.textOnlyButton {
		cursor: pointer;
		border: 0;
		background-color: inherit;
		color: inherit;
		margin: 0;
		padding: 0;
	}

	.dotted {
		text-decoration-style: dotted;
		text-decoration-line: underline;
		text-decoration-thickness: 2px;
	}
</style>

// app/components/TimePopover.tsx
import clsx from "clsx";
import { Check, Clipboard } from "lucide-react";
import { useRef, useState } from "react";
import { Dialog, Popover } from "react-aria-components";
import { useTranslation } from "react-i18next";
import { useCopyToClipboard } from "~/hooks/useCopyToClipboard";
import { SendouButton } from "./elements/Button";
import popoverStyles from "./elements/Popover.module.css";
import { LocaleTime } from "./LocaleTime";
import styles from "./TimePopover.module.css";

export default function TimePopover({
	date,
	options = {
		minute: "numeric",
		hour: "numeric",
		day: "numeric",
		month: "numeric",
	},
	underline = true,
	className,
	footerText,
}: {
	date: Date;
	options?: Intl.DateTimeFormatOptions;
	underline?: boolean;
	className?: string;
	footerText?: string;
}) {
	const [open, setOpen] = useState(false);

	const triggerRef = useRef(null);

	const { t } = useTranslation(["common"]);

	const { copyToClipboard, copySuccess } = useCopyToClipboard();

	return (
		<div>
			<button
				type="button"
				ref={triggerRef}
				className={clsx(
					className,
					"clickable",
					styles.textOnlyButton,
					underline ? styles.dotted : "",
				)}
				onClick={() => {
					setOpen(true);
				}}
			>
				<LocaleTime date={date} options={options} inline />
			</button>
			<Popover
				isOpen={open}
				className={popoverStyles.content}
				onOpenChange={setOpen}
				triggerRef={triggerRef}
			>
				<Dialog className={popoverStyles.dialog}>
					<div className="stack sm">
						<div className="text-center">
							<LocaleTime
								date={date}
								options={{
									timeZoneName: "long",
									hour: "numeric",
									minute: "numeric",
								}}
							/>
						</div>
						<SendouButton
							size="miniscule"
							variant="minimal"
							onPress={() => copyToClipboard(`<t:${date.valueOf() / 1000}:F>`)}
							icon={copySuccess ? <Check /> : <Clipboard />}
						>
							{t("common:actions.copyTimestampForDiscord")}
						</SendouButton>
						{footerText ? (
							<div className="text-lighter text-center mt-2 text-xs">
								{footerText}
							</div>
						) : null}
					</div>
				</Dialog>
			</Popover>
		</div>
	);
}
