// apps/web/src/lib/features/user-page/components/MutualFriends.svelte
<script lang="ts">
import Avatar from "#lib/components/Avatar.svelte";
import { m } from "#lib/paraglide/messages.js";
import type { CommonUser } from "#lib/server/kysely.ts";

const MAX_VISIBLE_AVATARS = 5;

interface Props {
	mutualFriends: Array<CommonUser>;
}

let { mutualFriends }: Props = $props();

const visibleFriends = $derived(mutualFriends.slice(0, MAX_VISIBLE_AVATARS));
const overflowCount = $derived(mutualFriends.length - MAX_VISIBLE_AVATARS);
</script>

<!--
@component
Static mutual friends avatar stack with a count, as shown on the user card.

xxx: React's `MutualFriends` also has an interactive variant (`withoutPopover={false}`, used
outside the card) where the stack is a popover trigger listing each friend as a `UserLink`;
that variant is not ported yet.
-->

{#if mutualFriends.length > 0}
	<div class="trigger">
		<div class="avatarStack">
			{#each visibleFriends as friend (friend.id)}
				<Avatar user={friend} size="xxs" class="stackedAvatar" />
			{/each}
		</div>
		{#if overflowCount > 0}
			<span class="overflow">+{overflowCount}</span>
		{/if}
		<span>
			{mutualFriends.length === 1
				? m.user_mutualFriends_count_one({ count: mutualFriends.length })
				: m.user_mutualFriends_count_other({ count: mutualFriends.length })}
		</span>
	</div>
{/if}

<style>
	.trigger {
		display: flex;
		align-items: center;
		font-size: var(--font-xs);
		font-weight: var(--weight-bold);

		span {
			color: var(--color-text-high);
		}
	}

	.avatarStack {
		display: flex;
		align-items: center;

		& :global(.stackedAvatar) {
			border-radius: 50%;
			border: 2px solid var(--color-bg);

			&:not(:first-child) {
				margin-inline-start: -8px;
			}
		}
	}

	.overflow {
		font-size: var(--font-xs);
		margin-inline: var(--s-1);
	}
</style>

// app/features/user-page/components/MutualFriends.tsx
import { useTranslation } from "react-i18next";
import { Avatar } from "~/components/Avatar";
import { SendouButton } from "~/components/elements/Button";
import { SendouPopover } from "~/components/elements/Popover";
import { UserLink } from "~/components/UserLink";
import type { CommonUser } from "~/utils/kysely.server";
import styles from "./MutualFriends.module.css";

const MAX_VISIBLE_AVATARS = 5;

export function MutualFriends({
	mutualFriends,
	withoutPopover = false,
}: {
	mutualFriends: Array<CommonUser>;
	/** When true renders a static avatar stack without the interactive popover, e.g. on the user card. */
	withoutPopover?: boolean;
}) {
	if (mutualFriends.length === 0) return null;

	if (withoutPopover) {
		return (
			<div className={styles.trigger}>
				<AvatarStack mutualFriends={mutualFriends} />
			</div>
		);
	}

	return (
		<div>
			<SendouPopover
				trigger={
					<SendouButton variant="minimal" size="small">
						<div className={styles.trigger}>
							<AvatarStack mutualFriends={mutualFriends} />
						</div>
					</SendouButton>
				}
			>
				<div className={styles.list}>
					{mutualFriends.map((friend) => (
						<UserLink
							key={friend.id}
							user={friend}
							className={styles.friendLink}
						/>
					))}
				</div>
			</SendouPopover>
		</div>
	);
}

function AvatarStack({ mutualFriends }: { mutualFriends: Array<CommonUser> }) {
	const { t } = useTranslation(["user"]);

	const visibleFriends = mutualFriends.slice(0, MAX_VISIBLE_AVATARS);
	const overflowCount = mutualFriends.length - MAX_VISIBLE_AVATARS;

	return (
		<>
			<div className={styles.avatarStack}>
				{visibleFriends.map((friend) => (
					<Avatar
						key={friend.id}
						user={friend}
						size="xxs"
						className={styles.stackedAvatar}
					/>
				))}
			</div>
			{overflowCount > 0 ? (
				<span className={styles.overflow}>+{overflowCount}</span>
			) : null}
			<span>
				{t("user:mutualFriends.count", {
					count: mutualFriends.length,
				})}
			</span>
		</>
	);
}
