// apps/web/src/lib/components/match-page/MatchBannerScheduledTime.svelte
<script lang="ts">
import TimePopover from "#lib/components/TimePopover.svelte";

const FORMAT_OPTIONS: Intl.DateTimeFormatOptions = {
	weekday: "short",
	year: "numeric",
	month: "numeric",
	day: "numeric",
	hour: "numeric",
	minute: "numeric",
};

interface Props {
	time: Date;
}

let { time }: Props = $props();
</script>

<TimePopover date={time} options={FORMAT_OPTIONS} class="font-semi-bold" />

// apps/web-react/app/components/match-page/MatchBannerScheduledTime.tsx
import TimePopover from "~/components/TimePopover";

interface MatchBannerScheduledTimeProps {
	time: Date;
}

export function MatchBannerScheduledTime({
	time,
}: MatchBannerScheduledTimeProps) {
	return (
		<TimePopover
			date={time}
			options={{
				weekday: "short",
				year: "numeric",
				month: "numeric",
				day: "numeric",
				hour: "numeric",
				minute: "numeric",
			}}
			className="font-semi-bold"
		/>
	);
}
