// app/components/Placement.tsx
import { useTranslation } from "react-i18next";
import { ordinalSuffix } from "~/utils/i18n";
import {
	FIRST_PLACEMENT_ICON_PATH,
	SECOND_PLACEMENT_ICON_PATH,
	THIRD_PLACEMENT_ICON_PATH,
} from "~/utils/urls";

export type PlacementProps = {
	placement: number;
	iconClassName?: string;
	textClassName?: string;
	size?: number;
	textOnly?: boolean;
	/** Render plain text, no icon or wrapping html elements */
	plain?: boolean;
	showAsSuperscript?: boolean;
};

const getSpecialPlacementIconPath = (placement: number): string | null => {
	switch (placement) {
		case 3:
			return THIRD_PLACEMENT_ICON_PATH;
		case 2:
			return SECOND_PLACEMENT_ICON_PATH;
		case 1:
			return FIRST_PLACEMENT_ICON_PATH;
		default:
			return null;
	}
};

export function Placement({
	placement,
	iconClassName,
	textClassName,
	size = 20,
	textOnly = false,
	showAsSuperscript = true,
	plain = false,
}: PlacementProps) {
	const { i18n } = useTranslation();

	const suffix = ordinalSuffix(placement, i18n.language);
	const isSuperscript = showAsSuperscript && suffix.startsWith("^");
	const ordinalSuffixText = suffix.replace(/^\^/, "");

	const iconPath = textOnly ? null : getSpecialPlacementIconPath(placement);

	if (plain) {
		return `${placement}${ordinalSuffixText}`;
	}

	if (!iconPath) {
		return (
			<span className={textClassName}>
				{placement}
				{isSuperscript ? <sup>{ordinalSuffixText}</sup> : ordinalSuffixText}
			</span>
		);
	}

	const placementString = `${placement}${ordinalSuffixText}`;

	return (
		<img
			alt={placementString}
			title={placementString}
			src={iconPath}
			className={iconClassName}
			height={size}
			width={size}
		/>
	);
}

// apps/web/src/lib/components/Placement.svelte
<script lang="ts">
import { getLocale } from "#lib/paraglide/runtime.js";
import { ordinalSuffix } from "#lib/utils/i18n.ts";
import {
	FIRST_PLACEMENT_ICON_PATH,
	SECOND_PLACEMENT_ICON_PATH,
	THIRD_PLACEMENT_ICON_PATH,
} from "#lib/utils/urls.ts";

interface Props {
	placement: number;
	iconClass?: string;
	textClass?: string;
	size?: number;
	textOnly?: boolean;
	showAsSuperscript?: boolean;
}

let {
	placement,
	iconClass,
	textClass,
	size = 20,
	textOnly = false,
	showAsSuperscript = true,
}: Props = $props();

const suffix = $derived(ordinalSuffix(placement, getLocale()));
const isSuperscript = $derived(showAsSuperscript && suffix.startsWith("^"));
const ordinalSuffixText = $derived(suffix.replace(/^\^/, ""));

const iconPath = $derived.by(() => {
	if (textOnly) return null;
	switch (placement) {
		case 3:
			return THIRD_PLACEMENT_ICON_PATH;
		case 2:
			return SECOND_PLACEMENT_ICON_PATH;
		case 1:
			return FIRST_PLACEMENT_ICON_PATH;
		default:
			return null;
	}
});

const placementString = $derived(`${placement}${ordinalSuffixText}`);
</script>

{#if !iconPath}
	<span class={textClass}
		>{placement}{#if isSuperscript}<sup>{ordinalSuffixText}</sup
			>{:else}{ordinalSuffixText}{/if}</span
	>
{:else}
	<img
		alt={placementString}
		title={placementString}
		src={iconPath}
		class={iconClass}
		height={size}
		width={size}
	/>
{/if}
