// app/features/friends/components/FriendMenu.tsx
import { Swords, Trash2, User } from "lucide-react";
import * as React from "react";
import { useTranslation } from "react-i18next";
import { useFetcher } from "react-router";
import { SendouButton } from "~/components/elements/Button";
import { SendouDialog } from "~/components/elements/Dialog";
import {
	SendouMenu,
	SendouMenuItem,
	SendouMenuSection,
} from "~/components/elements/Menu";
import { TwitchIcon } from "~/components/icons/Twitch";
import { ListButton } from "~/components/SideNav";
import {
	type FriendActivityBadge,
	type FriendActivityType,
	friendActivityBadge,
} from "~/features/friends/friends-constants";
import { useDateTimeFormat } from "~/hooks/intl/useDateTimeFormat";
import {
	SENDOUQ_PAGE,
	sendouQMatchPage,
	tournamentMatchPage,
	tournamentPage,
	tournamentSubsPage,
} from "~/utils/urls";

const ACTIVITY_BADGE_TRANSLATION_KEY = {
	MATCH: "friends:friendsList.inMatch",
	NEXT: "friends:friendsList.nextMatch",
} as const satisfies Record<FriendActivityBadge, string>;

export function FriendMenu({
	discordId,
	discordAvatar,
	customAvatarUrl,
	name,
	subtitle,
	badge,
	url,
	activityType,
	matchId,
	tournamentId,
	streamUrl,
	friendshipId,
	friendshipCreatedAt,
	onNavigate,
}: {
	discordId: string;
	discordAvatar: string | null;
	customAvatarUrl: string | null;
	name: string;
	subtitle: string | null;
	badge: string | null;
	url: string;
	activityType: FriendActivityType | null;
	matchId: number | null;
	tournamentId: number | null;
	streamUrl: string | null;
	friendshipId?: number;
	friendshipCreatedAt?: number | null;
	onNavigate?: () => void;
}) {
	const { t } = useTranslation(["common", "friends"]);
	const { formatter: dateFormatter } = useDateTimeFormat({
		day: "numeric",
		month: "numeric",
		year: "numeric",
	});
	const fetcher = useFetcher();
	const [confirmOpen, setConfirmOpen] = React.useState(false);

	const friendSinceText = friendshipCreatedAt
		? t("friends:friendsList.friendSince", {
				date: dateFormatter.format(friendshipCreatedAt) ?? "",
			})
		: null;

	const activityBadge = friendActivityBadge(activityType);
	const activity = resolveActivity({ activityType, matchId, tournamentId });

	return (
		<>
			<SendouMenu
				trigger={
					<ListButton
						user={{ discordId, discordAvatar, customAvatarUrl }}
						subtitle={subtitle}
						badge={
							streamUrl
								? t("friends:friendsList.live")
								: activityBadge
									? t(ACTIVITY_BADGE_TRANSLATION_KEY[activityBadge])
									: badge
						}
						badgeVariant={streamUrl ? "warning" : "default"}
					>
						{name}
					</ListButton>
				}
			>
				<SendouMenuSection headerText={friendSinceText ?? undefined}>
					<SendouMenuItem href={url} icon={<User />} onAction={onNavigate}>
						{t("friends:friendsList.viewUserPage")}
					</SendouMenuItem>
					{streamUrl ? (
						<SendouMenuItem
							href={streamUrl}
							target="_blank"
							rel="noreferrer"
							icon={<TwitchIcon />}
							onAction={onNavigate}
						>
							{t("friends:friendsList.watchStream")}
						</SendouMenuItem>
					) : null}
					{activity?.type === "join-sendouq" ? (
						<SendouMenuItem
							icon={<Swords />}
							onAction={() => {
								fetcher.submit(
									{ _action: "JOIN_QUEUE", direct: "true" },
									{ method: "post", action: SENDOUQ_PAGE },
								);
								onNavigate?.();
							}}
						>
							{t("friends:friendsList.joinSendouQ")}
						</SendouMenuItem>
					) : null}
					{activity?.type === "view-match" ? (
						<SendouMenuItem
							href={activity.url}
							icon={<Swords />}
							onAction={onNavigate}
						>
							{t("friends:friendsList.viewMatch")}
						</SendouMenuItem>
					) : null}
					{activity?.type === "view-tournament" ? (
						<SendouMenuItem
							href={activity.url}
							icon={<Swords />}
							onAction={onNavigate}
						>
							{t("friends:friendsList.viewTournament")}
						</SendouMenuItem>
					) : null}
					{friendshipId !== undefined ? (
						<SendouMenuItem
							icon={<Trash2 />}
							isDestructive
							onAction={() => setConfirmOpen(true)}
						>
							{t("friends:friendsList.deleteFriend")}
						</SendouMenuItem>
					) : null}
				</SendouMenuSection>
			</SendouMenu>
			{friendshipId !== undefined ? (
				<SendouDialog
					isOpen={confirmOpen}
					onClose={() => setConfirmOpen(false)}
					onOpenChange={() => setConfirmOpen(false)}
					isDismissable
				>
					<div className="stack md">
						<h2 className="text-md text-center">
							{t("friends:friendsList.deleteConfirm", { name })}
						</h2>
						<div className="stack horizontal md justify-center mt-2">
							<SendouButton
								variant="destructive"
								onPress={() => {
									fetcher.submit(
										{
											_action: "DELETE_FRIEND",
											friendshipId: String(friendshipId),
										},
										{ method: "post" },
									);
									setConfirmOpen(false);
								}}
							>
								{t("common:actions.delete")}
							</SendouButton>
						</div>
					</div>
				</SendouDialog>
			) : null}
		</>
	);
}

function resolveActivity(friend: {
	activityType: FriendActivityType | null;
	matchId: number | null;
	tournamentId: number | null;
}) {
	switch (friend.activityType) {
		case "SENDOUQ_MATCH":
			return friend.matchId
				? ({
						type: "view-match",
						url: sendouQMatchPage(friend.matchId),
					} as const)
				: null;
		case "TOURNAMENT_MATCH":
			return friend.tournamentId && friend.matchId
				? ({
						type: "view-match",
						url: tournamentMatchPage({
							tournamentId: friend.tournamentId,
							matchId: friend.matchId,
						}),
					} as const)
				: null;
		case "TOURNAMENT_WAITING":
			return friend.tournamentId
				? ({
						type: "view-tournament",
						url: tournamentPage(friend.tournamentId),
					} as const)
				: null;
		case "SENDOUQ":
			return { type: "join-sendouq" } as const;
		case "TOURNAMENT_SUB":
			return friend.tournamentId
				? ({
						type: "view-tournament",
						url: tournamentSubsPage(friend.tournamentId),
					} as const)
				: null;
		default:
			return null;
	}
}

// apps/web/src/lib/components/layout/FriendMenu.svelte
<script lang="ts" module>
type FriendActivityBadge = "MATCH" | "NEXT";

const ACTIVITY_BADGE: Record<FriendActivityType, FriendActivityBadge | null> = {
	SENDOUQ_MATCH: "MATCH",
	TOURNAMENT_MATCH: "MATCH",
	TOURNAMENT_WAITING: "NEXT",
	SENDOUQ: null,
	TOURNAMENT_SUB: null,
};

function resolveActivity(friend: {
	activityType: FriendActivityType | null;
	matchId: number | null;
	tournamentId: number | null;
}) {
	switch (friend.activityType) {
		case "SENDOUQ_MATCH":
			return friend.matchId
				? ({
						type: "view-match",
						url: sendouQMatchPage(friend.matchId),
					} as const)
				: null;
		case "TOURNAMENT_MATCH":
			return friend.tournamentId && friend.matchId
				? ({
						type: "view-match",
						url: `${tournamentPage(friend.tournamentId)}/matches/${friend.matchId}`,
					} as const)
				: null;
		case "TOURNAMENT_WAITING":
			return friend.tournamentId
				? ({
						type: "view-tournament",
						url: tournamentPage(friend.tournamentId),
					} as const)
				: null;
		case "SENDOUQ":
			return { type: "join-sendouq" } as const;
		case "TOURNAMENT_SUB":
			return friend.tournamentId
				? ({
						type: "view-tournament",
						url: `${tournamentPage(friend.tournamentId)}/subs`,
					} as const)
				: null;
		default:
			return null;
	}
}
</script>

<script lang="ts">
	import { Swords, User } from "@lucide/svelte";
	import { Menu, MenuItem } from "@sendou/components";
	import TwitchIcon from "#lib/components/icons/TwitchIcon.svelte";
	import { m } from "#lib/paraglide/messages.js";
	import { sendouQMatchPage, tournamentPage } from "#lib/utils/urls.ts";
	import type { FriendActivityType } from "./layout-types.ts";
	import ListButton from "./ListButton.svelte";

	interface Props {
		discordId: string;
		discordAvatar: string | null;
		customAvatarUrl: string | null;
		name: string;
		subtitle: string | null;
		badge: string | null;
		url: string;
		activityType: FriendActivityType | null;
		matchId: number | null;
		tournamentId: number | null;
		streamUrl: string | null;
		onNavigate?: () => void;
	}

	let {
		discordId,
		discordAvatar,
		customAvatarUrl,
		name,
		subtitle,
		badge,
		url,
		activityType,
		matchId,
		tournamentId,
		streamUrl,
		onNavigate,
	}: Props = $props();

	const activityBadge = $derived(
		activityType ? ACTIVITY_BADGE[activityType] : null,
	);
	const activity = $derived(
		resolveActivity({ activityType, matchId, tournamentId }),
	);

	const badgeText = $derived(
		streamUrl
			? m.friends_friendsList_live()
			: activityBadge === "MATCH"
				? m.friends_friendsList_inMatch()
				: activityBadge === "NEXT"
					? m.friends_friendsList_nextMatch()
					: badge,
	);
</script>

<Menu>
	{#snippet trigger(triggerProps)}
		<ListButton
			user={{ discordId, discordAvatar, customAvatarUrl }}
			{subtitle}
			badge={badgeText}
			badgeVariant={streamUrl ? "warning" : "default"}
			{...triggerProps}
		>
			{name}
		</ListButton>
	{/snippet}
	<MenuItem href={url}>
		{#snippet icon()}<User />{/snippet}
		{m.friends_friendsList_viewUserPage()}
	</MenuItem>
	{#if streamUrl}
		<MenuItem href={streamUrl}>
			{#snippet icon()}<TwitchIcon />{/snippet}
			{m.friends_friendsList_watchStream()}
		</MenuItem>
	{/if}
	{#if activity?.type === "view-match"}
		<MenuItem href={activity.url}>
			{#snippet icon()}<Swords />{/snippet}
			{m.friends_friendsList_viewMatch()}
		</MenuItem>
	{/if}
	{#if activity?.type === "view-tournament"}
		<MenuItem href={activity.url}>
			{#snippet icon()}<Swords />{/snippet}
			{m.friends_friendsList_viewTournament()}
		</MenuItem>
	{/if}
</Menu>
