// app/components/layout/index.tsx
import clsx from "clsx";
import { isToday, isTomorrow } from "date-fns";
import {
	Bell,
	Calendar,
	ChevronRight,
	LogIn,
	PanelLeft,
	Settings,
	Tv,
	Users,
} from "lucide-react";
import * as React from "react";
import {
	Button,
	Dialog,
	DialogTrigger,
	Modal,
	ModalOverlay,
} from "react-aria-components";
import { Flipped, Flipper } from "react-flip-toolkit";
import { useTranslation } from "react-i18next";
import { Link, useFetcher, useLocation, useMatches } from "react-router";
import { useUser } from "~/features/auth/core/user";
import { useChatContext } from "~/features/chat/useChatContext";
import { FriendMenu } from "~/features/friends/components/FriendMenu";
import { useDateTimeFormat } from "~/hooks/intl/useDateTimeFormat";
import { useHydrated } from "~/hooks/useHydrated";
import { useLayoutSize } from "~/hooks/useMainContentWidth";
import { useVisualViewportHeight } from "~/hooks/useVisualViewportHeight";
import type { RootLoaderData } from "~/root";
import type { Breadcrumb, SendouRouteHandle } from "~/utils/remix.server";
import {
	EVENTS_PAGE,
	FRIENDS_PAGE,
	SETTINGS_PAGE,
	userPage,
} from "~/utils/urls";
import { Avatar } from "../Avatar";
import { SendouButton } from "../elements/Button";
import { SendouPopover } from "../elements/Popover";
import { FuseZone } from "../fuse/Fuse";
import { Image } from "../Image";
import { MobileNav } from "../MobileNav";
import { NotificationDot } from "../NotificationDot";
import { ListLink, SideNav, SideNavFooter, SideNavHeader } from "../SideNav";
import sideNavStyles from "../SideNav.module.css";
import { StreamListItems } from "../StreamListItems";
import { AuthErrorDialog } from "./AuthErrorDialog";
import { ChatSidebar } from "./ChatSidebar";
import { Footer } from "./Footer";
import styles from "./index.module.css";
import { LogInButtonContainer } from "./LogInButtonContainer";
import { NotificationContent, useNotifications } from "./NotificationPopover";
import notificationPopoverStyles from "./NotificationPopover.module.css";
import { TopNavMenus } from "./TopNavMenus";
import { TopRightButtons } from "./TopRightButtons";

const MAX_DESKTOP_FRIENDS = 4;

function useRelativeDayFormat() {
	const { i18n } = useTranslation();
	const { formatter: timeFormatter } = useDateTimeFormat({
		hour: "numeric",
		minute: "numeric",
	});
	const { formatter: dateTimeFormatter } = useDateTimeFormat({
		month: "numeric",
		day: "numeric",
		hour: "numeric",
		minute: "numeric",
	});

	const formatRelativeDay = (daysFromToday: number) => {
		const rtf = new Intl.RelativeTimeFormat(i18n.language, { numeric: "auto" });
		const str = rtf.format(daysFromToday, "day");
		return str.charAt(0).toUpperCase() + str.slice(1);
	};

	const formatRelativeDate = (timestamp: number) => {
		const date = new Date(timestamp * 1000);
		const timeStr = timeFormatter.format(date);

		if (isToday(date)) {
			return `${formatRelativeDay(0)}, ${timeStr}`;
		}
		if (isTomorrow(date)) {
			return `${formatRelativeDay(1)}, ${timeStr}`;
		}

		return dateTimeFormatter.format(date);
	};

	return { formatRelativeDate };
}

function useBreadcrumbData() {
	const { t } = useTranslation();
	const matches = useMatches();

	const breadcrumbs: Breadcrumb[] = [];

	for (const match of [...matches].reverse()) {
		const handle = match.handle as SendouRouteHandle | undefined;
		const resolved = handle?.breadcrumb?.({ match, t });
		if (resolved) {
			const items = Array.isArray(resolved) ? resolved : [resolved];
			breadcrumbs.push(...items);
		}
	}

	return {
		breadcrumbs,
		currentPageText: breadcrumbs.at(-1)?.text,
	};
}

function useSideNavCollapsed(initialCollapsed: boolean) {
	const [collapsed, setCollapsed] = React.useState(initialCollapsed);
	const fetcher = useFetcher();

	const setCollapsedAndPersist = (value: boolean) => {
		setCollapsed(value);
		fetcher.submit(
			{ collapsed: String(value) },
			{ method: "POST", action: "/sidenav" },
		);
	};

	return [collapsed, setCollapsedAndPersist] as const;
}

function useNavOffset(headerRef: React.RefObject<HTMLElement | null>) {
	const [navOffset, setNavOffset] = React.useState(0);
	const lastScrollY = React.useRef(0);

	const MOBILE_BREAKPOINT = 600;
	const NAV_HEIGHT_FALLBACK = 55;
	const SCROLL_THRESHOLD_PX = 200;

	const scrollAccumulator = React.useRef(0);

	React.useEffect(() => {
		const handleScroll = () => {
			if (window.innerWidth >= MOBILE_BREAKPOINT) {
				setNavOffset(0);
				lastScrollY.current = window.scrollY;
				scrollAccumulator.current = 0;
				return;
			}

			const navHeight = headerRef.current?.offsetHeight ?? NAV_HEIGHT_FALLBACK;
			const currentScrollY = window.scrollY;
			const scrollDelta = currentScrollY - lastScrollY.current;

			const directionChanged =
				(scrollDelta > 0 && scrollAccumulator.current < 0) ||
				(scrollDelta < 0 && scrollAccumulator.current > 0);

			if (directionChanged) {
				scrollAccumulator.current = 0;
			}

			scrollAccumulator.current += scrollDelta;

			if (Math.abs(scrollAccumulator.current) >= SCROLL_THRESHOLD_PX) {
				const overflow =
					scrollAccumulator.current > 0
						? scrollAccumulator.current - SCROLL_THRESHOLD_PX
						: scrollAccumulator.current + SCROLL_THRESHOLD_PX;

				setNavOffset((prevOffset) => {
					const newOffset = prevOffset - overflow;
					return Math.max(-navHeight, Math.min(0, newOffset));
				});

				scrollAccumulator.current =
					scrollAccumulator.current > 0
						? SCROLL_THRESHOLD_PX
						: -SCROLL_THRESHOLD_PX;
			}

			lastScrollY.current = currentScrollY;
		};

		const handleResize = () => {
			if (window.innerWidth >= MOBILE_BREAKPOINT) {
				setNavOffset(0);
			}
		};

		window.addEventListener("scroll", handleScroll, { passive: true });
		window.addEventListener("resize", handleResize);

		return () => {
			window.removeEventListener("scroll", handleScroll);
			window.removeEventListener("resize", handleResize);
		};
	}, [headerRef]);

	return navOffset;
}

export function Layout({
	children,
	data,
}: {
	children: React.ReactNode;
	data?: RootLoaderData;
}) {
	const chatContext = useChatContext();
	const [sideNavCollapsed, setSideNavCollapsed] = useSideNavCollapsed(
		data?.sidenavCollapsed ?? false,
	);
	const [sideNavModalOpen, setSideNavModalOpen] = React.useState(false);
	const [chatSidebarModalOpen, setChatSidebarModalOpen] = React.useState(false);

	const layoutSize = useLayoutSize();
	useVisualViewportHeight();
	const chatSidebarOpen = chatContext?.chatOpen ?? false;
	const setChatSidebarOpen = chatContext?.setChatOpen ?? (() => {});

	const setChatSidebarModalOpenAndSync = (open: boolean) => {
		setChatSidebarModalOpen(open);
		setChatSidebarOpen(open);
	};

	const { t } = useTranslation(["front", "common"]);
	const { formatRelativeDate } = useRelativeDayFormat();
	const isHydrated = useHydrated();
	const location = useLocation();
	const headerRef = React.useRef<HTMLElement>(null);
	const navOffset = useNavOffset(headerRef);

	React.useEffect(() => {
		const handleResize = () => {
			if (window.innerWidth < 600 || window.innerWidth >= 1000) {
				setSideNavModalOpen(false);
				setChatSidebarModalOpen(false);
			}
		};

		window.addEventListener("resize", handleResize);
		return () => window.removeEventListener("resize", handleResize);
	}, []);

	// biome-ignore lint/correctness/useExhaustiveDependencies: intentionally close modals on navigation
	React.useEffect(() => {
		setSideNavModalOpen(false);
		setChatSidebarModalOpen(false);
	}, [location.pathname]);

	const user = useUser();
	const { unseenIds } = useNotifications();
	const sidebarData = data?.sidebar;
	const events = sidebarData?.events ?? [];
	const friends = sidebarData?.friends ?? [];
	const streams = sidebarData?.streams ?? [];

	const isFrontPage = location.pathname === "/";

	const showLeaderboard =
		import.meta.env.VITE_FUSE_ENABLED &&
		!data?.user?.roles.includes("MINOR_SUPPORT") &&
		!location.pathname.includes("plans");

	const sideNavFooterContent = (
		<SideNavFooter>
			<SideNavUserPanel />
		</SideNavFooter>
	);

	const sideNavChildren = (
		<>
			<SideNavHeader
				icon={<Calendar />}
				action={
					user ? (
						<Link to={EVENTS_PAGE} className={styles.viewAllLink}>
							{t("common:actions.viewAll")}
							<ChevronRight size={14} />
						</Link>
					) : null
				}
			>
				{t("front:sideNav.myCalendar")}
			</SideNavHeader>
			{events.length > 0 ? (
				events.map((event) => (
					<ListLink
						key={`${event.type}-${event.id}`}
						to={event.url}
						imageUrl={event.logoUrl ?? undefined}
						subtitle={
							isHydrated ? (
								formatRelativeDate(event.startTime)
							) : (
								<span className="invisible">Placeholder</span>
							)
						}
					>
						{event.scrimStatus === "booked"
							? t("front:sideNav.scrimVs", { opponent: event.name })
							: event.scrimStatus === "looking"
								? t("front:sideNav.lookingForScrim")
								: event.scrimStatus === "requestPending"
									? t("front:sideNav.scrimRequestPending")
									: event.name}
					</ListLink>
				))
			) : (
				<div className={styles.sideNavEmpty}>{t("front:sideNav.noEvents")}</div>
			)}

			<SideNavHeader
				icon={<Users />}
				action={
					user ? (
						<Link to={FRIENDS_PAGE} className={styles.viewAllLink}>
							{t("common:actions.viewAll")}
							<ChevronRight size={14} />
						</Link>
					) : null
				}
			>
				{t("front:sideNav.friends")}
			</SideNavHeader>
			{friends.length > 0 ? (
				friends
					.slice(0, MAX_DESKTOP_FRIENDS)
					.map((friend) => <FriendMenu key={friend.id} {...friend} />)
			) : (
				<div className={styles.sideNavEmpty}>
					{user
						? t("front:sideNav.friends.noFriends")
						: t("front:sideNav.friends.notLoggedIn")}
				</div>
			)}

			<SideNavHeader icon={<Tv />}>{t("front:sideNav.streams")}</SideNavHeader>
			{streams.length === 0 ? (
				<div className={styles.sideNavEmpty}>
					{t("front:sideNav.noStreams")}
				</div>
			) : null}
			<StreamListItems
				streams={streams}
				isLoggedIn={Boolean(user)}
				savedTournamentIds={sidebarData?.savedTournamentIds}
			/>
		</>
	);

	return (
		<>
			<SideNav
				className={showLeaderboard ? styles.sidebarFuseSpace : undefined}
				collapsed={sideNavCollapsed}
				footer={sideNavFooterContent}
				top={<SiteTitle />}
				topCentered={isFrontPage}
			>
				{sideNavChildren}
			</SideNav>
			<MobileNav sidebarData={data?.sidebar} />
			<div className={styles.container}>
				<header
					ref={headerRef}
					className={styles.header}
					style={{
						transform: `translateY(${navOffset}px)`,
					}}
				>
					<Link to="/" className={clsx(styles.siteLogo, styles.mobileLogo)}>
						<SiteLogoContent />
					</Link>
					<DialogTrigger
						isOpen={sideNavModalOpen}
						onOpenChange={setSideNavModalOpen}
					>
						<SideNavCollapseButton
							className={styles.sideNavModalTrigger}
							showNotificationDot={!sideNavModalOpen && unseenIds.length > 0}
							testId="sidenav-modal-trigger"
						/>
						<ModalOverlay className={styles.sideNavModalOverlay} isDismissable>
							<Modal className={styles.sideNavModal}>
								<Dialog className={styles.sideNavModalDialog}>
									<SideNav
										className={styles.sideNavInModal}
										footer={sideNavFooterContent}
										top={<SiteTitle />}
										topCentered={isFrontPage}
									>
										{sideNavChildren}
									</SideNav>
								</Dialog>
							</Modal>
						</ModalOverlay>
					</DialogTrigger>
					<ModalOverlay
						className={styles.chatSidebarModalOverlay}
						isDismissable
						isOpen={chatSidebarModalOpen}
						onOpenChange={setChatSidebarModalOpenAndSync}
					>
						<Modal className={styles.chatSidebarModal}>
							<Dialog
								className={styles.chatSidebarModalDialog}
								aria-label={t("common:chat.sidebar.title")}
							>
								<ChatSidebar />
							</Dialog>
						</Modal>
					</ModalOverlay>
					<SideNavCollapseButton
						onToggle={() => setSideNavCollapsed(!sideNavCollapsed)}
						className={styles.sideNavCollapseButton}
						showNotificationDot={sideNavCollapsed && unseenIds.length > 0}
						testId="sidenav-collapse-button"
					/>
					<TopNavMenus />
					<TopRightButtons
						showSupport={Boolean(
							data && !data?.user?.roles.includes("MINOR_SUPPORT"),
						)}
						showSearch={Boolean(data?.user)}
						isLoggedIn={Boolean(data?.user)}
						onChatToggle={
							data?.user && !chatSidebarOpen
								? () => setChatSidebarOpen(true)
								: undefined
						}
						onChatModalToggle={
							data?.user
								? () => setChatSidebarModalOpenAndSync(!chatSidebarModalOpen)
								: undefined
						}
						chatUnreadCount={chatContext?.totalUnreadCount}
					/>
				</header>
				{showLeaderboard ? (
					<FuseZone
						id="fuse-header"
						fuseSlot="header"
						className="top-leaderboard"
					/>
				) : null}
				{children}
				<Footer />
			</div>
			{chatSidebarOpen && layoutSize === "desktop" ? (
				<div
					className={clsx(
						styles.chatSidebar,
						showLeaderboard && styles.sidebarFuseSpace,
					)}
				>
					<ChatSidebar onClose={() => setChatSidebarOpen(false)} />
				</div>
			) : null}
			<AuthErrorDialog />
		</>
	);
}

function SiteTitle() {
	const location = useLocation();
	const { breadcrumbs, currentPageText } = useBreadcrumbData();

	const isFrontPage = location.pathname === "/";
	const hasBreadcrumbs = breadcrumbs.length > 0;

	return (
		<Flipper
			flipKey={isFrontPage ? "front" : "other"}
			className={styles.siteTitleFlipper}
		>
			<div className={styles.siteTitle}>
				<Flipped flipId="site-logo">
					<Link to="/" className={styles.siteLogo}>
						<SiteLogoContent />
					</Link>
				</Flipped>

				{hasBreadcrumbs ? (
					<>
						{breadcrumbs.map((crumb) => {
							const isCurrentPage = location.pathname === crumb.href;

							return (
								<React.Fragment key={crumb.href}>
									<span className={styles.separator}>/</span>
									{isCurrentPage ? (
										<PageIcon crumb={crumb} />
									) : (
										<Link to={crumb.href} className={styles.breadcrumbLink}>
											<PageIcon crumb={crumb} />
										</Link>
									)}
								</React.Fragment>
							);
						})}

						{currentPageText ? (
							<span className={styles.pageName}>{currentPageText}</span>
						) : null}
					</>
				) : null}
			</div>
		</Flipper>
	);
}

function SiteLogoContent() {
	return (
		<>
			<span className={styles.siteLogoS}>S</span>
			<span className={styles.siteLogoInk}>ink</span>
		</>
	);
}

function SideNavCollapseButton({
	onToggle,
	className,
	showNotificationDot,
	testId,
}: {
	onToggle?: () => void;
	className?: string;
	showNotificationDot?: boolean;
	testId?: string;
}) {
	return (
		<div className={styles.sideNavCollapseButtonContainer} data-testid={testId}>
			<SendouButton
				className={className}
				variant="minimal"
				size="small"
				shape="square"
				icon={<PanelLeft />}
				onPress={onToggle}
			/>
			{showNotificationDot ? <NotificationDot /> : null}
		</div>
	);
}

function PageIcon({ crumb }: { crumb: Breadcrumb }) {
	if (crumb.type !== "IMAGE") {
		return null;
	}

	const isExternal = crumb.imgPath.includes(".");
	const iconClass = clsx(styles.pageIcon, "rounded");

	return (
		<div className={styles.pageIconWrapper}>
			{isExternal ? (
				<img
					src={crumb.imgPath}
					alt=""
					className={iconClass}
					width={28}
					height={28}
				/>
			) : (
				<Image
					path={crumb.imgPath}
					alt=""
					className={iconClass}
					width={20}
					height={20}
				/>
			)}
		</div>
	);
}

function SideNavUserPanel() {
	const { t } = useTranslation();
	const location = useLocation();
	const user = useUser();
	const { notifications, unseenIds } = useNotifications();

	if (user) {
		return (
			<>
				<Link to={userPage(user)} className={sideNavStyles.sideNavFooterUser}>
					<Avatar user={user} size="xs" />
					<span className={sideNavStyles.sideNavFooterUsername}>
						{user.username}
					</span>
				</Link>
				<div className={sideNavStyles.sideNavFooterActions}>
					{notifications ? (
						<div
							className={sideNavStyles.sideNavFooterNotification}
							key={location.pathname}
						>
							{unseenIds.length > 0 ? (
								<NotificationDot
									className={sideNavStyles.sideNavFooterUnseenDot}
								/>
							) : null}
							<SendouPopover
								trigger={
									<Button
										className={sideNavStyles.sideNavFooterButton}
										data-testid="notifications-button"
									>
										<Bell />
									</Button>
								}
								popoverClassName={clsx(
									notificationPopoverStyles.popoverContainer,
									{
										[notificationPopoverStyles.noNotificationsContainer]:
											notifications.length === 0,
									},
								)}
							>
								<NotificationContent
									notifications={notifications}
									unseenIds={unseenIds}
								/>
							</SendouPopover>
						</div>
					) : null}
					<Link
						to={SETTINGS_PAGE}
						className={sideNavStyles.sideNavFooterButton}
					>
						<Settings />
					</Link>
				</div>
			</>
		);
	}

	return (
		<>
			<LogInButtonContainer>
				<SendouButton type="submit" size="small" icon={<LogIn />}>
					{t("header.login.discord")}
				</SendouButton>
			</LogInButtonContainer>
			<div className={sideNavStyles.sideNavFooterActions}>
				<Link to={SETTINGS_PAGE} className={sideNavStyles.sideNavFooterButton}>
					<Settings />
				</Link>
			</div>
		</>
	);
}

// apps/web/src/lib/components/layout/Layout.svelte
<script lang="ts">
	import { Calendar, ChevronRight, PanelLeft, Tv, Users } from "@lucide/svelte";
	import type { Snippet } from "svelte";
	import { page } from "$app/state";
	import Image from "#lib/components/Image.svelte";
	import NotificationDot from "#lib/components/NotificationDot.svelte";
	import { loggedInUser } from "#lib/features/auth/user-state.ts";
	import { getPatrons } from "#lib/features/front-page/front-page.remote.ts";
	import { getNotifications } from "#lib/features/notifications/notifications.remote.ts";
	import { toNotificationRows } from "#lib/features/notifications/notifications-utils.ts";
	import { m } from "#lib/paraglide/messages.js";
	import { getLocale } from "#lib/paraglide/runtime.js";
	import { GIT_COMMIT } from "#lib/utils/git-commit.ts";
	import { EVENTS_PAGE, FRIENDS_PAGE } from "#lib/utils/urls.ts";
	import Footer from "./Footer.svelte";
	import FriendMenu from "./FriendMenu.svelte";
	import type { NotificationRow, SidebarData } from "./layout-types.ts";
	import ListLink from "./ListLink.svelte";
	import MobileNav from "./MobileNav.svelte";
	import SideNav from "./SideNav.svelte";
	import SideNavFooter from "./SideNavFooter.svelte";
	import SideNavHeader from "./SideNavHeader.svelte";
	import SideNavUserPanel from "./SideNavUserPanel.svelte";
	import StreamListItems from "./StreamListItems.svelte";
	import TopNavMenus from "./TopNavMenus.svelte";
	import TopRightButtons from "./TopRightButtons.svelte";

	const MAX_DESKTOP_FRIENDS = 4;

	interface Breadcrumb {
		type: "IMAGE" | "TEXT";
		imgPath?: string;
		href: string;
		text?: string;
		identiconInput?: string;
	}

	interface Props {
		children: Snippet;
	}

	let { children }: Props = $props();

	const user = $derived(loggedInUser());
	const sidebarData = $derived(
		(page.data as { sidebar?: SidebarData }).sidebar,
	);
	const initialCollapsed =
		(page.data as { sidenavCollapsed?: boolean }).sidenavCollapsed ?? false;

	// svelte-ignore state_referenced_locally -- the cookie value seeds the initial state only
	let sideNavCollapsed = $state(initialCollapsed);
	let sideNavModalOpen = $state(false);
	let hydrated = $state(false);

	let notifications = $state<NotificationRow[] | null>(null);

	$effect(() => {
		hydrated = true;
	});

	// the bell data loads lazily like the React app's NotificationsProvider:
	// after hydration, never blocking SSR
	$effect(() => {
		if (!user) {
			notifications = null;
			return;
		}
		void getNotifications().then((result) => {
			notifications = result.notifications
				? toNotificationRows(result.notifications)
				: null;
		});
	});

	const unseenIds = $derived(
		notifications
			?.filter((notification) => !notification.seen)
			.map((notification) => notification.id) ?? [],
	);
	const showUnseenDot = $derived(unseenIds.length > 0);

	const patrons = $derived(await getPatrons());

	const events = $derived(sidebarData?.events ?? []);
	const friends = $derived(sidebarData?.friends ?? []);
	const streams = $derived(sidebarData?.streams ?? []);
	const unseenFriendRequests = $derived(
		sidebarData?.incomingFriendRequestIds.length ?? 0,
	);

	const isFrontPage = $derived(page.url.pathname === "/");

	const breadcrumbs = $derived(
		((page.data as { breadcrumbs?: Breadcrumb[] }).breadcrumbs ?? []),
	);
	const currentPageText = $derived(breadcrumbs.at(-1)?.text);

	function unseenRequestsLabel(count: number) {
		return count === 1
			? m.friends_unseenRequests_one({ count })
			: m.friends_unseenRequests_other({ count });
	}

	function toggleSideNavCollapsed() {
		sideNavCollapsed = !sideNavCollapsed;
		void fetch("/sidenav", {
			method: "POST",
			body: new URLSearchParams({ collapsed: String(sideNavCollapsed) }),
		});
	}

	// mobile hide-on-scroll header, ported from the React useNavOffset
	let headerElement = $state<HTMLElement | null>(null);
	let navOffset = $state(0);

	$effect(() => {
		const MOBILE_BREAKPOINT = 600;
		const NAV_HEIGHT_FALLBACK = 55;
		const SCROLL_THRESHOLD_PX = 200;

		let lastScrollY = 0;
		let scrollAccumulator = 0;

		const handleScroll = () => {
			if (window.innerWidth >= MOBILE_BREAKPOINT) {
				navOffset = 0;
				lastScrollY = window.scrollY;
				scrollAccumulator = 0;
				return;
			}

			const navHeight = headerElement?.offsetHeight ?? NAV_HEIGHT_FALLBACK;
			const currentScrollY = window.scrollY;
			const scrollDelta = currentScrollY - lastScrollY;

			const directionChanged =
				(scrollDelta > 0 && scrollAccumulator < 0) ||
				(scrollDelta < 0 && scrollAccumulator > 0);

			if (directionChanged) {
				scrollAccumulator = 0;
			}

			scrollAccumulator += scrollDelta;

			if (Math.abs(scrollAccumulator) >= SCROLL_THRESHOLD_PX) {
				const overflow =
					scrollAccumulator > 0
						? scrollAccumulator - SCROLL_THRESHOLD_PX
						: scrollAccumulator + SCROLL_THRESHOLD_PX;

				navOffset = Math.max(
					-navHeight,
					Math.min(0, navOffset - overflow),
				);

				scrollAccumulator =
					scrollAccumulator > 0 ? SCROLL_THRESHOLD_PX : -SCROLL_THRESHOLD_PX;
			}

			lastScrollY = currentScrollY;
		};

		const handleResize = () => {
			if (window.innerWidth >= MOBILE_BREAKPOINT) {
				navOffset = 0;
			}
		};

		window.addEventListener("scroll", handleScroll, { passive: true });
		window.addEventListener("resize", handleResize);

		return () => {
			window.removeEventListener("scroll", handleScroll);
			window.removeEventListener("resize", handleResize);
		};
	});

	// the tablet-only sidenav modal closes on navigation
	$effect(() => {
		page.url.pathname;
		sideNavModalOpen = false;
	});

	function formatRelativeDate(timestamp: number) {
		const locale = getLocale();
		const date = new Date(timestamp * 1000);
		const timeFormatter = new Intl.DateTimeFormat(locale, {
			hour: "numeric",
			minute: "numeric",
		});
		const dateTimeFormatter = new Intl.DateTimeFormat(locale, {
			month: "numeric",
			day: "numeric",
			hour: "numeric",
			minute: "numeric",
		});

		const now = new Date();
		const isToday = date.toDateString() === now.toDateString();
		const tomorrow = new Date(now);
		tomorrow.setDate(now.getDate() + 1);
		const isTomorrow = date.toDateString() === tomorrow.toDateString();

		const formatRelativeDay = (daysFromToday: number) => {
			const rtf = new Intl.RelativeTimeFormat(locale, { numeric: "auto" });
			const str = rtf.format(daysFromToday, "day");
			return str.charAt(0).toUpperCase() + str.slice(1);
		};

		if (isToday) return `${formatRelativeDay(0)}, ${timeFormatter.format(date)}`;
		if (isTomorrow) {
			return `${formatRelativeDay(1)}, ${timeFormatter.format(date)}`;
		}

		return dateTimeFormatter.format(date);
	}
</script>

{#snippet siteLogoContent()}
	<span class="siteLogoS">S</span>
	<span class="siteLogoInk">ink</span>
{/snippet}

{#snippet siteTitle()}
	<div class="siteTitle">
		<a href="/" class="siteLogo">
			{@render siteLogoContent()}
		</a>
		{#each breadcrumbs as crumb (crumb.href)}
			<span class="separator">/</span>
			{#if page.url.pathname === crumb.href}
				{@render pageIcon(crumb)}
			{:else}
				<a href={crumb.href} class="breadcrumbLink">
					{@render pageIcon(crumb)}
				</a>
			{/if}
		{/each}
		{#if currentPageText}
			<span class="pageName">{currentPageText}</span>
		{/if}
	</div>
{/snippet}

{#snippet pageIcon(crumb: Breadcrumb)}
	{#if crumb.type === "IMAGE" && crumb.imgPath}
		<div class="pageIconWrapper">
			<Image
				path={crumb.imgPath}
				alt=""
				class="pageIcon rounded"
				width={20}
				height={20}
			/>
		</div>
	{/if}
{/snippet}

{#snippet sideNavFooterContent()}
	<SideNavFooter>
		<SideNavUserPanel {notifications} {unseenIds} {showUnseenDot} />
	</SideNavFooter>
{/snippet}

{#snippet sideNavChildren()}
	<SideNavHeader>
		{#snippet icon()}<Calendar />{/snippet}
		{#snippet action()}
			{#if user}
				<a href={EVENTS_PAGE} class="viewAllLink">
					{m.common_actions_viewAll()}
					<ChevronRight size={14} />
				</a>
			{/if}
		{/snippet}
		{m.front_sideNav_myCalendar()}
	</SideNavHeader>
	{#each events as event (`${event.type}-${event.id}`)}
		<ListLink
			to={event.url}
			imageUrl={event.logoUrl ?? undefined}
			user={event.user ?? undefined}
		>
			{#snippet subtitle()}
				{#if hydrated}
					{formatRelativeDate(event.startsAt)}
				{:else}
					<span class="invisible">Placeholder</span>
				{/if}
			{/snippet}
			{event.scrimStatus === "booked"
				? m.front_sideNav_scrimVs({ opponent: event.name })
				: event.scrimStatus === "looking"
					? m.front_sideNav_lookingForScrim()
					: event.scrimStatus === "requestPending"
						? m.front_sideNav_scrimRequestPending()
						: event.name}
		</ListLink>
	{:else}
		<div data-testid="side-nav-empty" class="sideNavEmpty">
			{m.front_sideNav_noEvents()}
		</div>
	{/each}

	<SideNavHeader>
		{#snippet icon()}<Users />{/snippet}
		{#snippet action()}
			{#if user}
				{#if unseenFriendRequests > 0}
					<span
						class="friendRequestsBadge"
						role="status"
						aria-label={unseenRequestsLabel(unseenFriendRequests)}
					>
						{unseenFriendRequests}
					</span>
				{/if}
				<a href={FRIENDS_PAGE} class="viewAllLink">
					{m.common_actions_viewAll()}
					<ChevronRight size={14} />
				</a>
			{/if}
		{/snippet}
		{m.front_sideNav_friends()}
	</SideNavHeader>
	{#each friends.slice(0, MAX_DESKTOP_FRIENDS) as friend (friend.id)}
		<FriendMenu {...friend} />
	{:else}
		<div data-testid="side-nav-empty" class="sideNavEmpty">
			{user
				? m.front_sideNav_friends_noFriends()
				: m.front_sideNav_friends_notLoggedIn()}
		</div>
	{/each}

	<SideNavHeader>
		{#snippet icon()}<Tv />{/snippet}
		{m.front_sideNav_streams()}
	</SideNavHeader>
	{#if streams.length === 0}
		<div data-testid="side-nav-empty" class="sideNavEmpty">
			{m.front_sideNav_noStreams()}
		</div>
	{/if}
	<StreamListItems
		{streams}
		isLoggedIn={Boolean(user)}
		savedTournamentIds={sidebarData?.savedTournamentIds}
	/>
{/snippet}

<SideNav
	collapsed={sideNavCollapsed}
	topCentered={isFrontPage}
>
	{#snippet top()}{@render siteTitle()}{/snippet}
	{#snippet footer()}{@render sideNavFooterContent()}{/snippet}
	{@render sideNavChildren()}
</SideNav>
<MobileNav
	{sidebarData}
	notifications={notifications ?? undefined}
	unseenNotificationIds={unseenIds}
	{showUnseenDot}
/>
<div class="container">
	<header
		bind:this={headerElement}
		class="header"
		style="transform: translateY({navOffset}px)"
	>
		<a href="/" class="siteLogo mobileLogo">
			{@render siteLogoContent()}
		</a>
		<div class="sideNavCollapseButtonContainer" data-testid="sidenav-modal-trigger">
			<button
				type="button"
				class="collapseButton sideNavModalTrigger"
				onclick={() => {
					sideNavModalOpen = !sideNavModalOpen;
				}}
			>
				<PanelLeft />
			</button>
			{#if !sideNavModalOpen && showUnseenDot}
				<NotificationDot />
			{/if}
			{#if !sideNavModalOpen && unseenFriendRequests > 0}
				<span
					class={[
						"sideNavCollapseBadge",
						{ sideNavCollapseBadgeLeft: showUnseenDot },
					]}
					role="status"
					aria-label={unseenRequestsLabel(unseenFriendRequests)}
				>
					{unseenFriendRequests}
				</span>
			{/if}
		</div>
		<div
			class="sideNavCollapseButtonContainer"
			data-testid="sidenav-collapse-button"
		>
			<button
				type="button"
				class="collapseButton sideNavCollapseButton"
				onclick={toggleSideNavCollapsed}
			>
				<PanelLeft />
			</button>
			{#if sideNavCollapsed && showUnseenDot}
				<NotificationDot />
			{/if}
			{#if sideNavCollapsed && unseenFriendRequests > 0}
				<span
					class={[
						"sideNavCollapseBadge",
						{ sideNavCollapseBadgeLeft: showUnseenDot },
					]}
					role="status"
					aria-label={unseenRequestsLabel(unseenFriendRequests)}
				>
					{unseenFriendRequests}
				</span>
			{/if}
		</div>
		<TopNavMenus />
		<TopRightButtons
			showSupport={Boolean(!user?.roles.includes("MINOR_SUPPORT"))}
			showSearch={Boolean(user)}
			isLoggedIn={Boolean(user)}
			chatUnreadCount={0}
		/>
		<div id="nprogress-anchor" aria-hidden="true"></div>
	</header>
	{@render children()}
	<Footer {patrons} gitCommit={GIT_COMMIT} />
</div>

{#if sideNavModalOpen}
	<!-- svelte-ignore a11y_click_events_have_key_events, a11y_no_static_element_interactions -->
	<div
		class="sideNavModalOverlay"
		onclick={(event) => {
			if (event.target === event.currentTarget) sideNavModalOpen = false;
		}}
	>
		<div class="sideNavModal">
			<SideNav class="sideNavInModal" topCentered={isFrontPage}>
				{#snippet top()}{@render siteTitle()}{/snippet}
				{#snippet footer()}{@render sideNavFooterContent()}{/snippet}
				{@render sideNavChildren()}
			</SideNav>
		</div>
	</div>
{/if}

<style>
	.container {
		flex: 1;
		min-width: 0;
	}

	.header {
		container-type: inline-size;
		display: flex;
		width: 100%;
		height: var(--layout-nav-height);
		align-items: center;
		gap: var(--s-2);
		border-bottom: 1.5px solid var(--color-border);
		background-color: var(--color-bg-nav);
		font-weight: var(--weight-extra);
		padding-inline: var(--s-4);
		position: sticky;
		top: 0;
		z-index: 10;
	}

	.siteTitle {
		display: flex;
		align-items: center;
		gap: var(--s-2);
		height: 100%;
		min-width: 0;
		padding: 3px;
		margin: -3px;
	}

	.siteLogo {
		display: flex;
		flex-direction: row;
		align-items: center;
		justify-content: center;
		width: 40px;
		height: 36px;
		background-color: var(--color-text-accent);
		border-radius: var(--radius-field);
		font-weight: var(--weight-bold);
		color: var(--color-text-inverse);
		text-decoration: none;
		flex-shrink: 0;
		transition: background-color 0.2s;
		line-height: 1;

		&:focus-visible {
			outline: var(--focus-ring);
			outline-offset: 1px;
		}
	}

	.siteLogoS {
		font-size: 14px;
		position: relative;
		top: -4px;
	}

	.siteLogoInk {
		font-size: 12px;
		position: relative;
		bottom: -4px;
	}

	.separator {
		font-size: var(--font-xs);
		color: var(--color-text-high);
		font-weight: var(--weight-bold);
		opacity: 0.5;
		animation: fadeIn 200ms ease-out 150ms both;
	}

	@keyframes fadeIn {
		from {
			opacity: 0;
		}
		to {
			opacity: 0.5;
		}
	}

	.pageIconWrapper {
		display: flex;
		align-items: center;
		flex-shrink: 0;
		width: 28px;
		height: 28px;
		animation: fadeInFull 200ms ease-out 150ms both;
	}

	.pageIconWrapper :global(.pageIcon) {
		width: 28px;
		height: 28px;
		object-fit: cover;
	}

	@keyframes fadeInFull {
		from {
			opacity: 0;
		}
		to {
			opacity: 1;
		}
	}

	.breadcrumbLink {
		display: flex;
		align-items: center;
		text-decoration: none;
		border-radius: var(--radius-field);

		&:focus-visible {
			outline: var(--focus-ring);
			outline-offset: 1px;
		}
	}

	.pageName {
		font-size: var(--font-xs);
		font-weight: var(--weight-semi);
		color: var(--color-text);
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
		min-width: 0;
		animation: fadeInFull 200ms ease-out 150ms both;
	}

	@media screen and (display-mode: standalone) {
		.header {
			align-items: flex-end;
			padding-top: calc(var(--s-2) + env(safe-area-inset-top));
			padding-bottom: var(--s-2);
			height: calc(var(--layout-nav-height) + env(safe-area-inset-top));
		}

		.sideNavModalOverlay {
			top: calc(var(--layout-nav-height) + env(safe-area-inset-top));
		}
	}

	:global(.sideNavEmpty) {
		font-size: var(--font-2xs);
		color: var(--color-text-high);
		padding: var(--s-1) var(--s-2);
		margin: 0 auto;
		font-style: italic;
	}

	:global(.viewAllLink) {
		display: flex;
		align-items: center;
		gap: 2px;
	}

	:global(.viewAllLink svg) {
		stroke-width: 3;
	}

	:global(.friendRequestsBadge) {
		font-size: var(--font-2xs);
		font-weight: var(--weight-bold);
		color: var(--color-text-inverse);
		background-color: var(--color-text-accent);
		min-width: 18px;
		height: 18px;
		padding: 0 var(--s-1);
		border-radius: 9px;
		display: grid;
		place-items: center;
		margin-inline-end: var(--s-1-5);
		pointer-events: none;
	}

	.sideNavCollapseBadge {
		position: absolute;
		top: -5px;
		inset-inline-end: -5px;
		font-size: var(--font-2xs);
		font-weight: var(--weight-bold);
		color: var(--color-text-inverse);
		background-color: var(--color-text-accent);
		min-width: 16px;
		height: 16px;
		padding: 0 var(--s-0-5);
		border-radius: 8px;
		display: grid;
		place-items: center;
		line-height: 1;
		pointer-events: none;

		&.sideNavCollapseBadgeLeft {
			inset-inline-end: auto;
			inset-inline-start: -5px;
		}
	}

	.sideNavCollapseButtonContainer {
		display: none;
		position: relative;
		--dot-top: 2px;
		--dot-right: 2px;

		&:has(.sideNavCollapseButton) {
			@media screen and (min-width: 1000px) {
				display: flex;
			}
		}

		&:has(.sideNavModalTrigger) {
			@media screen and (min-width: 600px) and (max-width: 999px) {
				display: flex;
			}
		}
	}

	.collapseButton {
		display: none;
		align-items: center;
		justify-content: center;
		appearance: none;
		border: none;
		background-color: transparent;
		border-radius: var(--radius-field);
		cursor: pointer;
		padding: 0;
		height: var(--field-size-sm);
		aspect-ratio: 1 / 1;

		&:focus-visible {
			outline: var(--focus-ring);
		}

		& :global(svg) {
			color: var(--color-text);
			min-width: 20px;
			max-width: 20px;
		}

		&.sideNavCollapseButton {
			@media screen and (min-width: 1000px) {
				display: flex;
			}
		}

		&.sideNavModalTrigger {
			@media screen and (min-width: 600px) and (max-width: 999px) {
				display: flex;
			}
		}
	}

	.sideNavModalOverlay {
		position: fixed;
		inset: 0;
		top: var(--layout-nav-height);
		background-color: rgba(0, 0, 0, 0.4);
		backdrop-filter: blur(4px);
		z-index: 20;
	}

	.sideNavModal {
		height: 100%;
		width: var(--layout-sidenav-width);
		border-right: 1.5px solid var(--color-border);
	}

	.sideNavModal :global(.sideNavInModal) {
		display: flex;
		position: static;
		height: 100%;
		min-width: unset;
		max-width: unset;
		border-right: none;
	}

	.mobileLogo {
		display: flex;

		@media screen and (min-width: 600px) {
			display: none;
		}
	}
</style>
