// src/lib/components/form/DatetimeFormField.svelte
<script lang="ts">
	import type { FormFieldProps } from '$lib/form/types';
	import { format, parseISO } from 'date-fns';
	import Input from '../Input.svelte';
	import BottomText from './BottomText.svelte';
	import Label from './Label.svelte';
	import { ariaAttributes } from './utils';

	type Props = FormFieldProps<'datetime'> & {
		value?: Date;
	};

	let { label, name, bottomText, error, required, onblur, value = $bindable() }: Props = $props();

	const id = $props.id();
</script>

<div class="stack xs">
	<Label for={id} {required}>
		{label}
	</Label>
	<Input
		{id}
		{onblur}
		type="datetime-local"
		bind:value={
			() => (value ? format(value, "yyyy-MM-dd'T'HH:mm") : undefined),
			(valueStr) => {
				if (!valueStr) {
					value = undefined;
					return;
				}

				value = parseISO(valueStr);
			}
		}
		{...ariaAttributes({
			id,
			bottomText,
			error
		})}
	/>
	<input {name} type="hidden" value={value ? value.toISOString() : ''} />
	<BottomText info={bottomText} {error} fieldId={id} />
</div>

// app/form/fields/DatetimeFormField.tsx
import { format, parseISO } from "date-fns";
import * as React from "react";
import type { FormFieldProps } from "../types";
import { ariaAttributes } from "../utils";
import { FormFieldWrapper } from "./FormFieldWrapper";

type DatetimeFormFieldProps = FormFieldProps<"datetime"> & {
	value: Date | undefined;
	onChange: (value: Date | undefined) => void;
};

// xxx: this should probably use react-aria-components
export function DatetimeFormField({
	label,
	name,
	bottomText,
	error,
	required,
	onBlur,
	value,
	onChange,
}: DatetimeFormFieldProps) {
	const id = React.useId();

	const inputValue = value ? format(value, "yyyy-MM-dd'T'HH:mm") : "";

	const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
		const valueStr = e.target.value;
		if (!valueStr) {
			onChange(undefined);
			return;
		}
		onChange(parseISO(valueStr));
	};

	return (
		<FormFieldWrapper
			id={id}
			label={label}
			required={required}
			error={error}
			bottomText={bottomText}
		>
			<input
				id={id}
				type="datetime-local"
				value={inputValue}
				onChange={handleChange}
				onBlur={onBlur}
				className="plain"
				{...ariaAttributes({
					id,
					bottomText,
					error,
				})}
			/>
			<input
				name={name}
				type="hidden"
				value={value ? value.toISOString() : ""}
			/>
		</FormFieldWrapper>
	);
}
