// src/lib/components/form/InputFormField.svelte
<script lang="ts">
	import type { FormFieldProps } from '$lib/form/types';
	import Input from '../Input.svelte';
	import BottomText from './BottomText.svelte';
	import Label from './Label.svelte';
	import { ariaAttributes } from './utils';

	type Props = FormFieldProps<'text-field'> & {
		value: string;
		onblur?: () => void;
	};

	let {
		label,
		name,
		bottomText,
		leftAddon,
		maxLength,
		error,
		onblur,
		value = $bindable()
	}: Props = $props();
	const id = $props.id();
</script>

<div class="stack xs">
	<Label for={id}>
		{label}
	</Label>
	<Input
		{name}
		{id}
		{leftAddon}
		{onblur}
		maxlength={maxLength}
		bind:value
		{...ariaAttributes({
			id,
			bottomText,
			error
		})}
	/>
	<BottomText info={bottomText} {error} fieldId={id} />
</div>

// app/form/fields/InputFormField.tsx
import * as React from "react";
import type { FormFieldProps } from "../types";
import { ariaAttributes } from "../utils";
import { FormFieldWrapper } from "./FormFieldWrapper";

type InputFormFieldProps = FormFieldProps<"text-field"> & {
	value: string;
	onChange: (value: string) => void;
};

export function InputFormField({
	name,
	label,
	bottomText,
	leftAddon,
	maxLength,
	error,
	onBlur,
	required,
	value,
	onChange,
}: InputFormFieldProps) {
	const id = React.useId();

	return (
		<FormFieldWrapper
			id={id}
			name={name}
			label={label}
			required={required}
			error={error}
			bottomText={bottomText}
		>
			<div className={leftAddon ? "input-with-addon" : undefined}>
				{leftAddon ? <span className="input-addon">{leftAddon}</span> : null}
				<input
					id={id}
					type="text"
					value={value}
					onChange={(e) => onChange(e.target.value)}
					onBlur={() => onBlur?.()}
					maxLength={maxLength}
					{...ariaAttributes({
						id,
						bottomText,
						error,
						required,
					})}
				/>
			</div>
		</FormFieldWrapper>
	);
}
