// src/lib/components/form/MapPoolFormField.svelte
<script lang="ts">
	import type { ModeShort, StageId } from '$lib/constants/in-game/types';
	import ModeMapPoolPicker from '../ModeMapPoolPicker.svelte';
	import BottomText from './BottomText.svelte';
	import Label from './Label.svelte';
	import type { FormFieldProps } from '$lib/form/types';
	import { rankedModesShort } from '$lib/constants/in-game/modes';

	export type MapPool = Record<ModeShort, StageId[]>;

	type Props = FormFieldProps<'custom'> & {
		modes?: ModeShort[];
		maxCount: number;
		name: string;
		value: MapPool;
	};

	let {
		modes = rankedModesShort,
		maxCount,
		name,
		label,
		error,
		bottomText,
		value = $bindable()
	}: Props = $props();
	const id = $props.id();
</script>

<div class="stack xs">
	<Label for={id}>
		{label}
	</Label>
	<div class="stack lg">
		{#each modes as mode (mode)}
			<ModeMapPoolPicker {mode} {maxCount} bind:pool={value[mode]} />
		{/each}
	</div>
	<input type="hidden" {name} value={JSON.stringify(value)} />
	<BottomText info={bottomText} {error} fieldId={id} />
</div>

// app/form/fields/MapPoolFormField.tsx
import * as React from "react";
import { FormMessage } from "~/components/FormMessage";
import { Label } from "~/components/Label";
import { MapPoolSelector } from "~/components/MapPoolSelector";
import { MapPool } from "~/features/map-list-generator/core/map-pool";
import type {
	MapPoolObject,
	ReadonlyMapPoolObject,
} from "~/features/map-list-generator/core/map-pool-serializer/types";
import type { ModeShort } from "~/modules/in-game-lists/types";
import type { FormFieldProps } from "../types";

type MapPoolFormFieldProps = Omit<FormFieldProps<"map-pool">, "modes"> & {
	modes?: ModeShort[];
	value: MapPoolObject;
	onChange: (value: ReadonlyMapPoolObject) => void;
};

export function MapPoolFormField({
	label,
	name,
	bottomText,
	error,
	modes,
	value,
	onChange,
}: MapPoolFormFieldProps) {
	const id = React.useId();

	const mapPool = new MapPool(value as ReadonlyMapPoolObject);

	const handleMapPoolChange = (newMapPool: MapPool) => {
		onChange(newMapPool.parsed);
	};

	return (
		<div className="stack xs">
			{label ? <Label htmlFor={id}>{label}</Label> : null}
			<MapPoolSelector
				mapPool={mapPool}
				handleMapPoolChange={handleMapPoolChange}
				modesToInclude={modes}
			/>
			<input type="hidden" name={name} value={JSON.stringify(value)} />
			{error ? <FormMessage type="error">{error}</FormMessage> : null}
			{bottomText && !error ? (
				<FormMessage type="info">{bottomText}</FormMessage>
			) : null}
		</div>
	);
}
