// apps/web/src/lib/form/fields/SelectFormField.svelte
<script lang="ts">
import type { FormFieldItems } from "../form-types.ts";
import { ariaAttributes, translateItemLabel } from "../form-utils.ts";
import FormFieldWrapper from "./FormFieldWrapper.svelte";

interface Props {
	name?: string;
	label?: string;
	bottomText?: string;
	items: FormFieldItems<string>;
	error?: string;
	onBlur?: (latestValue?: unknown) => void;
	value: string | null;
	onChange: (value: string | null) => void;
	clearable?: boolean;
	disabled?: boolean;
}

let {
	name,
	label,
	bottomText,
	items,
	error,
	onBlur,
	value,
	onChange,
	clearable,
	disabled,
}: Props = $props();

const id = $props.id();

const itemsWithResolvedLabels = $derived(
	items.map((item) => ({
		value: item.value,
		resolvedLabel: translateItemLabel(item.label),
	})),
);

function handleChange(event: Event & { currentTarget: HTMLSelectElement }) {
	const newValue =
		event.currentTarget.value === "" ? null : event.currentTarget.value;
	onChange(newValue);
}
</script>

<FormFieldWrapper {id} {name} {label} {error} {bottomText}>
	<select
		{id}
		{name}
		value={value ?? ""}
		onchange={handleChange}
		onblur={() => onBlur?.()}
		{disabled}
		{...ariaAttributes({ name, error, bottomText })}
	>
		{#if clearable}<option value="">—</option>{/if}
		{#each itemsWithResolvedLabels as item (item.value)}
			<option value={item.value}>{item.resolvedLabel}</option>
		{/each}
	</select>
</FormFieldWrapper>

// app/form/fields/SelectFormField.tsx
import * as React from "react";
import { useTranslation } from "react-i18next";
import type { FormFieldItems, FormFieldProps } from "../types";
import { ariaAttributes } from "../utils";
import { FormFieldWrapper } from "./FormFieldWrapper";

type SelectFormFieldProps<V extends string> = Omit<
	FormFieldProps<"select">,
	"items" | "clearable" | "onBlur" | "name"
> & {
	name?: string;
	items: FormFieldItems<V>;
	value: V | null;
	onChange: (value: V | null) => void;
	onSelect?: (value: V) => void;
	onBlur?: () => void;
};

export function SelectFormField<V extends string>({
	name,
	label,
	bottomText,
	items,
	error,
	onBlur,
	value,
	onChange,
	onSelect,
}: SelectFormFieldProps<V>) {
	const { t, i18n } = useTranslation();
	const id = React.useId();

	const itemsWithResolvedLabels = items.map((item) => {
		const itemLabel = item.label;
		const resolvedLabel =
			typeof itemLabel === "function"
				? itemLabel(i18n.language)
				: typeof itemLabel === "string" && itemLabel.includes(":")
					? t(itemLabel as never)
					: String(itemLabel);

		return {
			value: item.value,
			resolvedLabel,
		};
	});

	const handleChange = (e: React.ChangeEvent<HTMLSelectElement>) => {
		const newValue = e.target.value === "" ? null : (e.target.value as V);
		onChange(newValue);
		if (newValue && onSelect) {
			onSelect(newValue);
		}
	};

	return (
		<FormFieldWrapper
			id={id}
			name={name}
			label={label}
			error={error}
			bottomText={bottomText}
		>
			<select
				id={id}
				name={name}
				value={value ?? ""}
				onChange={handleChange}
				onBlur={() => onBlur?.()}
				{...ariaAttributes({ id, error, bottomText })}
			>
				{itemsWithResolvedLabels.map((item) => (
					<option key={item.value} value={item.value}>
						{item.resolvedLabel}
					</option>
				))}
			</select>
		</FormFieldWrapper>
	);
}
