// apps/web/src/lib/form/fields/SwitchFormField.svelte
<script lang="ts">
import { Switch } from "@sendou/components";
import { translateFormText } from "../form-utils.ts";
import FormFieldMessages from "./FormFieldMessages.svelte";

interface Props {
	name: string;
	label?: string;
	bottomText?: string;
	error?: string;
	checked: boolean;
	onChange: (checked: boolean) => void;
	isDisabled?: boolean;
}

let { name, label, bottomText, error, checked, onChange, isDisabled }: Props =
	$props();

const id = $props.id();

const translatedLabel = $derived(translateFormText(label));
</script>

<div class="stack xs">
	<div class="stack horizontal sm items-center">
		<Switch {id} isSelected={checked} {onChange} {isDisabled}>
			{translatedLabel}
		</Switch>
	</div>
	<FormFieldMessages {name} {error} {bottomText} />
</div>

// app/form/fields/SwitchFormField.tsx
import * as React from "react";
import { useTranslation } from "react-i18next";
import { SendouSwitch } from "~/components/elements/Switch";
import type { FormFieldProps } from "../types";
import { FormFieldMessages } from "./FormFieldWrapper";

type SwitchFormFieldProps = Omit<
	FormFieldProps<"switch">,
	"onBlur" | "name"
> & {
	checked: boolean;
	onChange: (checked: boolean) => void;
	isDisabled?: boolean;
};

export function SwitchFormField({
	label,
	bottomText,
	error,
	checked,
	onChange,
	isDisabled,
}: SwitchFormFieldProps) {
	const { t } = useTranslation();
	const id = React.useId();

	const translatedLabel = label?.includes(":") ? t(label as never) : label;
	const translatedError = error?.includes(":") ? t(error as never) : error;
	const translatedBottomText = bottomText?.includes(":")
		? t(bottomText as never)
		: bottomText;

	return (
		<div className="stack xs">
			<div className="stack horizontal sm items-center">
				<SendouSwitch
					id={id}
					isSelected={checked}
					onChange={onChange}
					isDisabled={isDisabled}
				>
					{translatedLabel}
				</SendouSwitch>
			</div>
			<FormFieldMessages
				error={translatedError}
				bottomText={translatedBottomText}
			/>
		</div>
	);
}
