// apps/web/src/lib/form/fields/TimeRangeFormField.svelte
<script lang="ts">
import { translateFormText } from "../form-utils.ts";
import FormFieldMessages from "./FormFieldMessages.svelte";
import FormFieldWrapper from "./FormFieldWrapper.svelte";

type TimeRange = { start: string; end: string } | null;

interface Props {
	name?: string;
	label?: string;
	bottomText?: string;
	startLabel?: string;
	endLabel?: string;
	error?: string;
	onBlur?: (latestValue?: unknown) => void;
	value: TimeRange;
	onChange: (value: TimeRange) => void;
	disabled?: boolean;
}

let {
	name,
	label,
	bottomText,
	startLabel,
	endLabel,
	error,
	onBlur,
	value,
	onChange,
	disabled,
}: Props = $props();

const startId = $props.id();
const endId = `${startId}-end`;

const translatedLabel = $derived(translateFormText(label));
const translatedStartLabel = $derived(translateFormText(startLabel));
const translatedEndLabel = $derived(translateFormText(endLabel));

function handleStartChange(event: Event & { currentTarget: HTMLInputElement }) {
	const newStart = event.currentTarget.value;
	if (!newStart && !value?.end) {
		onChange(null);
	} else {
		onChange({ start: newStart, end: value?.end ?? "" });
	}
}

function handleEndChange(event: Event & { currentTarget: HTMLInputElement }) {
	const newEnd = event.currentTarget.value;
	if (!newEnd && !value?.start) {
		onChange(null);
	} else {
		onChange({ start: value?.start ?? "", end: newEnd });
	}
}
</script>

<div class="stack xs">
	{#if translatedLabel}
		<span class="text-sm font-semi-bold">{translatedLabel}</span>
	{/if}
	<div class="stack horizontal sm">
		<FormFieldWrapper id={startId} label={translatedStartLabel}>
			<input
				id={startId}
				type="time"
				value={value?.start ?? ""}
				oninput={handleStartChange}
				onblur={() => onBlur?.()}
				{disabled}
				class="size-extra-small"
			/>
		</FormFieldWrapper>
		<FormFieldWrapper id={endId} label={translatedEndLabel}>
			<input
				id={endId}
				type="time"
				value={value?.end ?? ""}
				oninput={handleEndChange}
				onblur={() => onBlur?.()}
				{disabled}
				class="size-extra-small"
			/>
		</FormFieldWrapper>
	</div>
	<FormFieldMessages {name} {error} {bottomText} />
</div>

// app/form/fields/TimeRangeFormField.tsx
import * as React from "react";
import type { FormFieldProps } from "../types";
import {
	FormFieldMessages,
	FormFieldWrapper,
	useTranslatedTexts,
} from "./FormFieldWrapper";

type TimeRange = { start: string; end: string } | null;

type TimeRangeFormFieldProps = Omit<FormFieldProps<"time-range">, "onBlur"> & {
	value: TimeRange;
	onChange: (value: TimeRange) => void;
	onBlur?: () => void;
};

// xxx: instead of labels just have in line "from" and "to" so "from + input + to + input"
export function TimeRangeFormField({
	name,
	label,
	bottomText,
	startLabel,
	endLabel,
	error,
	onBlur,
	value,
	onChange,
}: TimeRangeFormFieldProps) {
	const startId = React.useId();
	const endId = React.useId();

	const { translatedLabel } = useTranslatedTexts({ label });
	const { translatedLabel: translatedStartLabel } = useTranslatedTexts({
		label: startLabel,
	});
	const { translatedLabel: translatedEndLabel } = useTranslatedTexts({
		label: endLabel,
	});

	const handleStartChange = (e: React.ChangeEvent<HTMLInputElement>) => {
		const newStart = e.target.value;
		if (!newStart && !value?.end) {
			onChange(null);
		} else {
			onChange({ start: newStart, end: value?.end ?? "" });
		}
	};

	const handleEndChange = (e: React.ChangeEvent<HTMLInputElement>) => {
		const newEnd = e.target.value;
		if (!newEnd && !value?.start) {
			onChange(null);
		} else {
			onChange({ start: value?.start ?? "", end: newEnd });
		}
	};

	return (
		<div className="stack xs">
			{translatedLabel ? (
				<span className="text-sm font-semi-bold">{translatedLabel}</span>
			) : null}
			<div className="stack horizontal sm">
				<FormFieldWrapper id={startId} label={translatedStartLabel}>
					<input
						id={startId}
						type="time"
						value={value?.start ?? ""}
						onChange={handleStartChange}
						onBlur={() => onBlur?.()}
						className="size-extra-small"
					/>
				</FormFieldWrapper>
				<FormFieldWrapper id={endId} label={translatedEndLabel}>
					<input
						id={endId}
						type="time"
						value={value?.end ?? ""}
						onChange={handleEndChange}
						onBlur={() => onBlur?.()}
						className="size-extra-small"
					/>
				</FormFieldWrapper>
			</div>
			<FormFieldMessages name={name} error={error} bottomText={bottomText} />
		</div>
	);
}
