// app/features/badges/components/BadgesSelector.tsx
import { useTranslation } from "react-i18next";
import {
	BadgeDisplay,
	type BadgeDisplayProps,
} from "~/features/badges/components/BadgeDisplay";

export function BadgesSelector({
	options,
	selectedBadges,
	onChange,
	onBlur,
	children,
	maxCount,
	showSelect = true,
}: {
	options: BadgeDisplayProps["badges"];
	selectedBadges: number[];
	onChange: (newBadges: number[]) => void;
	onBlur?: () => void;
	children?: React.ReactNode;
	maxCount?: number;
	showSelect?: boolean;
}) {
	const { t } = useTranslation(["common"]);

	return (
		<div className="stack md">
			{selectedBadges.length > 0 ? (
				<BadgeDisplay
					badges={options
						.filter((badge) => selectedBadges.includes(badge.id))
						.sort((a, b) => {
							const aIdx = selectedBadges.indexOf(a.id);
							const bIdx = selectedBadges.indexOf(b.id);

							return aIdx - bIdx;
						})}
					onChange={onChange}
					key={selectedBadges.join(",")}
				>
					{children}
				</BadgeDisplay>
			) : (
				<div className="text-lighter text-md font-bold">
					{t("common:badges.selector.none")}
				</div>
			)}
			{showSelect ? (
				<select
					onBlur={() => onBlur?.()}
					onChange={(e) =>
						onChange([...selectedBadges, Number(e.target.value)])
					}
					disabled={Boolean(maxCount && selectedBadges.length >= maxCount)}
					data-testid="badges-selector"
				>
					<option>{t("common:badges.selector.select")}</option>
					{options
						.filter((badge) => !selectedBadges.includes(badge.id))
						.map((badge) => (
							<option key={badge.id} value={badge.id}>
								{badge.displayName}
							</option>
						))}
				</select>
			) : null}
		</div>
	);
}

// src/lib/components/badge/BadgesSelector.svelte
<script lang="ts">
	import { m } from '$lib/paraglide/messages';
	import type { BadgeDisplayProps } from './BadgeDisplay.svelte';
	import BadgeDisplay from './BadgeDisplay.svelte';

	interface Props {
		options: BadgeDisplayProps['badges'];
		selectedBadges: number[];
		onblur?: () => void;
		children?: import('svelte').Snippet;
		maxCount?: number;
		showSelect?: boolean;
	}

	let {
		options,
		selectedBadges = $bindable(),
		onblur,
		children,
		maxCount,
		showSelect = true
	}: Props = $props();

	const selectedBadgeData = $derived(
		options
			.filter((badge) => selectedBadges.includes(badge.id))
			.sort((a, b) => {
				const aIdx = selectedBadges.indexOf(a.id);
				const bIdx = selectedBadges.indexOf(b.id);
				return aIdx - bIdx;
			})
	);

	const availableOptions = $derived(options.filter((badge) => !selectedBadges.includes(badge.id)));

	const isSelectDisabled = $derived(Boolean(maxCount && selectedBadges.length >= maxCount));

	function handleSelectChange(event: Event) {
		const target = event.target as HTMLSelectElement;
		const newBadgeId = Number(target.value);
		if (newBadgeId) {
			selectedBadges.push(newBadgeId);
			target.value = '';
		}
	}
</script>

<div class="stack md">
	{#if selectedBadges.length > 0}
		<BadgeDisplay badges={selectedBadgeData}>
			{@render children?.()}
		</BadgeDisplay>
	{:else}
		<div class="text-lighter text-md font-bold">
			{m.common_badges_selector_none()}
		</div>
	{/if}

	{#if showSelect}
		<select
			{onblur}
			onchange={handleSelectChange}
			disabled={isSelectDisabled}
			data-testid="badges-selector"
		>
			<option value="">{m.common_badges_selector_select()}</option>
			{#each availableOptions as badge (badge.id)}
				<option value={badge.id}>
					{badge.displayName}
				</option>
			{/each}
		</select>
	{/if}
</div>
