// apps/web/src/lib/components/TournamentSearch.svelte
<script lang="ts">
import { Select, SelectItem } from "@sendou/components";
import { sub } from "date-fns";
import {
	searchTournaments,
	type TournamentSearchItem,
} from "#lib/features/tournament/tournament-search.remote.ts";
import { m } from "#lib/paraglide/messages.js";
import { getLocale } from "#lib/paraglide/runtime.js";
import { databaseTimestampToDate } from "#lib/utils/dates.ts";
import { EntitySearchText } from "./entity-search.svelte.ts";
import FormMessage from "./FormMessage.svelte";
import Label from "./Label.svelte";

interface Props {
	label?: string;
	bottomText?: string;
	errorText?: string;
	errorId?: string;
	initialTournamentId?: number;
	/**
	 * Restrict results to tournaments that have already started (finished/past)
	 * instead of the default recent + upcoming window.
	 */
	pastOnly?: boolean;
	onChange?: (tournament: TournamentSearchItem | null) => void;
	isRequired?: boolean;
	isDisabled?: boolean;
}

let {
	label,
	bottomText,
	errorText,
	errorId,
	initialTournamentId,
	pastOnly,
	onChange,
	isRequired,
	isDisabled,
}: Props = $props();

const search = new EntitySearchText();

let selectedItem = $state<TournamentSearchItem | null>(null);
// svelte-ignore state_referenced_locally -- the preselected id seeds the initial state only
let selectedKey = $state<number | null>(initialTournamentId ?? null);

const pinnedItem = $derived(selectedItem);

function timeBounds() {
	return pastOnly
		? { maxStartTime: new Date() }
		: { minStartTime: sub(new Date(), { days: 7 }) };
}

const resultsQuery = $derived(
	search.query
		? searchTournaments({ q: search.query, limit: 6, ...timeBounds() })
		: null,
);

/** `null` = no up-to-date results for the typed query (show the placeholder) */
const results = $derived.by(() => {
	if (!resultsQuery) return null;
	const data = resultsQuery.current;
	if (!data || data.query !== search.query) return null;
	return data.tournaments.filter(
		(tournament) => tournament.id !== pinnedItem?.id,
	);
});

function handleSelectionChange(key: string | number | null) {
	if (key === null || typeof key === "string") return;

	selectedKey = key;
	const item =
		pinnedItem?.id === key
			? pinnedItem
			: (results?.find((tournament) => tournament.id === key) ?? null);
	if (item) {
		selectedItem = item;
		onChange?.(item);
	}
}

function formatStartsAt(startsAt: number) {
	return new Intl.DateTimeFormat(getLocale(), {
		day: "numeric",
		month: "numeric",
		year: "numeric",
	}).format(databaseTimestampToDate(startsAt));
}

const composedAriaLabel = $derived(
	["Tournament search", label, isRequired ? "*" : undefined]
		.filter(Boolean)
		.join(" "),
);
</script>

{#snippet tournamentContent(item: TournamentSearchItem)}
	<img src={item.logoUrl} alt="" class="logo" />
	<div class="itemTextsContainer">
		<span>{item.name}</span>
		<div class="itemAdditionalText">{formatStartsAt(item.startsAt)}</div>
	</div>
{/snippet}

<div class="root">
	{#if label}
		<Label spaced={false} required={isRequired}>{label}</Label>
	{/if}
	<Select
		aria-label={composedAriaLabel}
		{selectedKey}
		onSelectionChange={handleSelectionChange}
		{isDisabled}
		{isRequired}
		search={{
			placeholder: m.common_actions_search(),
			testId: "tournament-search-input",
		}}
		bind:searchValue={search.searchValue}
		popoverClass="searchSelectPopover"
	>
		{#snippet valueContent(key)}
			{#if pinnedItem && pinnedItem.id === key}
				<span class="selectValue">
					{@render tournamentContent(pinnedItem)}
				</span>
			{/if}
		{/snippet}
		{#if pinnedItem}
			<SelectItem
				id={pinnedItem.id}
				textValue={pinnedItem.name}
				testId="tournament-search-item"
			>
				<div class="item">{@render tournamentContent(pinnedItem)}</div>
			</SelectItem>
		{/if}
		{#if results === null}
			<SelectItem id="PLACEHOLDER" textValue="PLACEHOLDER" isDisabled>
				<div class="placeholder">
					{m.common_forms_tournamentSearch_placeholder()}
				</div>
			</SelectItem>
		{:else if results.length === 0}
			<SelectItem id="NO_RESULTS" textValue="NO_RESULTS" isDisabled>
				<div class="placeholder">
					{m.common_forms_tournamentSearch_noResults()}
				</div>
			</SelectItem>
		{:else}
			{#each results as item (item.id)}
				<SelectItem
					id={item.id}
					textValue={item.name}
					testId="tournament-search-item"
				>
					<div class="item">{@render tournamentContent(item)}</div>
				</SelectItem>
			{/each}
		{/if}
	</Select>
	{#if errorText}
		<FormMessage type="error" spaced={false} id={errorId}>
			{errorText}
		</FormMessage>
	{/if}
	{#if bottomText}
		<FormMessage type="info" spaced={false}>{bottomText}</FormMessage>
	{/if}
</div>

<style>
	.root {
		display: flex;
		flex-direction: column;
		gap: var(--s-1-5);
		width: 100%;
	}

	.root :global(.searchSelectPopover) {
		min-height: 250px;
	}

	.item,
	.selectValue {
		display: flex;
		align-items: center;
		gap: var(--s-2);
		min-width: 0;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
	}

	.itemTextsContainer {
		line-height: 1.1;
		font-size: var(--font-sm);

		& span {
			max-width: 175px;
			text-overflow: ellipsis;
			white-space: nowrap;
			overflow: hidden;
			display: block;
		}
	}

	.itemAdditionalText {
		font-size: var(--font-xs);
		color: var(--color-text-high);
	}

	.selectValue .itemAdditionalText {
		display: none;
	}

	.logo {
		width: 24px;
		height: 24px;
		border-radius: var(--radius-field);
		object-fit: cover;
	}

	.placeholder {
		font-size: var(--font-xs);
		font-weight: var(--weight-semi);
		color: var(--color-text-high);
		text-align: center;
		display: grid;
		place-items: center;
		height: 162px;
		margin-block: var(--s-4);
	}
</style>

// apps/web-react/app/components/elements/TournamentSearch.tsx
import clsx from "clsx";
import { sub } from "date-fns";
import type * as React from "react";
import { ListBoxItem, type SelectProps } from "react-aria-components";
import type { TournamentSearchLoaderData } from "~/features/tournament/routes/to.search";
import { tournamentSearchSearchParams } from "~/features/tournament/tournament-search-params";
import { LocaleTime } from "../LocaleTime";
import { SearchSelect } from "./SearchSelect";
import searchSelectStyles from "./SearchSelect.module.css";
import selectStyles from "./Select.module.css";
import { useEntitySearch } from "./useEntitySearch";

export type TournamentSearchItem = NonNullable<
	Extract<TournamentSearchLoaderData, { tournaments: unknown }>
>["tournaments"][number];

interface TournamentSearchProps<T extends object>
	extends Omit<SelectProps<T>, "children" | "onChange"> {
	name?: string;
	label?: string;
	bottomText?: string;
	errorText?: string;
	initialTournamentId?: number;
	/**
	 * Restrict results to tournaments that have already started (finished/past)
	 * instead of the default recent + upcoming window. Useful e.g. for importing
	 * data from a previous tournament.
	 */
	pastOnly?: boolean;
	onChange?: (tournament: TournamentSearchItem | null) => void;
	ref?: React.Ref<HTMLButtonElement>;
}

export function TournamentSearch<T extends object>({
	name,
	label,
	bottomText,
	errorText,
	initialTournamentId,
	pastOnly,
	onChange,
	ref,
	...rest
}: TournamentSearchProps<T>) {
	const search = useEntitySearch<TournamentSearchItem>({
		buildUrl: (query) =>
			pastOnly
				? tournamentSearchSearchParams.href("/to/search", {
						q: query,
						limit: 6,
						maxStartTime: new Date(),
					})
				: tournamentSearchSearchParams.href("/to/search", {
						q: query,
						limit: 6,
						minStartTime: sub(new Date(), { days: 7 }),
					}),
		parseResults: parseTournamentResults,
		initialSelectedId: initialTournamentId,
		onChange,
	});

	return (
		<SearchSelect
			{...rest}
			name={name}
			label={label}
			bottomText={bottomText}
			errorText={errorText}
			ariaLabel="Tournament search"
			inputTestId="tournament-search-input"
			i18nKey="tournamentSearch"
			search={search}
			buttonRef={ref}
			renderItem={(item) => <TournamentItem item={item} />}
		/>
	);
}

function parseTournamentResults(
	data: unknown,
	query: string,
): TournamentSearchItem[] | null {
	const searchData = data as TournamentSearchLoaderData;
	if (!searchData || Array.isArray(searchData) || searchData.query !== query) {
		return null;
	}
	return searchData.tournaments;
}

function TournamentItem({ item }: { item: TournamentSearchItem }) {
	return (
		<ListBoxItem
			id={item.id}
			textValue={item.name}
			className={({ isFocused, isSelected }) =>
				clsx(searchSelectStyles.item, {
					[selectStyles.itemFocused]: isFocused,
					[selectStyles.itemSelected]: isSelected,
				})
			}
			data-testid="tournament-search-item"
		>
			<img src={item.logoUrl} alt="" className={searchSelectStyles.logo} />
			<div className={searchSelectStyles.itemTextsContainer}>
				<span>{item.name}</span>
				<LocaleTime
					date={item.startsAt}
					options={{
						day: "numeric",
						month: "numeric",
						year: "numeric",
					}}
					inline
					className={searchSelectStyles.itemAdditionalText}
				/>
			</div>
		</ListBoxItem>
	);
}
