// app/features/scrims/components/ScrimMatchActionTab.tsx
import { MapPin, Repeat, Undo2 } from "lucide-react";
import { useTranslation } from "react-i18next";
import { useFetcher, useLoaderData } from "react-router";
import { SendouButton } from "~/components/elements/Button";
import { SendouTabPanel } from "~/components/elements/Tabs";
import { MatchActionTab } from "~/components/match-page/MatchActionTab";
import { TAB_KEYS } from "~/components/match-page/MatchTabs";
import { useUser } from "~/features/auth/core/user";
import * as Scrim from "../core/Scrim";
import * as ScrimMapByMap from "../core/ScrimMapByMap";
import type { loader } from "../loaders/scrims.$id.server";
import type { ScrimSide } from "../scrims-types";
import { PickMapDialog } from "./PickMapDialog";
import { ScrimMapListManager } from "./ScrimMapListManager";
import styles from "./ScrimMatchActionTab.module.css";

const ALPHA_TEAM_ID = 1;
const BRAVO_TEAM_ID = 2;

export function ScrimMatchActionTab() {
	const data = useLoaderData<typeof loader>();
	const user = useUser();

	const viewerSide = user ? Scrim.sideOfUser(data.post, user.id) : null;

	if (data.mapByMap.locked) return null;
	if (!viewerSide) return <NotParticipantSection />;

	if (!data.mapByMap.currentMap) {
		return (
			<SendouTabPanel id={TAB_KEYS.ACTION}>
				<ScrimMapListManager viewerSide={viewerSide} standalone />
			</SendouTabPanel>
		);
	}

	return <ReportMapSection viewerSide={viewerSide} />;
}

function NotParticipantSection() {
	const { t } = useTranslation(["scrims"]);
	return (
		<SendouTabPanel id={TAB_KEYS.ACTION}>
			<div className={styles.locked}>
				{t("scrims:mapByMap.nonParticipantNotice")}
			</div>
		</SendouTabPanel>
	);
}

function ReportMapSection({ viewerSide }: { viewerSide: ScrimSide }) {
	const { t } = useTranslation(["q"]);
	const data = useLoaderData<typeof loader>();
	const fetcher = useFetcher();
	const map = data.mapByMap!.currentMap!;
	const acceptedRequest = data.post.requests.find((r) => r.isAccepted)!;

	const alphaName = data.post.team
		? Scrim.sideDisplayName(data.post)
		: t("q:match.groupAlpha");
	const bravoName = acceptedRequest.team
		? Scrim.sideDisplayName(acceptedRequest)
		: t("q:match.groupBravo");

	const ownTeamId = viewerSide === "ALPHA" ? ALPHA_TEAM_ID : BRAVO_TEAM_ID;

	return (
		<MatchActionTab
			key={map.id}
			teams={[
				{ id: ALPHA_TEAM_ID, name: alphaName },
				{ id: BRAVO_TEAM_ID, name: bravoName },
			]}
			ownTeamId={ownTeamId}
			stageId={map.stageId}
			mode={map.mode}
			withKo={false}
			isSubmitting={fetcher.state !== "idle"}
			onSubmit={({ winnerId }) => {
				fetcher.submit(
					{
						_action: "REPORT_MAP",
						mapId: String(map.id),
						winnerSide: winnerId === ALPHA_TEAM_ID ? "ALPHA" : "BRAVO",
					},
					{ method: "post" },
				);
			}}
			actionButtons={<MapActionButtons />}
			secondaryAction={<ScrimMapListManager viewerSide={viewerSide} />}
		/>
	);
}

function MapActionButtons() {
	const { t } = useTranslation(["scrims"]);
	const data = useLoaderData<typeof loader>();
	const undoFetcher = useFetcher();
	const replayFetcher = useFetcher();

	const maps = data.mapByMap?.maps ?? [];
	const currentMap = data.mapByMap?.currentMap;
	const latest = Scrim.lastReportedMap(maps);
	const undoAllowed = ScrimMapByMap.canUndo(latest, maps);
	const replayAllowed = Boolean(latest && currentMap);

	return (
		<>
			<SendouButton
				testId="undo-map-button"
				variant="minimal-destructive"
				size="miniscule"
				icon={<Undo2 size={16} />}
				isPending={undoFetcher.state !== "idle"}
				isDisabled={!undoAllowed}
				onPress={() => {
					undoFetcher.submit({ _action: "UNDO_MAP" }, { method: "post" });
				}}
			>
				{t("scrims:mapByMap.undo")}
			</SendouButton>
			<SendouButton
				testId="replay-map-button"
				variant="minimal"
				size="miniscule"
				icon={<Repeat size={16} />}
				isPending={replayFetcher.state !== "idle"}
				isDisabled={!replayAllowed}
				onPress={() => {
					replayFetcher.submit({ _action: "REPLAY_MAP" }, { method: "post" });
				}}
			>
				{t("scrims:mapByMap.replay")}
			</SendouButton>
			<PickMapDialog
				key={
					currentMap
						? `${currentMap.id}-${currentMap.mode}-${currentMap.stageId}`
						: "no-map"
				}
				heading={t("scrims:mapByMap.pickDialog.heading")}
				trigger={
					<SendouButton
						testId="pick-map-button"
						variant="minimal"
						size="miniscule"
						icon={<MapPin size={16} />}
					>
						{t("scrims:mapByMap.pick")}
					</SendouButton>
				}
			/>
		</>
	);
}

// apps/web/src/lib/features/scrims/components/ScrimMatchActionTab.svelte
<script lang="ts">
import { MapPin, Repeat, Undo2 } from "@lucide/svelte";
import { Button, TabPanel } from "@sendou/components";
import MatchActionTab from "#lib/components/match-page/MatchActionTab.svelte";
import { TAB_KEYS } from "#lib/components/match-page/match-page-constants.ts";
import { loggedInUser } from "#lib/features/auth/user-state.ts";
import { m } from "#lib/paraglide/messages.js";
import * as Scrim from "../Scrim.ts";
import * as ScrimMapByMap from "../ScrimMapByMap.ts";
import { replayMap, reportMap, type ScrimPageData, undoMap } from "../scrims.remote.ts";
import PickMapDialog from "./PickMapDialog.svelte";
import ScrimMapListManager from "./ScrimMapListManager.svelte";

const ALPHA_TEAM_ID = 1;
const BRAVO_TEAM_ID = 2;

interface Props {
	data: ScrimPageData;
}

let { data }: Props = $props();

const user = $derived(loggedInUser());

const viewerSide = $derived(
	user ? Scrim.sideOfUser(data.post, user.id) : null,
);

const currentMap = $derived(data.mapByMap.currentMap);
const acceptedRequest = $derived(
	data.post.requests.find((r) => r.isAccepted),
);

const alphaName = $derived(
	data.post.team ? Scrim.sideDisplayName(data.post) : m.q_match_groupAlpha(),
);
const bravoName = $derived(
	acceptedRequest?.team
		? Scrim.sideDisplayName(acceptedRequest)
		: m.q_match_groupBravo(),
);

let reportPending = $state(false);
let undoPending = $state(false);
let replayPending = $state(false);

const maps = $derived(data.mapByMap.maps);
const latest = $derived(Scrim.lastReportedMap(maps));
const undoAllowed = $derived(ScrimMapByMap.canUndo(latest, maps));
const replayAllowed = $derived(Boolean(latest && currentMap));

async function handleReport(submitted: { winnerId: number }) {
	if (!currentMap) return;

	reportPending = true;
	try {
		await reportMap({
			scrimPostId: data.post.id,
			mapId: currentMap.id,
			winnerSide: submitted.winnerId === ALPHA_TEAM_ID ? "ALPHA" : "BRAVO",
		});
	} finally {
		reportPending = false;
	}
}

async function handleUndo() {
	undoPending = true;
	try {
		await undoMap({ scrimPostId: data.post.id });
	} finally {
		undoPending = false;
	}
}

async function handleReplay() {
	replayPending = true;
	try {
		await replayMap({ scrimPostId: data.post.id });
	} finally {
		replayPending = false;
	}
}
</script>

{#if !data.mapByMap.locked}
	{#if !viewerSide}
		<TabPanel id={TAB_KEYS.ACTION}>
			<div class="locked">
				{m.scrims_mapByMap_nonParticipantNotice()}
			</div>
		</TabPanel>
	{:else if !currentMap}
		<TabPanel id={TAB_KEYS.ACTION}>
			<ScrimMapListManager {data} {viewerSide} standalone />
		</TabPanel>
	{:else}
		{#key currentMap.id}
			<MatchActionTab
				teams={[
					{ id: ALPHA_TEAM_ID, name: alphaName },
					{ id: BRAVO_TEAM_ID, name: bravoName },
				]}
				ownTeamId={viewerSide === "ALPHA" ? ALPHA_TEAM_ID : BRAVO_TEAM_ID}
				stageId={currentMap.stageId}
				mode={currentMap.mode}
				withKo={false}
				isSubmitting={reportPending}
				onSubmit={handleReport}
			>
				{#snippet actionButtons()}
					<Button
						testId="undo-map-button"
						variant="minimal-destructive"
						size="miniscule"
						disabled={!undoAllowed || undoPending}
						onclick={handleUndo}
					>
						{#snippet icon()}<Undo2 size={16} />{/snippet}
						{m.scrims_mapByMap_undo()}
					</Button>
					<Button
						testId="replay-map-button"
						variant="minimal"
						size="miniscule"
						disabled={!replayAllowed || replayPending}
						onclick={handleReplay}
					>
						{#snippet icon()}<Repeat size={16} />{/snippet}
						{m.scrims_mapByMap_replay()}
					</Button>
					{#key `${currentMap.id}-${currentMap.mode}-${currentMap.stageId}`}
						<PickMapDialog
							heading={m.scrims_mapByMap_pickDialog_heading()}
							scrimPostId={data.post.id}
						>
							{#snippet trigger(triggerProps)}
								<Button
									testId="pick-map-button"
									variant="minimal"
									size="miniscule"
									{...triggerProps}
								>
									{#snippet icon()}<MapPin size={16} />{/snippet}
									{m.scrims_mapByMap_pick()}
								</Button>
							{/snippet}
						</PickMapDialog>
					{/key}
				{/snippet}
				{#snippet secondaryAction()}
					<ScrimMapListManager {data} {viewerSide} />
				{/snippet}
			</MatchActionTab>
		{/key}
	{/if}
{/if}

<style>
	.locked {
		padding: var(--s-3);
		border-radius: var(--radius-box);
		background: var(--color-bg-high);
		color: var(--color-text-high);
		text-align: center;
	}
</style>
