// app/features/scrims/components/ScrimMapListManager.tsx
import { Map as MapIcon, Trash2 } from "lucide-react";
import { useState } from "react";
import { useTranslation } from "react-i18next";
import { useLoaderData } from "react-router";
import { SendouButton } from "~/components/elements/Button";
import { FormWithConfirm } from "~/components/FormWithConfirm";
import { SecondaryAction } from "~/components/match-page/SecondaryAction";
import type { loader } from "../loaders/scrims.$id.server";
import type { ScrimSide } from "../scrims-types";
import { ScrimMapListForm } from "./ScrimMapListForm";
import styles from "./ScrimMapListManager.module.css";

interface Props {
	viewerSide: ScrimSide;
	standalone?: boolean;
}

export function ScrimMapListManager({ viewerSide, standalone }: Props) {
	const { t } = useTranslation(["scrims"]);
	const data = useLoaderData<typeof loader>();
	const ownList = data.mapByMap.mapLists.find((l) => l.side === viewerSide);
	const [isOpen, setIsOpen] = useState(() => !ownList);

	return (
		<SecondaryAction
			isOpen={isOpen}
			onOpenChange={setIsOpen}
			collapsedLabel={t("scrims:mapByMap.manageMapLists")}
			collapsedIcon={<MapIcon size={16} />}
			standalone={standalone}
		>
			<div className={styles.root}>
				{ownList ? null : <ScrimMapListForm />}
				<MapListsSummary viewerSide={viewerSide} />
			</div>
		</SecondaryAction>
	);
}

function MapListsSummary({ viewerSide }: { viewerSide: ScrimSide }) {
	const { t } = useTranslation(["scrims", "q"]);
	const data = useLoaderData<typeof loader>();
	const lists = data.mapByMap.mapLists;

	const sides: ScrimSide[] = ["ALPHA", "BRAVO"];

	return (
		<div className={styles.mapListsSummary}>
			{sides.map((side) => {
				const list = lists.find((l) => l.side === side);
				const isOwn = side === viewerSide;
				return (
					<div
						key={side}
						className={styles.mapListRow}
						data-testid={`map-list-row-${side}`}
					>
						<div className={styles.mapListRowHeader}>
							{side === "ALPHA"
								? t("q:match.sides.alpha")
								: t("q:match.sides.bravo")}
						</div>
						<div className={styles.mapListBody}>
							{list ? (
								<>
									<MapListDisplay
										tournament={list.tournament}
										mapCount={list.mapList.length}
									/>
									{isOwn ? <RemoveOwnListButton /> : null}
								</>
							) : (
								<span className={styles.mapListRowMissing}>
									{t("scrims:mapByMap.noListYet")}
								</span>
							)}
						</div>
					</div>
				);
			})}
		</div>
	);
}

function RemoveOwnListButton() {
	const { t } = useTranslation(["scrims", "common"]);
	return (
		<FormWithConfirm
			fields={[["_action", "REMOVE_MAP_LIST"]]}
			dialogHeading={t("scrims:mapByMap.removeListConfirm")}
			submitButtonText={t("common:actions.remove")}
			submitButtonTestId="remove-list-button"
		>
			<SendouButton
				variant="minimal-destructive"
				size="miniscule"
				icon={<Trash2 size={16} />}
				aria-label={t("scrims:mapByMap.removeList")}
			/>
		</FormWithConfirm>
	);
}

function MapListDisplay({
	tournament,
	mapCount,
}: {
	tournament: { id: number; name: string } | undefined;
	mapCount: number;
}) {
	const { t } = useTranslation(["scrims"]);
	if (tournament) {
		return <span>{tournament.name}</span>;
	}
	return <span>{t("scrims:mapByMap.poolList", { count: mapCount })}</span>;
}

// apps/web/src/lib/features/scrims/components/ScrimMapListManager.svelte
<script lang="ts">
import { Map as MapIcon, Trash2 } from "@lucide/svelte";
import { Button } from "@sendou/components";
import ConfirmDialog from "#lib/components/ConfirmDialog.svelte";
import SecondaryAction from "#lib/components/match-page/SecondaryAction.svelte";
import { m } from "#lib/paraglide/messages.js";
import { removeMapList, type ScrimPageData } from "../scrims.remote.ts";
import type { ScrimSide } from "../scrims-types.ts";
import ScrimMapListForm from "./ScrimMapListForm.svelte";

interface Props {
	data: ScrimPageData;
	viewerSide: ScrimSide;
	standalone?: boolean;
}

let { data, viewerSide, standalone }: Props = $props();

const ownList = $derived(
	data.mapByMap.mapLists.find((list) => list.side === viewerSide),
);
// svelte-ignore state_referenced_locally -- whether the manager starts open is decided once at mount
let isOpen = $state(!ownList);

const sides: ScrimSide[] = ["ALPHA", "BRAVO"];

function sideLabel(side: ScrimSide) {
	return side === "ALPHA" ? m.q_match_sides_alpha() : m.q_match_sides_bravo();
}
</script>

<SecondaryAction
	{isOpen}
	onOpenChange={(open) => {
		isOpen = open;
	}}
	collapsedLabel={m.scrims_mapByMap_manageMapLists()}
	{standalone}
>
	{#snippet collapsedIcon()}<MapIcon size={16} />{/snippet}
	<div class="root">
		{#if !ownList}
			<ScrimMapListForm {data} />
		{/if}
		<div class="mapListsSummary">
			{#each sides as side (side)}
				{@const list = data.mapByMap.mapLists.find(
					(candidate) => candidate.side === side,
				)}
				{@const isOwn = side === viewerSide}
				<div class="mapListRow" data-testid={`map-list-row-${side}`}>
					<div class="mapListRowHeader">{sideLabel(side)}</div>
					<div class="mapListBody">
						{#if list}
							{#if list.tournament}
								<span>{list.tournament.name}</span>
							{:else}
								<span>
									{m.scrims_mapByMap_poolList({ count: list.mapList.length })}
								</span>
							{/if}
							{#if isOwn}
								<ConfirmDialog
									dialogHeading={m.scrims_mapByMap_removeListConfirm()}
									submitButtonText={m.common_actions_remove()}
									onConfirm={() =>
										removeMapList({ scrimPostId: data.post.id })}
								>
									{#snippet trigger(triggerProps)}
										<Button
											variant="minimal-destructive"
											size="miniscule"
											aria-label={m.scrims_mapByMap_removeList()}
											{...triggerProps}
										>
											{#snippet icon()}<Trash2 size={16} />{/snippet}
										</Button>
									{/snippet}
								</ConfirmDialog>
							{/if}
						{:else}
							<span class="mapListRowMissing">
								{m.scrims_mapByMap_noListYet()}
							</span>
						{/if}
					</div>
				</div>
			{/each}
		</div>
	</div>
</SecondaryAction>

<style>
	.root {
		display: flex;
		flex-direction: column;
		gap: var(--s-4);
		align-items: stretch;
		width: 100%;
		container-type: inline-size;
	}

	.mapListsSummary {
		display: flex;
		flex-direction: column;
		gap: var(--s-3);
	}

	.mapListRow {
		display: flex;
		flex-direction: column;
		gap: var(--s-1);
		padding: var(--s-2);
	}

	.mapListRowHeader {
		font-weight: var(--weight-bold);
	}

	.mapListBody {
		display: flex;
		align-items: center;
		gap: var(--s-2);
	}

	.mapListRowMissing {
		font-style: italic;
		color: var(--color-text-high);
	}
</style>
