// app/features/scrims/components/ScrimMatchStatsTab.tsx
import * as React from "react";
import { useTranslation } from "react-i18next";
import { useLoaderData } from "react-router";
import {
	SendouChipRadio,
	SendouChipRadioGroup,
} from "~/components/elements/ChipRadio";
import { SendouSwitch } from "~/components/elements/Switch";
import { SendouTabPanel } from "~/components/elements/Tabs";
import { ModeImage, StageImage } from "~/components/Image";
import { TAB_KEYS } from "~/components/match-page/MatchTabs";
import { MapPool } from "~/features/map-list-generator/core/map-pool";
import type { ModeShort, StageId } from "~/modules/in-game-lists/types";
import * as ScrimMapByMap from "../core/ScrimMapByMap";
import type { loader } from "../loaders/scrims.$id.server";
import styles from "./ScrimMatchStatsTab.module.css";

type View = "MODE" | "STAGE" | "BOTH";

const VIEW_OPTIONS: View[] = ["MODE", "STAGE", "BOTH"];

export function ScrimMatchStatsTab() {
	const { t } = useTranslation(["scrims", "game-misc"]);
	const data = useLoaderData<typeof loader>();

	const viewerSide = data.mapByMap?.viewerSide;
	const maps = data.mapByMap?.maps ?? [];
	const ownPool = data.mapByMap?.ownPool
		? new MapPool(data.mapByMap.ownPool)
		: null;

	const [view, setView] = React.useState<View>("BOTH");
	const [restrictToPool, setRestrictToPool] = React.useState(Boolean(ownPool));

	if (!viewerSide || maps.length === 0) {
		return (
			<SendouTabPanel id={TAB_KEYS.STATS}>
				<div className={styles.empty}>{t("scrims:mapByMap.stats.empty")}</div>
			</SendouTabPanel>
		);
	}

	const restrictPool = restrictToPool && ownPool ? ownPool : undefined;

	const stats = ScrimMapByMap.stats(maps, viewerSide, {
		restrictToPool: restrictPool,
	});

	return (
		<SendouTabPanel id={TAB_KEYS.STATS}>
			<div className={styles.root} data-testid="scrim-stats-root">
				<div className={styles.controls}>
					<SendouChipRadioGroup>
						{VIEW_OPTIONS.map((option) => (
							<SendouChipRadio
								key={option}
								name="scrim-stats-view"
								value={option}
								checked={view === option}
								onChange={(value) => setView(value as View)}
							>
								{t(`scrims:mapByMap.stats.view.${option}` as const)}
							</SendouChipRadio>
						))}
					</SendouChipRadioGroup>
					{ownPool ? (
						<label className={styles.toggleRow}>
							<SendouSwitch
								isSelected={restrictToPool}
								onChange={setRestrictToPool}
							/>
							{t("scrims:mapByMap.stats.restrictToPool")}
						</label>
					) : null}
				</div>

				{view === "MODE" ? (
					<StatsTable
						rows={stats.byMode.map((r) => ({
							key: r.key,
							label: (
								<span className={styles.stageModeLabel}>
									<ModeImage mode={r.key as ModeShort} size={20} />
									{t(`game-misc:MODE_LONG_${r.key as "SZ"}` as const, {
										defaultValue: r.key,
									})}
								</span>
							),
							wins: r.wins,
							losses: r.losses,
						}))}
					/>
				) : null}

				{view === "STAGE" ? (
					<StatsTable
						rows={stats.byStage.map((r) => {
							const stageId = Number(r.key);
							return {
								key: r.key,
								label: (
									<span className={styles.stageModeLabel}>
										<StageImage
											stageId={stageId as StageId}
											width={36}
											className={styles.stageImage}
										/>
										{t(`game-misc:STAGE_${stageId}` as const, {
											defaultValue: r.key,
										})}
									</span>
								),
								wins: r.wins,
								losses: r.losses,
							};
						})}
					/>
				) : null}

				{view === "BOTH" ? (
					<StatsTable
						rows={stats.byStageMode.map((r) => {
							const [stageId, mode] = r.key.split("-");
							const stageLabel = t(
								`game-misc:STAGE_${Number(stageId)}` as const,
								{ defaultValue: stageId },
							);
							return {
								key: r.key,
								label: (
									<span className={styles.stageModeLabel}>
										<ModeImage mode={mode as ModeShort} size={20} />
										<StageImage
											stageId={Number(stageId) as StageId}
											width={36}
											className={styles.stageImage}
										/>
										{stageLabel}
									</span>
								),
								wins: r.wins,
								losses: r.losses,
							};
						})}
					/>
				) : null}
			</div>
		</SendouTabPanel>
	);
}

function StatsTable({
	rows,
}: {
	rows: Array<{
		key: string;
		label: React.ReactNode;
		wins: number;
		losses: number;
	}>;
}) {
	const { t } = useTranslation(["scrims"]);

	if (rows.length === 0) {
		return (
			<div className={styles.empty}>{t("scrims:mapByMap.stats.empty")}</div>
		);
	}

	const sortedRows = [...rows]
		.map((row) => ({ ...row, winRate: row.wins / (row.wins + row.losses) }))
		.sort((a, b) => {
			if (b.winRate !== a.winRate) return b.winRate - a.winRate;
			return b.wins + b.losses - (a.wins + a.losses);
		});

	return (
		<table className={styles.table}>
			<thead>
				<tr>
					<th>{t("scrims:mapByMap.stats.col.label")}</th>
					<th className={styles.cellNum}>
						{t("scrims:mapByMap.stats.col.wins")}
					</th>
					<th className={styles.cellNum}>
						{t("scrims:mapByMap.stats.col.losses")}
					</th>
					<th className={styles.cellNum}>
						{t("scrims:mapByMap.stats.col.winPct")}
					</th>
				</tr>
			</thead>
			<tbody>
				{sortedRows.map((row) => (
					<tr key={row.key}>
						<td>{row.label}</td>
						<td className={styles.cellNum}>{row.wins}</td>
						<td className={styles.cellNum}>{row.losses}</td>
						<td className={styles.cellNum}>{Math.round(row.winRate * 100)}%</td>
					</tr>
				))}
			</tbody>
		</table>
	);
}

// apps/web/src/lib/features/scrims/components/ScrimMatchStatsTab.svelte
<script lang="ts">
import type { ModeShort, StageId } from "@sendou/in-game-lists/types";
import { ChipRadio, ChipRadioGroup, Switch, TabPanel } from "@sendou/components";
import { MapPool } from "@sendou/map-list-generator/map-pool";
import ModeImage from "#lib/components/ModeImage.svelte";
import StageImage from "#lib/components/StageImage.svelte";
import Table from "#lib/components/Table.svelte";
import { TAB_KEYS } from "#lib/components/match-page/match-page-constants.ts";
import { modeLongName, stageName } from "#lib/modules/i18n/messages.ts";
import { dynamicMessage } from "#lib/modules/i18n/messages.ts";
import { m } from "#lib/paraglide/messages.js";
import * as ScrimMapByMap from "../ScrimMapByMap.ts";
import type { ScrimPageData } from "../scrims.remote.ts";

type View = "MODE" | "STAGE" | "BOTH";

const VIEW_OPTIONS: View[] = ["MODE", "STAGE", "BOTH"];

interface Props {
	data: ScrimPageData;
}

let { data }: Props = $props();

const viewerSide = $derived(data.mapByMap.viewerSide);
const maps = $derived(data.mapByMap.maps);
const ownPool = $derived(
	data.mapByMap.ownPool ? new MapPool(data.mapByMap.ownPool) : null,
);

let view = $state<View>("BOTH");
// svelte-ignore state_referenced_locally -- whether a pool exists seeds the initial toggle only
let restrictToPool = $state(Boolean(ownPool));

const stats = $derived(
	viewerSide
		? ScrimMapByMap.stats(maps, viewerSide, {
				restrictToPool: restrictToPool && ownPool ? ownPool : undefined,
			})
		: null,
);

interface StatsRow {
	key: string;
	wins: number;
	losses: number;
	winRate: number;
}

function sortRows(rows: Array<{ key: string; wins: number; losses: number }>) {
	return rows
		.map((row) => ({
			...row,
			winRate: row.wins / (row.wins + row.losses),
		}))
		.sort((a, b) => {
			if (b.winRate !== a.winRate) return b.winRate - a.winRate;
			return b.wins + b.losses - (a.wins + a.losses);
		});
}

function viewLabel(option: View) {
	return dynamicMessage(`scrims_mapByMap_stats_view_${option}`);
}
</script>

<TabPanel id={TAB_KEYS.STATS}>
	{#if !viewerSide || maps.length === 0}
		<div class="empty">{m.scrims_mapByMap_stats_empty()}</div>
	{:else if stats}
		<div class="root" data-testid="scrim-stats-root">
			<div class="controls">
				<ChipRadioGroup>
					{#each VIEW_OPTIONS as option (option)}
						<ChipRadio
							name="scrim-stats-view"
							value={option}
							checked={view === option}
							onChange={(value) => {
								view = value as View;
							}}
						>
							{viewLabel(option)}
						</ChipRadio>
					{/each}
				</ChipRadioGroup>
				{#if ownPool}
					<label class="toggleRow">
						<Switch
							isSelected={restrictToPool}
							onChange={(isSelected) => {
								restrictToPool = isSelected;
							}}
						/>
						{m.scrims_mapByMap_stats_restrictToPool()}
					</label>
				{/if}
			</div>

			{#if view === "MODE"}
				{@render statsTable(sortRows(stats.byMode), modeLabel)}
			{:else if view === "STAGE"}
				{@render statsTable(sortRows(stats.byStage), stageLabel)}
			{:else}
				{@render statsTable(sortRows(stats.byStageMode), stageModeLabel)}
			{/if}
		</div>
	{/if}
</TabPanel>

{#snippet modeLabel(key: string)}
	<span class="stageModeLabel">
		<ModeImage mode={key as ModeShort} size={20} />
		{modeLongName(key)}
	</span>
{/snippet}

{#snippet stageLabel(key: string)}
	<span class="stageModeLabel">
		<StageImage
			stageId={Number(key) as StageId}
			width={36}
			class="stageImage"
		/>
		{stageName(Number(key))}
	</span>
{/snippet}

{#snippet stageModeLabel(key: string)}
	{@const [stageId, mode] = key.split("-")}
	<span class="stageModeLabel">
		<ModeImage mode={mode as ModeShort} size={20} />
		<StageImage
			stageId={Number(stageId) as StageId}
			width={36}
			class="stageImage"
		/>
		{stageName(Number(stageId))}
	</span>
{/snippet}

{#snippet statsTable(
	rows: StatsRow[],
	label: import("svelte").Snippet<[string]>,
)}
	{#if rows.length === 0}
		<div class="empty">{m.scrims_mapByMap_stats_empty()}</div>
	{:else}
		<Table>
			<thead>
				<tr>
					<th>{m.scrims_mapByMap_stats_col_label()}</th>
					<th class="cellNum">{m.scrims_mapByMap_stats_col_wins()}</th>
					<th class="cellNum">{m.scrims_mapByMap_stats_col_losses()}</th>
					<th class="cellNum">{m.scrims_mapByMap_stats_col_winPct()}</th>
				</tr>
			</thead>
			<tbody>
				{#each rows as row (row.key)}
					<tr>
						<td class="labelCell">{@render label(row.key)}</td>
						<td class="cellNum">{row.wins}</td>
						<td class="cellNum">{row.losses}</td>
						<td class="cellNum">{Math.round(row.winRate * 100)}%</td>
					</tr>
				{/each}
			</tbody>
		</Table>
	{/if}
{/snippet}

<style>
	.root {
		display: flex;
		flex-direction: column;
		gap: var(--s-4);
	}

	.controls {
		display: flex;
		flex-wrap: wrap;
		align-items: center;
		justify-content: space-between;
		gap: var(--s-3);
	}

	.toggleRow {
		display: flex;
		align-items: center;
		gap: var(--s-2);
		font-size: var(--font-sm);
	}

	.labelCell {
		white-space: nowrap;
	}

	.cellNum {
		width: 4rem;
		text-align: right;
		font-variant-numeric: tabular-nums;
	}

	.empty {
		color: var(--color-text-high);
		font-style: italic;
	}

	.stageModeLabel {
		display: inline-flex;
		align-items: center;
		gap: var(--s-2);

		& > :global(*) {
			flex-shrink: 0;
		}
	}

	.stageModeLabel :global(.stageImage) {
		border-radius: var(--radius-field);
	}
</style>
