// packages/components/src/Select.svelte
<script lang="ts">
import type { Snippet } from "svelte";
import { SvelteMap } from "svelte/reactivity";
import { closePopoverOnScrollClip } from "./popover-scroll-close.svelte.ts";
import { setSelectContext } from "./select-context.ts";

interface Props {
	label?: string;
	placeholder?: string;
	selectedKey?: string | number | null;
	defaultSelectedKey?: string | number;
	onSelectionChange?: (key: string | number | null) => void;
	onOpenChange?: (isOpen: boolean) => void;
	clearable?: boolean;
	isDisabled?: boolean;
	isRequired?: boolean;
	testId?: string;
	"aria-label"?: string;
	search?: { placeholder?: string; testId?: string };
	searchValue?: string;
	noResultsText?: string;
	clearText?: string;
	popoverClass?: string;
	/** Trigger content for the selected item; falls back to the item's registered text value. */
	valueContent?: Snippet<[string | number]>;
	children: Snippet;
}

let {
	label,
	placeholder,
	selectedKey,
	defaultSelectedKey,
	onSelectionChange,
	onOpenChange,
	clearable = false,
	isDisabled,
	isRequired,
	testId,
	"aria-label": ariaLabel,
	search,
	searchValue = $bindable(""),
	noResultsText = "No results",
	clearText = "Clear",
	popoverClass,
	valueContent,
	children,
}: Props = $props();

// svelte-ignore state_referenced_locally -- controlled vs. uncontrolled is decided once at mount
const isControlled = selectedKey !== undefined;
// svelte-ignore state_referenced_locally -- the default seeds the initial value only
let uncontrolledKey = $state<string | number | null>(
	defaultSelectedKey ?? null,
);
const currentKey = $derived(
	isControlled ? (selectedKey ?? null) : uncontrolledKey,
);

let open = $state(false);
let focusedKey = $state<string | number | null>(null);

interface RegisteredItem {
	element: HTMLElement;
	textValue: string;
	disabled: boolean;
}
const items = new SvelteMap<string | number, RegisteredItem>();

let triggerElement = $state<HTMLButtonElement | null>(null);
let popoverElement = $state<HTMLDivElement | null>(null);
let searchInputElement = $state<HTMLInputElement | null>(null);

closePopoverOnScrollClip({
	isOpen: () => open,
	element: () => popoverElement,
	close: () => setOpen(false),
});

const selectedText = $derived(
	currentKey !== null ? items.get(currentKey)?.textValue : undefined,
);

setSelectContext({
	get selectedKey() {
		return currentKey;
	},
	get focusedKey() {
		return focusedKey;
	},
	registerItem(key, element, options) {
		items.set(key, { element, ...options });
		return () => {
			items.delete(key);
		};
	},
	select(key) {
		commitSelection(key);
	},
	setFocusedKey(key) {
		focusedKey = key;
	},
});

function commitSelection(key: string | number | null) {
	if (!isControlled) {
		uncontrolledKey = key;
	}
	onSelectionChange?.(key);
	setOpen(false);
	triggerElement?.focus();
}

function setOpen(next: boolean) {
	if (open === next) return;

	if (next) {
		popoverElement?.showPopover();
	} else {
		popoverElement?.hidePopover();
	}
}

function orderedKeys(visibleOnly = true) {
	void visibleOnly;
	return [...items.entries()]
		.filter(([, item]) => !item.disabled)
		.sort(([, a], [, b]) =>
			a.element.compareDocumentPosition(b.element) &
			Node.DOCUMENT_POSITION_FOLLOWING
				? -1
				: 1,
		)
		.map(([key]) => key);
}

function moveFocus(direction: "next" | "previous" | "first" | "last") {
	const keys = orderedKeys();
	if (keys.length === 0) return;

	const currentIndex = focusedKey === null ? -1 : keys.indexOf(focusedKey);
	const targetIndex =
		direction === "first"
			? 0
			: direction === "last"
				? keys.length - 1
				: direction === "next"
					? Math.min(currentIndex + 1, keys.length - 1)
					: Math.max(currentIndex - 1, 0);

	focusedKey = keys[targetIndex];
	scrollFocusedIntoView();
}

function scrollFocusedIntoView() {
	if (focusedKey === null) return;
	items.get(focusedKey)?.element.scrollIntoView({ block: "nearest" });
}

function onTriggerKeydown(event: KeyboardEvent) {
	if (event.key === "ArrowDown" || event.key === "ArrowUp") {
		event.preventDefault();
		setOpen(true);
	}
}

function onPopoverKeydown(event: KeyboardEvent) {
	if (event.key === "Escape") {
		event.preventDefault();
		setOpen(false);
		triggerElement?.focus();
		return;
	}
	if (event.key === "ArrowDown") {
		event.preventDefault();
		moveFocus("next");
		return;
	}
	if (event.key === "ArrowUp") {
		event.preventDefault();
		moveFocus("previous");
		return;
	}
	if (event.key === "Home" && !search) {
		event.preventDefault();
		moveFocus("first");
		return;
	}
	if (event.key === "End" && !search) {
		event.preventDefault();
		moveFocus("last");
		return;
	}
	if (event.key === "Enter") {
		event.preventDefault();
		if (focusedKey !== null && !items.get(focusedKey)?.disabled) {
			commitSelection(focusedKey);
		}
	}
}

function onPopoverToggle(event: Event) {
	const next = (event as ToggleEvent).newState === "open";
	if (next === open) return;
	open = next;
	onOpenChange?.(next);

	if (next) {
		focusedKey = currentKey ?? orderedKeys(false)[0] ?? null;
		requestAnimationFrame(() => {
			if (search) {
				searchInputElement?.focus();
			} else {
				popoverElement?.focus();
			}
			scrollFocusedIntoView();
		});
	} else {
		searchValue = "";
		focusedKey = null;
	}
}

const hasVisibleItems = $derived(items.size > 0);

// while searching, keep an actionable item focused so Enter commits the top
// result the moment it appears (matching the react-aria autocomplete flow)
$effect(() => {
	if (!open || !search || searchValue === "") return;

	const keys = orderedKeys();
	if (
		focusedKey !== null &&
		keys.includes(focusedKey)
	) {
		return;
	}
	if (keys[0] !== undefined) {
		focusedKey = keys[0];
	}
});

const uid = $props.id();
const labelId = $derived(label ? `${uid}-select-label` : undefined);
const valueId = `${uid}-select-value`;
const popoverId = `${uid}-select-popover`;
const anchorName = `--select-anchor-${uid}`;
</script>

<div class="select" data-testid={testId}>
	{#if label}
		<span class="label" id={labelId}>{label}</span>
	{/if}
	<button
		type="button"
		class="button"
		bind:this={triggerElement}
		disabled={isDisabled}
		aria-haspopup="listbox"
		aria-expanded={open}
		aria-label={ariaLabel}
		aria-labelledby={labelId && !ariaLabel ? `${valueId} ${labelId}` : undefined}
		data-required={isRequired || undefined}
		popovertarget={popoverId}
		style:anchor-name={anchorName}
		onkeydown={onTriggerKeydown}
	>
		<span id={valueId} class="selectValue" data-placeholder={selectedText === undefined ? "true" : undefined}>
			{#if currentKey !== null && valueContent}
				{@render valueContent(currentKey)}
			{:else if selectedText !== undefined}
				{selectedText}
			{:else}
				{placeholder}
			{/if}
		</span>
		<span aria-hidden="true">
			<svg
				class="icon"
				xmlns="http://www.w3.org/2000/svg"
				viewBox="0 0 24 24"
				fill="none"
				stroke="currentColor"
				stroke-width="2"
				stroke-linecap="round"
				stroke-linejoin="round"
			>
				<path d="m7 15 5 5 5-5" />
				<path d="m7 9 5-5 5 5" />
			</svg>
		</span>
	</button>
	{#if clearable && currentKey !== null}
		<button
			type="button"
			class="clearButton"
			onclick={() => commitSelection(null)}
		>
			<svg
				class="clearIcon"
				xmlns="http://www.w3.org/2000/svg"
				viewBox="0 0 24 24"
				fill="none"
				stroke="currentColor"
				stroke-width="2"
				stroke-linecap="round"
				stroke-linejoin="round"
			>
				<path d="M18 6 6 18" />
				<path d="m6 6 12 12" />
			</svg>
			{clearText}
		</button>
	{/if}
	<!-- svelte-ignore a11y_no_static_element_interactions -- keydown steers the listbox inside -->
	<div
		bind:this={popoverElement}
		id={popoverId}
		popover="auto"
		class={["popover", popoverClass]}
		style:position-anchor={anchorName}
		ontoggle={onPopoverToggle}
		onkeydown={onPopoverKeydown}
		tabindex="-1"
	>
		{#if search && open}
			<div class="searchField" data-empty={searchValue === "" ? "true" : undefined}>
				<svg
					class="icon"
					aria-hidden="true"
					xmlns="http://www.w3.org/2000/svg"
					viewBox="0 0 24 24"
					fill="none"
					stroke="currentColor"
					stroke-width="2"
					stroke-linecap="round"
					stroke-linejoin="round"
				>
					<circle cx="11" cy="11" r="8" />
					<path d="m21 21-4.3-4.3" />
				</svg>
				<input
					type="search"
					bind:this={searchInputElement}
					bind:value={searchValue}
					placeholder={search.placeholder}
					aria-label="Search"
					data-testid={search.testId}
					class="searchInput in-container"
				/>
				<button
					type="button"
					class="searchClearButton"
					tabindex="-1"
					aria-label="Clear"
					onclick={() => {
						searchValue = "";
						searchInputElement?.focus();
					}}
				>
					<svg
						class="icon"
						xmlns="http://www.w3.org/2000/svg"
						viewBox="0 0 24 24"
						fill="none"
						stroke="currentColor"
						stroke-width="2"
						stroke-linecap="round"
						stroke-linejoin="round"
					>
						<path d="M18 6 6 18" />
						<path d="m6 6 12 12" />
					</svg>
				</button>
			</div>
		{/if}
		<!-- labelled only while open so a closed select exposes exactly one
		     element under its label (the trigger) to queries -->
		<div
			class="listBox scrollbar"
			role="listbox"
			aria-labelledby={open ? labelId : undefined}
		>
			{@render children()}
			{#if !hasVisibleItems}
				<div class="noResults">{noResultsText}</div>
			{/if}
		</div>
	</div>
</div>

<style>
	.select {
		width: 100%;
		position: relative;
		display: flex;
		flex-direction: column;
		gap: var(--s-1-5);
	}

	.label {
		font-size: var(--font-xs);
		font-weight: var(--weight-bold);
		margin: 0;
		display: block;
		text-box: trim-start cap alphabetic;
	}

	.button {
		height: var(--field-size);
		padding: 0 var(--field-padding);
		border: var(--border-style);
		border-radius: var(--radius-field);
		background-color: var(--color-bg);
		outline: none;

		display: flex;
		align-items: center;
		justify-content: space-between;
		gap: var(--s-1-5);
		width: 100%;
		cursor: pointer;

		&:focus-visible,
		&[aria-expanded="true"] {
			outline: var(--focus-ring);
			outline-offset: 1px;
		}

		&:disabled {
			pointer-events: none;
			cursor: not-allowed;
			opacity: 0.5;
			outline: none;
		}
	}

	.selectValue {
		font-size: var(--font-sm);
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
		min-width: 0;
		color: var(--color-text);
		display: flex;
		align-items: center;

		&[data-placeholder] {
			color: var(--color-text-high);
		}
	}

	.icon {
		min-width: 18px;
		max-width: 18px;
		color: var(--color-text-high);
	}

	.popover {
		position: fixed;
		position-area: block-end;
		position-try-fallbacks: flip-block;
		width: anchor-size(width);
		max-height: 300px;
		margin: var(--s-1) 0;
		padding: var(--s-1);
		border: var(--border-style);
		border-radius: var(--radius-box);
		background-color: var(--color-bg);
		outline: none;
		color: var(--color-text);

		display: none;
		flex-direction: column;

		&:popover-open {
			display: flex;
		}
	}

	.listBox {
		overflow: auto;
		flex: 1;
	}

	.searchField {
		position: relative;
		display: flex;
		gap: var(--s-2);

		border-bottom: 1px solid var(--color-border);
		border-radius: 0;
		accent-color: var(--color-accent);
		color: var(--color-text);
		outline: none;
		padding: var(--s-1-5) var(--s-1-5) calc(var(--s-0-5) + var(--s-2))
			var(--s-1-5);
		margin-block-end: var(--s-1-5);

		&[data-empty] .searchClearButton {
			visibility: hidden;
		}
	}

	.searchInput {
		all: unset;
		font-size: var(--font-xs);
		font-weight: var(--weight-semi);
		letter-spacing: 0.5px;
		flex: 1;
		min-width: 0;
		padding-inline-end: calc(18px + var(--s-2));

		&::-webkit-search-cancel-button {
			display: none;
		}

		&::placeholder {
			color: var(--color-text-high);
		}
	}

	.searchClearButton {
		position: absolute;
		right: var(--s-2);
		top: 50%;
		transform: translateY(-50%);
		background-color: transparent;
		border: none;
		padding: 0;
		cursor: pointer;
		color: var(--color-text-high);
	}

	.noResults {
		font-size: var(--font-md);
		font-weight: var(--weight-bold);
		text-align: center;
		padding-block: var(--s-8);
		color: var(--color-text-high);
	}

	.clearButton {
		position: absolute;
		bottom: -21px;
		right: 9px;

		display: flex;
		align-items: center;
		border: none;
		background-color: transparent;
		color: var(--color-error);
		cursor: pointer;
		font-size: var(--font-2xs);
		font-weight: var(--weight-bold);
		height: var(--field-size-xs);
		padding: 0;
	}

	.clearIcon {
		min-width: 14px;
		max-width: 14px;
		margin-inline-end: var(--s-1);
	}
</style>

// app/components/elements/Select.tsx
import clsx from "clsx";
import { ChevronsUpDown, Search, X } from "lucide-react";
import * as React from "react";
import { useTranslation } from "react-i18next";
import { SendouBottomTexts } from "~/components/elements/BottomTexts";
import { SendouButton } from "~/components/elements/Button";
import { Image } from "../Image";
import { useAnchorPositioning } from "./anchor-positioning";
import { isOwnToggle, useAnchorSafeId } from "./Popover";
import styles from "./Select.module.css";
import { useCloseOnScrollClip } from "./useCloseOnScrollClip";

export type SelectKey = string | number;

interface RegisteredItem {
	element: HTMLElement;
	textValue: string;
	disabled: boolean;
	getContent: () => React.ReactNode;
}

/**
 * Focused option kept outside React state so hovering across options
 * re-renders only the two options whose focus changed, not the whole list.
 */
interface FocusStore {
	get: () => SelectKey | null;
	set: (key: SelectKey | null) => void;
	subscribe: (listener: () => void) => () => void;
}

/** Stable-identity callbacks items use to wire themselves to the select. */
interface SelectRegistry {
	registerItem: (key: SelectKey, item: RegisteredItem) => () => void;
	select: (key: SelectKey) => void;
	focus: FocusStore;
	optionIdFor: (key: SelectKey) => string;
}

interface SelectState {
	open: boolean;
	selectedKey: SelectKey | null;
	disabledKeys?: Set<SelectKey>;
	matches: (textValue: string) => boolean;
}

const SelectRegistryContext = React.createContext<SelectRegistry | null>(null);
const SelectStateContext = React.createContext<SelectState | null>(null);

export interface SendouSelectProps<T extends object> {
	label?: string;
	/** Renders a required marker next to the label. */
	labelRequired?: boolean;
	placeholder?: string;
	selectedKey?: SelectKey | null;
	defaultSelectedKey?: SelectKey | null;
	onSelectionChange?: (key: SelectKey | null) => void;
	onOpenChange?: (isOpen: boolean) => void;
	clearable?: boolean;
	disabledKeys?: SelectKey[];
	isDisabled?: boolean;
	isRequired?: boolean;
	/** Submits the selected key with the surrounding form. */
	name?: string;
	"data-testid"?: string;
	"aria-label"?: string;
	className?: string;
	popoverClassName?: string;
	search?: { placeholder?: string; testId?: string; inputClassName?: string };
	/** Value of the search input, used for controlled components */
	searchInputValue?: string;
	/** Callback for when the search input value changes. When defined `items` has to be filtered on the caller side (automatic filtering in component disabled). */
	onSearchInputChange?: (value: string) => void;
	/** Custom search matcher, replacing the default textValue "contains" filter. */
	filter?: (textValue: string, searchValue: string) => boolean;
	errorText?: string;
	bottomText?: string;
	onBlur?: () => void;
	triggerRef?: React.Ref<HTMLButtonElement>;
	items?: Iterable<T>;
	children: React.ReactNode | ((item: T) => React.ReactNode);
}

/**
 * A customizable select component with optional search functionality,
 * rendered through the native popover API with CSS anchor positioning.
 *
 * Options mount only while the popover is open (plus the selected one, so the
 * trigger can show it); the trigger's content is read straight from the
 * `SendouSelectItem` element matching the selection, so it is server rendered.
 *
 * @example
 * ```tsx
 * <SendouSelect items={items} search={{ placeholder: "Search for items..." }}>
 *   {({ key, ...item }) => (
 *     <SendouSelectItem key={key} {...item}>
 *       {item.name}
 *     </SendouSelectItem>
 *   )}
 * </SendouSelect>
 * ```
 */
export function SendouSelect<T extends object>({
	label,
	labelRequired,
	placeholder,
	selectedKey,
	defaultSelectedKey,
	onSelectionChange,
	onOpenChange,
	clearable = false,
	disabledKeys,
	isDisabled,
	isRequired,
	name,
	"data-testid": testId,
	"aria-label": ariaLabel,
	className,
	popoverClassName,
	search,
	searchInputValue,
	onSearchInputChange,
	filter,
	errorText,
	bottomText,
	onBlur,
	triggerRef,
	items,
	children,
}: SendouSelectProps<T>) {
	const { t } = useTranslation(["common"]);
	const uid = useAnchorSafeId();
	const popoverId = `${uid}-select-popover`;
	const listboxId = `${uid}-select-listbox`;
	const anchorName = `--select-anchor-${uid}`;
	const labelId = label ? `${uid}-select-label` : undefined;
	const valueId = `${uid}-select-value`;
	const triggerId = `${uid}-select-trigger`;
	const hiddenAriaLabelId =
		label && ariaLabel ? `${uid}-select-aria-label` : undefined;

	const [isControlled] = React.useState(selectedKey !== undefined);
	const [uncontrolledKey, setUncontrolledKey] =
		React.useState<SelectKey | null>(defaultSelectedKey ?? null);
	const currentKey = isControlled ? (selectedKey ?? null) : uncontrolledKey;

	const isSearchControlled = !!onSearchInputChange;
	const [uncontrolledSearch, setUncontrolledSearch] = React.useState("");
	const searchValue = isSearchControlled
		? (searchInputValue ?? "")
		: uncontrolledSearch;
	const setSearchValue = (value: string) => {
		if (isSearchControlled) {
			onSearchInputChange(value);
		} else {
			setUncontrolledSearch(value);
		}
	};

	const [open, setOpenState] = React.useState(false);
	const [, rerenderWithRegisteredContent] = React.useReducer(
		(count: number) => count + 1,
		0,
	);

	const itemsMapRef = React.useRef(new Map<SelectKey, RegisteredItem>());
	const keyByElementRef = React.useRef(new WeakMap<HTMLElement, SelectKey>());
	/** Persists past unregistration so the trigger can render a filtered-out selection. */
	const contentByKeyRef = React.useRef(
		new Map<
			SelectKey,
			{ textValue: string; getContent: () => React.ReactNode }
		>(),
	);
	/** Selection whose content only a wrapped item's registration can provide. */
	const unresolvedSelectionRef = React.useRef<SelectKey | null>(null);
	const normalizedTextCacheRef = React.useRef(new Map<string, string>());

	const triggerElementRef = React.useRef<HTMLButtonElement | null>(null);
	const popoverRef = React.useRef<HTMLDivElement | null>(null);
	const listboxRef = React.useRef<HTMLDivElement | null>(null);
	const searchInputRef = React.useRef<HTMLInputElement | null>(null);

	useCloseOnScrollClip(open, popoverRef, () => setOpen(false));
	useAnchorPositioning({
		isOpen: open,
		popoverRef,
		getAnchor: () => triggerElementRef.current,
		matchAnchorWidth: true,
		constrainHeight: true,
	});

	const commitSelection = (key: SelectKey | null) => {
		if (!isControlled) {
			setUncontrolledKey(key);
		}
		onSelectionChange?.(key);
		setOpen(false);
		triggerElementRef.current?.focus();
	};

	function setOpen(next: boolean) {
		if (next) {
			popoverRef.current?.showPopover();
		} else {
			popoverRef.current?.hidePopover();
		}
	}

	const commitSelectionRef = React.useRef(commitSelection);
	commitSelectionRef.current = commitSelection;

	const [registry] = React.useState<SelectRegistry>(() => ({
		registerItem: (key, item) => {
			itemsMapRef.current.set(key, item);
			keyByElementRef.current.set(item.element, key);
			contentByKeyRef.current.set(key, {
				textValue: item.textValue,
				getContent: item.getContent,
			});
			if (key === unresolvedSelectionRef.current) {
				rerenderWithRegisteredContent();
			}
			return () => {
				itemsMapRef.current.delete(key);
			};
		},
		select: (key) => commitSelectionRef.current(key),
		focus: createFocusStore(),
		optionIdFor: (key) => `${popoverId}-option-${key}`,
	}));
	const focusStore = registry.focus;

	/** Keys of the enabled options in DOM order. */
	const orderedKeys = () => {
		const listbox = listboxRef.current;
		if (!listbox) return [];

		const keys: SelectKey[] = [];
		for (const element of listbox.querySelectorAll<HTMLElement>(
			'[role="option"]',
		)) {
			const key = keyByElementRef.current.get(element);
			if (key === undefined || itemsMapRef.current.get(key)?.disabled) {
				continue;
			}
			keys.push(key);
		}
		return keys;
	};

	const scrollIntoView = (key: SelectKey | null) => {
		if (key === null) return;
		itemsMapRef.current.get(key)?.element.scrollIntoView({ block: "nearest" });
	};

	const moveFocus = (direction: "next" | "previous" | "first" | "last") => {
		const keys = orderedKeys();
		if (keys.length === 0) return;

		const focusedKey = focusStore.get();
		const currentIndex = focusedKey === null ? -1 : keys.indexOf(focusedKey);
		const targetIndex =
			direction === "first"
				? 0
				: direction === "last"
					? keys.length - 1
					: direction === "next"
						? Math.min(currentIndex + 1, keys.length - 1)
						: Math.max(currentIndex - 1, 0);

		focusStore.set(keys[targetIndex]);
		scrollIntoView(keys[targetIndex]);
	};

	const onTriggerKeyDown = (event: React.KeyboardEvent) => {
		if (event.key === "ArrowDown" || event.key === "ArrowUp") {
			event.preventDefault();
			setOpen(true);
		}
	};

	const onPopoverKeyDown = (event: React.KeyboardEvent) => {
		if (event.key === "Escape") {
			event.preventDefault();
			setOpen(false);
			triggerElementRef.current?.focus();
			return;
		}
		if (event.key === "Tab") {
			triggerElementRef.current?.focus();
			setOpen(false);
			return;
		}
		if (event.key === "ArrowDown") {
			event.preventDefault();
			moveFocus("next");
			return;
		}
		if (event.key === "ArrowUp") {
			event.preventDefault();
			moveFocus("previous");
			return;
		}
		if (event.key === "Home" && !search) {
			event.preventDefault();
			moveFocus("first");
			return;
		}
		if (event.key === "End" && !search) {
			event.preventDefault();
			moveFocus("last");
			return;
		}
		if (event.key === "Enter") {
			event.preventDefault();
			const focusedKey = focusStore.get();
			// registration is what proves the option is still in the list, the
			// search can have filtered the focused one out from under the user
			const focusedItem =
				focusedKey !== null ? itemsMapRef.current.get(focusedKey) : undefined;
			if (focusedKey !== null && focusedItem && !focusedItem.disabled) {
				commitSelection(focusedKey);
			}
		}
	};

	const onPopoverToggle = (event: React.ToggleEvent<HTMLDivElement>) => {
		if (!isOwnToggle(event)) return;

		const next = event.newState === "open";
		if (next === open) return;
		setOpenState(next);
		onOpenChange?.(next);

		if (next) {
			focusStore.set(currentKey);
			// the toggle event's render mounts the options synchronously, so they
			// are registered by the time this runs
			requestAnimationFrame(() => {
				if (search) {
					searchInputRef.current?.focus();
				} else {
					listboxRef.current?.focus();
				}
				scrollIntoView(currentKey);
			});
		} else {
			setSearchValue("");
			focusStore.set(null);
		}
	};

	const normalizedSearchValue = normalizeForSearch(searchValue);
	const normalizedTextValue = (textValue: string) => {
		const cache = normalizedTextCacheRef.current;
		let normalized = cache.get(textValue);
		if (normalized === undefined) {
			normalized = normalizeForSearch(textValue);
			cache.set(textValue, normalized);
		}
		return normalized;
	};

	const matches = (textValue: string) => {
		if (searchValue === "") return true;
		if (filter) return filter(textValue, searchValue);
		if (isSearchControlled || !search) return true;
		return normalizedTextValue(textValue).includes(normalizedSearchValue);
	};

	// while searching, keep an actionable item focused so Enter commits the top
	// result the moment it appears; deliberately runs after every render since
	// controlled results can arrive without the search value changing
	React.useEffect(() => {
		if (!open || !search || searchValue === "") return;

		const focusedKey = focusStore.get();
		if (
			focusedKey !== null &&
			itemsMapRef.current.get(focusedKey)?.disabled === false
		) {
			return;
		}
		focusStore.set(orderedKeys()[0] ?? null);
	});

	const state: SelectState = {
		open,
		selectedKey: currentKey,
		disabledKeys: disabledKeys ? new Set(disabledKeys) : undefined,
		matches,
	};

	const renderedChildren =
		typeof children === "function"
			? Array.from(items ?? []).map(children)
			: children;

	let selectedItemContent: React.ReactNode | undefined;
	let visibleItemCount = 0;
	forEachItemElement(
		renderedChildren,
		(itemProps) => {
			if (itemProps.id === currentKey) {
				selectedItemContent = itemProps.children;
			}
			if (isItemVisible(state, itemProps.id, resolveTextValue(itemProps))) {
				visibleItemCount++;
			}
		},
		() => {
			visibleItemCount++;
		},
	);

	const registeredSelection =
		selectedItemContent === undefined && currentKey !== null
			? contentByKeyRef.current.get(currentKey)
			: undefined;
	const selectedContent =
		selectedItemContent !== undefined
			? selectedItemContent
			: registeredSelection
				? (registeredSelection.getContent() ?? registeredSelection.textValue)
				: undefined;
	unresolvedSelectionRef.current =
		selectedContent === undefined ? currentKey : null;

	return (
		// biome-ignore lint/a11y/noStaticElementInteractions: only observes focus leaving the select
		<div
			className={clsx(className, styles.select)}
			data-testid={testId}
			onBlur={(event) => {
				if (
					event.relatedTarget instanceof Node &&
					event.currentTarget.contains(event.relatedTarget)
				) {
					return;
				}
				if (event.relatedTarget instanceof Node) {
					setOpen(false);
				}
				onBlur?.();
			}}
		>
			{label ? (
				<label className={styles.label} id={labelId} htmlFor={triggerId}>
					{label}
					{labelRequired ? <span className="text-error"> *</span> : null}
				</label>
			) : null}
			{hiddenAriaLabelId ? (
				<span id={hiddenAriaLabelId} hidden>
					{ariaLabel}
				</span>
			) : null}
			<button
				type="button"
				id={triggerId}
				className={styles.button}
				ref={(element) => {
					triggerElementRef.current = element;
					if (typeof triggerRef === "function") {
						triggerRef(element);
					} else if (triggerRef) {
						triggerRef.current = element;
					}
				}}
				disabled={isDisabled}
				aria-haspopup="listbox"
				aria-expanded={open}
				aria-label={label ? undefined : ariaLabel}
				aria-labelledby={
					labelId
						? hiddenAriaLabelId
							? `${labelId} ${hiddenAriaLabelId} ${valueId}`
							: `${valueId} ${labelId}`
						: undefined
				}
				data-required={isRequired || undefined}
				popoverTarget={popoverId}
				style={{ anchorName } as React.CSSProperties}
				onKeyDown={onTriggerKeyDown}
			>
				<span
					id={valueId}
					className={styles.selectValue}
					data-placeholder={selectedContent === undefined ? "true" : undefined}
				>
					{selectedContent !== undefined ? selectedContent : placeholder}
				</span>
				<span aria-hidden="true">
					<ChevronsUpDown className={styles.icon} />
				</span>
			</button>
			{clearable && currentKey !== null ? (
				<SendouButton
					variant="minimal-destructive"
					size="miniscule"
					icon={<X />}
					onClick={() => commitSelection(null)}
					className={styles.clearButton}
				>
					Clear
				</SendouButton>
			) : null}
			{name ? (
				<input type="hidden" name={name} value={currentKey ?? ""} />
			) : null}
			<SendouBottomTexts bottomText={bottomText} errorText={errorText} />
			{/* biome-ignore lint/a11y/noStaticElementInteractions: keydown steers the listbox inside */}
			<div
				ref={popoverRef}
				id={popoverId}
				popover="auto"
				className={clsx(styles.popover, popoverClassName)}
				style={{ positionAnchor: anchorName } as React.CSSProperties}
				onToggle={onPopoverToggle}
				onKeyDown={onPopoverKeyDown}
				tabIndex={-1}
			>
				{search && open ? (
					<SearchField
						registry={registry}
						inputRef={searchInputRef}
						value={searchValue}
						onChange={setSearchValue}
						placeholder={search.placeholder}
						listboxId={listboxId}
						testId={search.testId}
						className={clsx(
							search.inputClassName ?? "in-container",
							styles.searchInput,
						)}
					/>
				) : null}
				<Listbox
					registry={registry}
					open={open}
					listboxRef={listboxRef}
					id={listboxId}
					labelId={labelId}
				>
					<SelectRegistryContext value={registry}>
						<SelectStateContext value={state}>
							{renderedChildren}
						</SelectStateContext>
					</SelectRegistryContext>
					{open && visibleItemCount === 0 ? (
						<div className={styles.noResults}>{t("common:noResults")}</div>
					) : null}
				</Listbox>
			</div>
		</div>
	);
}

function createFocusStore(): FocusStore {
	let focusedKey: SelectKey | null = null;
	const listeners = new Set<() => void>();

	return {
		get: () => focusedKey,
		set: (key) => {
			if (key === focusedKey) return;
			focusedKey = key;
			for (const listener of listeners) {
				listener();
			}
		},
		subscribe: (listener) => {
			listeners.add(listener);
			return () => listeners.delete(listener);
		},
	};
}

/** Subscribes only this component to focus changes, keeping the select root out of hover re-renders. */
function useActiveDescendant(registry: SelectRegistry, open: boolean) {
	const focusedKey = React.useSyncExternalStore(
		registry.focus.subscribe,
		registry.focus.get,
		() => null,
	);
	return open && focusedKey !== null
		? registry.optionIdFor(focusedKey)
		: undefined;
}

function SearchField({
	registry,
	inputRef,
	value,
	onChange,
	placeholder,
	listboxId,
	testId,
	className,
}: {
	registry: SelectRegistry;
	inputRef: React.RefObject<HTMLInputElement | null>;
	value: string;
	onChange: (value: string) => void;
	placeholder?: string;
	listboxId: string;
	testId?: string;
	className: string;
}) {
	const activeDescendant = useActiveDescendant(registry, true);

	return (
		<div
			className={styles.searchField}
			data-empty={value === "" ? "true" : undefined}
		>
			<Search aria-hidden className={styles.icon} />
			<input
				type="search"
				ref={inputRef}
				value={value}
				onChange={(event) => onChange(event.target.value)}
				placeholder={placeholder}
				role="combobox"
				aria-label="Search"
				aria-controls={listboxId}
				aria-expanded
				aria-autocomplete="list"
				aria-activedescendant={activeDescendant}
				data-testid={testId}
				className={className}
			/>
			<button
				type="button"
				className={styles.searchClearButton}
				tabIndex={-1}
				aria-label="Clear"
				onClick={() => {
					onChange("");
					inputRef.current?.focus();
				}}
			>
				<X className={styles.icon} />
			</button>
		</div>
	);
}

function Listbox({
	registry,
	open,
	listboxRef,
	id,
	labelId,
	children,
}: {
	registry: SelectRegistry;
	open: boolean;
	listboxRef: React.RefObject<HTMLDivElement | null>;
	id: string;
	labelId?: string;
	children: React.ReactNode;
}) {
	const activeDescendant = useActiveDescendant(registry, open);

	return (
		// labelled only while open so a closed select exposes exactly one
		// element under its label (the trigger) to queries
		<div
			ref={listboxRef}
			id={id}
			className={clsx(styles.listBox, "scrollbar")}
			role="listbox"
			tabIndex={-1}
			aria-labelledby={open ? labelId : undefined}
			aria-activedescendant={activeDescendant}
		>
			{children}
		</div>
	);
}

function normalizeForSearch(value: string) {
	return value
		.normalize("NFD")
		.replace(/\p{Diacritic}/gu, "")
		.toLowerCase();
}

/** Case- and diacritic-insensitive "contains" matcher, the select's default search filter. */
export function searchContains(value: string, substring: string) {
	return normalizeForSearch(value).includes(normalizeForSearch(substring));
}

export interface SendouSelectItemProps {
	id: SelectKey;
	textValue?: string;
	isDisabled?: boolean;
	className?: string;
	"data-testid"?: string;
	"data-status"?: string;
	children: React.ReactNode;
}

function resolveTextValue({ textValue, children }: SendouSelectItemProps) {
	return textValue ?? (typeof children === "string" ? children : "");
}

/** Closed selects keep only the selected option mounted, open ones the search matches. */
function isItemVisible(state: SelectState, id: SelectKey, textValue: string) {
	if (!state.open) return state.selectedKey === id;
	return state.matches(textValue);
}

/**
 * Visits the `SendouSelectItem` elements reachable through arrays, fragments
 * and sections. Items hidden behind other components are opaque: `onOpaque`
 * lets callers treat them as present.
 */
function forEachItemElement(
	node: React.ReactNode,
	visit: (props: SendouSelectItemProps) => void,
	onOpaque: () => void,
) {
	if (Array.isArray(node)) {
		for (const child of node) {
			forEachItemElement(child, visit, onOpaque);
		}
		return;
	}
	if (!React.isValidElement(node)) return;

	if (node.type === SendouSelectItem) {
		visit(node.props as SendouSelectItemProps);
	} else if (
		node.type === React.Fragment ||
		node.type === SendouSelectItemSection
	) {
		forEachItemElement(
			(node.props as { children?: React.ReactNode }).children,
			visit,
			onOpaque,
		);
	} else {
		onOpaque();
	}
}

function hasVisibleItems(state: SelectState, node: React.ReactNode) {
	let found = false;
	forEachItemElement(
		node,
		(itemProps) => {
			if (isItemVisible(state, itemProps.id, resolveTextValue(itemProps))) {
				found = true;
			}
		},
		() => {
			found = true;
		},
	);
	return found;
}

export function SendouSelectItem(props: SendouSelectItemProps) {
	const {
		id,
		isDisabled: isDisabledProp = false,
		className,
		"data-testid": testId,
		"data-status": dataStatus,
		children,
	} = props;
	const registry = React.use(SelectRegistryContext);
	const state = React.use(SelectStateContext);
	if (!registry || !state) {
		throw new Error("SendouSelectItem must be inside SendouSelect");
	}

	const isDisabled = isDisabledProp || !!state.disabledKeys?.has(id);
	const resolvedText = resolveTextValue(props);
	const visible = isItemVisible(state, id, resolvedText);
	const isFocused = React.useSyncExternalStore(
		registry.focus.subscribe,
		() => registry.focus.get() === id,
		() => false,
	);

	const childrenRef = React.useRef(children);
	childrenRef.current = children;
	const elementRef = React.useRef<HTMLDivElement | null>(null);

	React.useEffect(() => {
		if (!visible) return;
		const element = elementRef.current;
		if (!element) return;
		return registry.registerItem(id, {
			element,
			textValue: resolvedText,
			disabled: isDisabled,
			getContent: () => childrenRef.current,
		});
	}, [visible, id, resolvedText, isDisabled, registry]);

	if (!visible) return null;

	const isSelected = state.selectedKey === id;

	return (
		<div
			ref={elementRef}
			id={registry.optionIdFor(id)}
			role="option"
			tabIndex={-1}
			aria-selected={isSelected}
			aria-disabled={isDisabled || undefined}
			data-disabled={isDisabled ? "true" : undefined}
			data-testid={testId}
			data-status={dataStatus}
			className={clsx(styles.item, className, {
				[styles.itemFocused]: isFocused,
				[styles.itemSelected]: isSelected,
			})}
			onClick={() => {
				if (!isDisabled) registry.select(id);
			}}
			onPointerMove={() => {
				if (!isDisabled) registry.focus.set(id);
			}}
		>
			{children}
		</div>
	);
}

interface SendouSelectItemSectionProps {
	heading: string;
	headingImgPath?: string;
	children: React.ReactNode;
	className?: string;
}

export function SendouSelectItemSection({
	heading,
	headingImgPath,
	children,
	className,
}: SendouSelectItemSectionProps) {
	const state = React.use(SelectStateContext);
	if (!state) {
		throw new Error("SendouSelectItemSection must be inside SendouSelect");
	}
	if (!hasVisibleItems(state, children)) return null;

	return (
		// biome-ignore lint/a11y/useSemanticElements: a fieldset would carry form semantics this listbox section does not have
		<div role="group" aria-label={heading} className={styles.section}>
			<div className={clsx(className, styles.categoryHeading)}>
				{headingImgPath ? (
					<Image path={headingImgPath} size={28} alt="" />
				) : null}
				{heading}
				<div className={styles.categoryDivider} />
			</div>
			{children}
		</div>
	);
}
