// src/routes/maps/+page.svelte
<script lang="ts">
	import Main from '$lib/components/layout/Main.svelte';
	import ModeMapPoolPicker from '$lib/components/ModeMapPoolPicker.svelte';
	import OpenGraphMeta from '$lib/components/OpenGraphMeta.svelte';
	import { modesShort } from '$lib/constants/in-game/modes';
	import type { ModeWithStage } from '$lib/constants/in-game/types';
	import { SearchParamState } from '$lib/runes/search-param-state.svelte';
	import * as MapPool from '$lib/core/maps/MapPool';
	import z from 'zod';
	import { partialMapPoolSchema } from '$lib/utils/zod';
	import Button from '$lib/components/buttons/Button.svelte';
	import X from '@lucide/svelte/icons/x';
	import Tally5 from '@lucide/svelte/icons/tally-5';
	import { m } from '$lib/paraglide/messages';
	import { stageIds } from '$lib/constants/in-game/stage-ids';
	import ListOrdered from '@lucide/svelte/icons/list-ordered';
	import SwitchFormField from '$lib/components/form/SwitchFormField.svelte';
	import {
		modesLongTranslations,
		modesShortTranslations,
		stageTranslations
	} from '$lib/utils/i18n';
	import CopyToClipboardButton from '$lib/components/CopyToClipboardButton.svelte';
	import * as MapList from '$lib/core/maps/MapList';

	const AMOUNT_OF_MAPS_TO_GENERATE = stageIds.length;

	const MAP_POOL_CODEC = z.codec(z.string(), partialMapPoolSchema(), {
		decode: (string) => MapPool.fromSerialized(string),
		encode: (mapPool) => MapPool.toSerialized(mapPool)
	});

	const mapPool = new SearchParamState({
		key: 'pool',
		defaultValue: MapPool.empty(),
		schema: MAP_POOL_CODEC
	});

	let splatZonesEveryOther = $state(false);
	let mapList = $state<Array<ModeWithStage> | null>(null);

	function generateMapListFromSelection() {
		const generator = MapList.generate({ mapPool: mapPool.state });
		generator.next();

		const createdMapList = generator.next({
			amount: AMOUNT_OF_MAPS_TO_GENERATE,
			pattern: splatZonesEveryOther ? (Math.random() > 0.5 ? 'SZ*' : '*SZ') : ''
		}).value;

		mapList = createdMapList;
	}
</script>

<OpenGraphMeta
	title="Map List Generator"
	ogTitle="Splatoon 3 map list generator"
	description="Generate a map list based on maps you choose or a tournament's map pool."
/>

<Main class="stack lg">
	{@render mapPoolPicker()}
	<a
		href={`https://maps.iplabs.ink/?3&pool=${MapPool.toSerialized(mapPool.state)}`}
		target="_blank"
		rel="noreferrer"
		class="tournament-map-list-link"
	>
		{m.common_maps_tournamentMaplist()}
	</a>
	<div class="stack items-center">
		<SwitchFormField label={m.common_maps_halfSz()} bind:checked={splatZonesEveryOther} />
	</div>
	<div class="stack items-center">
		<Button
			size="big"
			icon={ListOrdered}
			disabled={MapPool.isEmpty(mapPool.state)}
			onclick={generateMapListFromSelection}>{m.common_maps_createMapList()}</Button
		>
	</div>
	{#if mapList}
		{@render mapListWithCopy(mapList)}
	{/if}
</Main>

{#snippet mapPoolPicker()}
	{#each modesShort as mode (mode)}
		<div class="stack md">
			<ModeMapPoolPicker
				{mode}
				bind:pool={
					() => mapPool.state[mode] ?? [],
					(value) => mapPool.update({ ...mapPool.state, [mode]: value })
				}
			/>
			<div class="stack horizontal md justify-center">
				<Button
					size="miniscule"
					icon={Tally5}
					variant="outlined"
					onclick={() => {
						const newPool = { ...mapPool.state, [mode]: [...stageIds] };
						mapPool.update(newPool);
					}}>{m.builds_stats_all()}</Button
				>
				<Button
					size="miniscule"
					icon={X}
					variant="destructive"
					onclick={() => {
						const newPool = { ...mapPool.state };
						delete newPool[mode];
						mapPool.update(newPool);
					}}>{m.common_maps_template_none()}</Button
				>
			</div>
		</div>
	{/each}
{/snippet}

{#snippet mapListWithCopy(list: NonNullable<typeof mapList>)}
	{@const mapListString = list
		.map(
			({ mode, stageId }, i) =>
				`${i + 1}) ${modesShortTranslations[mode]()} ${stageTranslations[stageId]()}`
		)
		.join('\n')}
	<div class="map-list-container">
		<ol class="map-list">
			{#each list as { mode, stageId }, i (i)}
				<li>
					<abbr class="mode-abbr" title={modesLongTranslations[mode]()}>
						{modesShortTranslations[mode]()}
					</abbr>
					{stageTranslations[stageId]()}
				</li>
			{/each}
		</ol>
		<div>
			<CopyToClipboardButton content={mapListString} />
		</div>
	</div>
{/snippet}

<style>
	.tournament-map-list-link {
		font-size: var(--fonts-xxs);
		text-align: center;
		color: var(--color-primary);
	}

	.map-list {
		font-size: var(--fonts-xs);
		font-weight: var(--semi-bold);
		margin-block-start: var(--s-4);
	}

	.map-list-container {
		margin: 0 auto;
		display: flex;
		align-items: center;
		flex-direction: column;
		gap: var(--s-8);
	}

	.mode-abbr {
		color: var(--color-secondary);
		font-weight: var(--bold);
		text-decoration: none;
	}
</style>

// app/features/map-list-generator/routes/maps.tsx
import { Check, Clipboard } from "lucide-react";
import * as React from "react";
import { useTranslation } from "react-i18next";
import type { MetaFunction } from "react-router";
import { SendouButton } from "~/components/elements/Button";
import { SendouSwitch } from "~/components/elements/Switch";
import { Label } from "~/components/Label";
import { Main } from "~/components/Main";
import { MapPoolPicker, useMapPoolQuickFill } from "~/components/MapPoolPicker";
import { MapPoolStages } from "~/components/MapPoolStages";
import { useCopyToClipboard } from "~/hooks/useCopyToClipboard";
import { stageIds } from "~/modules/in-game-lists/stage-ids";
import type { ModeWithStage } from "~/modules/in-game-lists/types";
import { useSearchParamsTyped } from "~/modules/search-params/hooks";
import { invariant } from "~/utils/invariant";
import { metaTags, ogPageImage } from "~/utils/remix";
import type { SendouRouteHandle } from "~/utils/remix.server";
import { ipLabsMaps, MAPS_URL, navIconUrl } from "~/utils/urls";
import * as MapList from "../core/MapList";
import { MapPool } from "../core/map-pool";
import { mapListGeneratorSearchParams } from "../map-list-generator-search-params";

import styles from "./maps.module.css";

const AMOUNT_OF_MAPS_IN_MAP_LIST = stageIds.length * 2;

export const meta: MetaFunction = (args) => {
	return metaTags({
		title: "Map List Generator",
		ogTitle: "Splatoon 3 map list generator",
		description:
			"Generate a map list based on maps you choose or a tournament's map pool.",
		image: ogPageImage("maps"),
		location: args.location,
	});
};

export const handle: SendouRouteHandle = {
	i18n: "game-misc",
	breadcrumb: () => ({
		imgPath: navIconUrl("maps"),
		href: MAPS_URL,
		type: "IMAGE",
	}),
};

export default function MapListPage() {
	const { t } = useTranslation(["common"]);
	const { mapPool, handleMapPoolChange, readonly } =
		useSearchParamPersistedMapPool();
	const quickFill = useMapPoolQuickFill();

	return (
		<Main className={`${styles.container} stack lg`}>
			{readonly ? (
				<MapPoolStages mapPool={mapPool} />
			) : (
				<MapPoolPicker
					mapPool={mapPool}
					onChange={handleMapPoolChange}
					quickFill={quickFill}
					aria-label={t("common:maps.mapPool")}
				/>
			)}
			<a
				href={ipLabsMaps(mapPool.serialized)}
				target="_blank"
				rel="noreferrer"
				className={styles.tournamentMapListLink}
			>
				{t("common:maps.tournamentMaplist")}
			</a>
			<MapListCreator mapPool={mapPool} />
		</Main>
	);
}

export function useSearchParamPersistedMapPool() {
	const [params, setParams] = useSearchParamsTyped(
		mapListGeneratorSearchParams,
	);

	const [mapPool, setMapPool] = React.useState(() => new MapPool(params.pool));

	const handleMapPoolChange = (newMapPool: MapPool) => {
		setMapPool(newMapPool);
		setParams({ pool: newMapPool.serialized });
	};

	return {
		mapPool,
		readonly: params.readonly,
		handleMapPoolChange,
	};
}

function MapListCreator({ mapPool }: { mapPool: MapPool }) {
	const { t } = useTranslation(["game-misc", "common"]);
	const [mapList, setMapList] = React.useState<ModeWithStage[]>();
	const [szEveryOther, setSzEveryOther] = React.useState(false);
	const { copyToClipboard, copySuccess } = useCopyToClipboard();

	const handleCreateMaplist = () => {
		const generator = MapList.generate({ mapPool });
		generator.next();

		const list = generator.next({
			amount: AMOUNT_OF_MAPS_IN_MAP_LIST,
			pattern: szEveryOther ? (Math.random() > 0.5 ? "SZ*" : "*SZ") : undefined,
		}).value;

		invariant(list);

		setMapList(list);
	};

	const disabled =
		mapPool.isEmpty() || (szEveryOther && !mapPool.hasMode("SZ"));

	return (
		<div className={styles.mapListCreator}>
			<div className={styles.toggleContainer}>
				<Label>{t("common:maps.halfSz")}</Label>
				<SendouSwitch isSelected={szEveryOther} onChange={setSzEveryOther} />
			</div>
			<SendouButton onClick={handleCreateMaplist} isDisabled={disabled}>
				{t("common:maps.createMapList")}
			</SendouButton>
			{mapList ? (
				<>
					<ol className={styles.mapList}>
						{mapList.map(({ mode, stageId }, i) => (
							<li key={i}>
								<abbr
									className={styles.modeAbbr}
									title={t(`game-misc:MODE_LONG_${mode}`)}
								>
									{t(`game-misc:MODE_SHORT_${mode}`)}
								</abbr>{" "}
								{t(`game-misc:STAGE_${stageId}`)}
							</li>
						))}
					</ol>
					<SendouButton
						size="small"
						variant="outlined"
						icon={copySuccess ? <Check /> : <Clipboard />}
						onClick={() =>
							copyToClipboard(
								mapList
									.map(
										({ mode, stageId }, i) =>
											`${i + 1}) ${t(`game-misc:MODE_SHORT_${mode}`)} ${t(
												`game-misc:STAGE_${stageId}`,
											)}`,
									)
									.join("\n"),
							)
						}
					>
						{t("common:actions.copyToClipboard")}
					</SendouButton>
				</>
			) : null}
		</div>
	);
}
