// app/form/fields/ArrayFormField.tsx
import type * as React from "react";
import { useTranslation } from "react-i18next";
import { SendouButton } from "~/components/elements/Button";
import { FormMessage } from "~/components/FormMessage";
import { PlusIcon } from "~/components/icons/Plus";
import { TrashIcon } from "~/components/icons/Trash";
import type { FormFieldProps } from "../types";
import styles from "./ArrayFormField.module.css";
import { useTranslatedTexts } from "./FormFieldWrapper";

type ArrayFormFieldProps = Omit<FormFieldProps<"array">, "field"> & {
	name: string;
	value: unknown[];
	onChange: (value: unknown[]) => void;
	renderItem: (index: number, name: string) => React.ReactNode;
	isObjectArray?: boolean;
	sortable?: boolean;
};

export function ArrayFormField({
	label,
	name,
	bottomText,
	error,
	min,
	max,
	value,
	onChange,
	renderItem,
	isObjectArray,
	sortable,
}: ArrayFormFieldProps) {
	const { t } = useTranslation(["common"]);
	const { translatedLabel, translatedBottomText, translatedError } =
		useTranslatedTexts({ label, bottomText, error });

	const count = value.length;

	const handleAdd = () => {
		onChange([...value, isObjectArray ? {} : undefined]);
	};

	const handleRemoveAt = (index: number) => {
		onChange(value.filter((_, i) => i !== index));
	};

	return (
		<div className="stack md w-full">
			{translatedLabel ? (
				<div
					style={{
						fontSize: "var(--fonts-xs)",
						fontWeight: "var(--semi-bold)",
					}}
				>
					{translatedLabel}
				</div>
			) : null}
			{Array.from({ length: count }).map((_, idx) =>
				isObjectArray ? (
					<ArrayItemFieldset
						key={idx}
						index={idx}
						canRemove={count > min}
						onRemove={() => handleRemoveAt(idx)}
						sortable={sortable}
					>
						{renderItem(idx, `${name}[${idx}]`)}
					</ArrayItemFieldset>
				) : (
					<div key={idx} className="stack horizontal sm items-center w-full">
						<div className={styles.itemInput}>
							{renderItem(idx, `${name}[${idx}]`)}
						</div>
						{count > min ? (
							<SendouButton
								icon={<TrashIcon />}
								aria-label="Remove item"
								size="small"
								variant="minimal-destructive"
								onPress={() => handleRemoveAt(idx)}
							/>
						) : null}
					</div>
				),
			)}
			{translatedError ? (
				<FormMessage type="error">{translatedError}</FormMessage>
			) : null}
			{translatedBottomText && !translatedError ? (
				<FormMessage type="info">{translatedBottomText}</FormMessage>
			) : null}
			<SendouButton
				size="small"
				icon={<PlusIcon />}
				onPress={handleAdd}
				isDisabled={count >= max}
				style={{ margin: "0 auto" }}
			>
				{t("common:actions.add")}
			</SendouButton>
		</div>
	);
}

function ArrayItemFieldset({
	index,
	children,
	canRemove,
	onRemove,
	sortable,
}: {
	index: number;
	children: React.ReactNode;
	canRemove: boolean;
	onRemove: () => void;
	sortable?: boolean;
}) {
	return (
		<fieldset className={styles.card}>
			<div className={styles.header}>
				{sortable ? <span className={styles.dragHandle}>☰</span> : null}
				<legend className={styles.headerLabel}>#{index + 1}</legend>
				{canRemove ? (
					<SendouButton
						icon={<TrashIcon />}
						aria-label="Remove item"
						size="small"
						variant="minimal-destructive"
						onPress={onRemove}
					/>
				) : null}
			</div>
			<div className={styles.content}>{children}</div>
		</fieldset>
	);
}

// src/lib/components/form/ArrayFormField.svelte
<script lang="ts">
	import type { FormFieldProps } from '$lib/form/types';
	import Button from '../buttons/Button.svelte';
	import BottomText from './BottomText.svelte';
	import FormField from './FormField.svelte';
	import Plus from '@lucide/svelte/icons/plus';
	import Minus from '@lucide/svelte/icons/minus';
	import { m } from '$lib/paraglide/messages';

	type Props = FormFieldProps<'array'> & {
		value: Array<unknown>;
	};

	let { label, name, bottomText, error, field, max, value = $bindable() }: Props = $props();
	const id = $props.id();

	let count = $state(value.length || 1);
</script>

<fieldset class="container stack md">
	<legend>
		{label}
	</legend>
	{#each { length: count }, idx}
		<FormField {field} name={`${name}[${idx}]`} label={`#${idx + 1}`} />
	{/each}
	<BottomText info={bottomText} {error} fieldId={id} />
	<div class="stack sm horizontal">
		<Button size="small" icon={Plus} onclick={() => count++} disabled={count >= max}
			>{m.common_actions_add()}</Button
		>
		<Button
			class={count === 1 ? 'invisible' : undefined}
			size="small"
			icon={Minus}
			variant="destructive"
			onclick={() => count--}>{m.common_actions_remove()}</Button
		>
	</div>
</fieldset>

<style>
	.container {
		:global {
			svg {
				stroke-width: 3px;
			}
		}
	}

	fieldset {
		border: var(--border-style);
		border-radius: var(--radius-field);
		background-color: var(--color-base-section);
	}

	legend {
		font-size: var(--fonts-xs);
		font-weight: var(--semi-bold);
	}
</style>
