// app/form/FormField.tsx
import * as React from "react";
import type { z } from "zod";
import type {
	MapPoolObject,
	ReadonlyMapPoolObject,
} from "~/features/map-list-generator/core/map-pool-serializer/types";
import { formRegistry } from "./fields";
import { ArrayFormField } from "./fields/ArrayFormField";
import { DatetimeFormField } from "./fields/DatetimeFormField";
import { DualSelectFormField } from "./fields/DualSelectFormField";
import { ImageFormField } from "./fields/ImageFormField";
import { InputFormField } from "./fields/InputFormField";
import {
	CheckboxGroupFormField,
	RadioGroupFormField,
} from "./fields/InputGroupFormField";
import { MapPoolFormField } from "./fields/MapPoolFormField";
import { MultiSelectFormField } from "./fields/MultiSelectFormField";
import { SelectFormField } from "./fields/SelectFormField";
import { SwitchFormField } from "./fields/SwitchFormField";
import { TextareaFormField } from "./fields/TextareaFormField";
import {
	WeaponPoolFormField,
	type WeaponPoolItem,
} from "./fields/WeaponPoolFormField";
import { useOptionalFormFieldContext } from "./SendouForm";
import type { FormField as FormFieldType } from "./types";
import { validateField } from "./utils";

interface FormFieldProps {
	name: string;
	label?: string;
	field?: z.ZodType;
	children?: (props: {
		name: string;
		error: string | undefined;
		value: unknown;
		onChange: (value: unknown) => void;
	}) => React.ReactNode;
}

export function FormField({ name, label, field, children }: FormFieldProps) {
	const context = useOptionalFormFieldContext();

	const fieldSchema = React.useMemo(() => {
		if (field) return field;
		if (!context?.schema) {
			throw new Error(
				"FormField requires either a 'field' prop or to be used within a FormProvider",
			);
		}

		const zodObject = context.schema;
		const result = zodObject.shape[name];

		if (!result) {
			throw new Error(
				`Field schema not found for name: ${name}. Does the schema have a corresponding key?`,
			);
		}
		return result;
	}, [field, context?.schema, name]);

	const formField = React.useMemo(() => {
		const result = formRegistry.get(fieldSchema) as FormFieldType | undefined;

		if (!result) {
			throw new Error(`Form field metadata not found for name: ${name}`);
		}

		const fieldWithLabel = label ? { ...result, label } : result;
		return fieldWithLabel as FormFieldType;
	}, [fieldSchema, name, label]);

	const value = context?.values[name] ?? formField.initialValue;

	const serverError =
		context?.serverErrors[name as keyof typeof context.serverErrors];
	const clientError = context?.clientErrors[name];
	const hasSubmitted = context?.hasSubmitted ?? false;

	const runValidation = (val: unknown) => {
		if (!context?.schema) return;
		const validationError = validateField(context.schema, name, val);
		context.setClientError(name, validationError);
	};

	const handleBlur = (latestValue?: unknown) => {
		if (hasSubmitted) return;
		runValidation(latestValue ?? value);
	};

	const handleChange = (newValue: unknown) => {
		context?.setValue(name, newValue);
		if (hasSubmitted && context) {
			const updatedValues = { ...context.values, [name]: newValue };
			context.revalidateAll(updatedValues);
		}
		context?.onFieldChange?.(name, newValue);
	};

	const displayedError = serverError ?? clientError;

	const commonProps = { name, error: displayedError, onBlur: handleBlur };

	if (formField.type === "text-field") {
		return (
			<InputFormField
				{...commonProps}
				{...formField}
				value={value as string}
				onChange={handleChange as (v: string) => void}
			/>
		);
	}

	if (formField.type === "switch") {
		return (
			<SwitchFormField
				{...commonProps}
				{...formField}
				checked={value as boolean}
				onChange={handleChange as (v: boolean) => void}
			/>
		);
	}

	if (formField.type === "text-area") {
		return (
			<TextareaFormField
				{...commonProps}
				{...formField}
				value={value as string}
				onChange={handleChange as (v: string) => void}
			/>
		);
	}

	if (formField.type === "select") {
		return (
			<SelectFormField
				{...commonProps}
				{...formField}
				value={value as string | null}
				onChange={handleChange as (v: string | null) => void}
			/>
		);
	}

	if (formField.type === "dual-select") {
		return (
			<DualSelectFormField
				{...commonProps}
				{...formField}
				value={value as [string | null, string | null]}
				onChange={handleChange as (v: [string | null, string | null]) => void}
			/>
		);
	}

	if (formField.type === "multi-select") {
		return (
			<MultiSelectFormField
				{...commonProps}
				{...formField}
				value={value as string[]}
				onChange={handleChange as (v: string[]) => void}
			/>
		);
	}

	if (formField.type === "radio-group") {
		return (
			<RadioGroupFormField
				{...commonProps}
				{...formField}
				value={value as string}
				onChange={handleChange as (v: string) => void}
			/>
		);
	}

	if (formField.type === "checkbox-group") {
		return (
			<CheckboxGroupFormField
				{...commonProps}
				{...formField}
				value={value as string[]}
				onChange={handleChange as (v: string[]) => void}
			/>
		);
	}

	if (formField.type === "datetime") {
		return (
			<DatetimeFormField
				{...commonProps}
				{...formField}
				value={value as Date | undefined}
				onChange={handleChange as (v: Date | undefined) => void}
			/>
		);
	}

	if (formField.type === "weapon-pool") {
		return (
			<WeaponPoolFormField
				{...commonProps}
				{...formField}
				value={value as WeaponPoolItem[]}
				onChange={handleChange as (v: WeaponPoolItem[]) => void}
			/>
		);
	}

	if (formField.type === "map-pool") {
		return (
			<MapPoolFormField
				{...commonProps}
				{...formField}
				value={value as MapPoolObject}
				onChange={handleChange as (v: ReadonlyMapPoolObject) => void}
			/>
		);
	}

	if (formField.type === "custom") {
		if (!children) {
			throw new Error("Custom form field requires children render function");
		}
		return (
			<>
				{children({
					name,
					error: displayedError,
					value,
					onChange: handleChange,
				})}
			</>
		);
	}

	if (formField.type === "image") {
		return (
			<ImageFormField
				{...commonProps}
				{...formField}
				value={value as File | string | null}
				onChange={handleChange as (v: File | string | null) => void}
			/>
		);
	}

	if (
		formField.type === "string-constant" ||
		formField.type === "id-constant"
	) {
		return null;
	}

	if (formField.type === "array") {
		return (
			<ArrayFormField
				{...commonProps}
				{...formField}
				value={value as unknown[]}
				onChange={handleChange as (v: unknown[]) => void}
				renderItem={(idx, itemName) => (
					<FormField key={idx} name={itemName} field={formField.field} />
				)}
			/>
		);
	}

	return (
		<div>Unsupported form field type: {(formField as FormFieldType).type}</div>
	);
}

// src/lib/components/form/FormField.svelte
<script lang="ts">
	import type { ZodObject, ZodRawShape } from 'zod';
	import type { FormField } from '$lib/form/types';
	import { formRegistry } from '$lib/form/fields';
	import { formContext, type FormContextValue } from './context';
	import WeaponPoolFormField, { type WeaponPool } from './WeaponPoolFormField.svelte';
	import InputFormField from './InputFormField.svelte';
	import SwitchFormField from './SwitchFormField.svelte';
	import TextareaFormField from './TextareaFormField.svelte';
	import SelectFormField from './SelectFormField.svelte';
	import DualSelectFormField from './DualSelectFormField.svelte';
	import type { Snippet } from 'svelte';
	import InputGroupFormField from './InputGroupFormField.svelte';
	import MapPoolFormField from './MapPoolFormField.svelte';
	import type { ModeShort } from '$lib/constants/in-game/types';
	import MultiSelectFormField from './MultiSelectFormField.svelte';
	import ImageFormField from '$lib/components/form/ImageFormField.svelte';
	import * as MapPool from '$lib/core/maps/MapPool';
	import { resolveDefaultValue } from '$lib/form/utils';
	import DatetimeFormField from './DatetimeFormField.svelte';
	import ArrayFormField from './ArrayFormField.svelte';

	interface Props {
		/** Name of the form field, should correspond to a key in the form schema if `field` was not provided. */
		name: string;
		/** The zod object containing form registry information. Used for array form fields. */
		field?: ZodObject<ZodRawShape>;
		label?: string;
		/** For map pool form field, what modes to pick for? */
		modes?: ModeShort[];
		children?: Snippet<
			[
				{
					label?: string;
					onblur: FormContextValue['onblur'];
					error: string | undefined;
					name: string;
					data: { value: unknown };
				}
			]
		>;
	}

	let { name, children, modes, field, label }: Props = $props();

	const { schema, defaultValues, errors, onblur } = formContext.get();

	const fieldSchema = (() => {
		if (field) return field;

		const zodObject = schema as ZodObject<ZodRawShape>;
		const result = zodObject.shape[name as string];

		if (!result) {
			throw new Error(
				`Field schema not found for name: ${String(name)}. Does the schema have a corresponding key to the name property of FormField?`
			);
		}
		return result;
	})();

	const formField = (() => {
		const result = formRegistry.get(fieldSchema) as FormField | undefined;

		if (!result) {
			throw new Error(`Form field not found for name: ${String(name)}`);
		}

		return label ? { ...result, label } : result;
	})();

	let data = $state({
		value:
			resolveDefaultValue({
				defaultValues,
				name
			}) ?? formField.initialValue
	});
	const error = $derived<string | undefined>(errors()[name as keyof typeof errors]);

	const commonProps = $derived({ name, error, onblur });
</script>

{#if formField.type === 'text-field'}
	<InputFormField bind:value={data.value as string} {...commonProps} {...formField} />
{:else if formField.type === 'switch'}
	<SwitchFormField bind:checked={data.value as boolean} {...commonProps} {...formField} />
{:else if formField.type === 'text-area'}
	<TextareaFormField bind:value={data.value as string} {...commonProps} {...formField} />
{:else if formField.type === 'select'}
	<SelectFormField bind:value={data.value as string} clearable {...commonProps} {...formField} />
{:else if formField.type === 'dual-select'}
	<DualSelectFormField
		bind:value={data.value as [string, string]}
		clearable
		{...commonProps}
		{...formField}
	/>
{:else if formField.type === 'multi-select'}
	<MultiSelectFormField bind:value={data.value as string[]} {...commonProps} {...formField} />
{:else if formField.type === 'radio-group'}
	<InputGroupFormField
		inputType="radio"
		bind:value={data.value as string}
		{...commonProps}
		{...formField}
	/>
{:else if formField.type === 'checkbox-group'}
	<InputGroupFormField
		inputType="checkbox"
		bind:value={data.value as string[]}
		{...commonProps}
		{...formField}
	/>
{:else if formField.type === 'datetime'}
	<DatetimeFormField bind:value={data.value as Date} {...commonProps} {...formField} />
{:else if formField.type === 'weapon-pool'}
	<WeaponPoolFormField bind:value={data.value as WeaponPool[]} {...commonProps} {...formField} />
{:else if formField.type === 'map-pool'}
	<MapPoolFormField
		bind:value={data.value as MapPool.MapPool}
		{modes}
		{...commonProps}
		{...formField}
	/>
{:else if formField.type === 'custom'}
	{@render children?.({ data, ...commonProps, ...formField })}
{:else if formField.type === 'image'}
	<ImageFormField bind:value={data.value as File} {...commonProps} {...formField} />
{:else if formField.type === 'string-constant'}
	<input type="hidden" {name} value={data.value} />
{:else if formField.type === 'id-constant'}
	<input type="hidden" {name} value={data.value} />
{:else if formField.type === 'array'}
	<ArrayFormField bind:value={data.value as string[]} {...commonProps} {...formField} />
{:else}
	<p>Unsupported form field type</p>
{/if}
