// app/form/fields/ImageFormField.tsx
import * as React from "react";
import { useTranslation } from "react-i18next";
import { SendouButton } from "~/components/elements/Button";
import { FormMessage } from "~/components/FormMessage";
import { TrashIcon } from "~/components/icons/Trash";
import { Label } from "~/components/Label";
import type { FormFieldProps } from "../types";

type ImageFormFieldProps = FormFieldProps<"image"> & {
	value: File | string | null;
	onChange: (value: File | string | null) => void;
};

export function ImageFormField({
	label,
	name,
	error,
	dimensions,
	value,
	onChange,
}: ImageFormFieldProps) {
	const { t } = useTranslation(["common"]);
	const id = React.useId();

	const { width, height } =
		dimensions === "logo"
			? { width: 400, height: 400 }
			: { width: 1000, height: 500 };

	const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
		const file = e.target.files?.[0];
		onChange(file ?? null);
	};

	const bottomText = `Recommended size is ${width}x${height}. Note that non-supporters need to wait for moderator validation before the image is shown to others.`;

	return (
		<div className="stack xs">
			{label ? <Label htmlFor={id}>{label}</Label> : null}
			{typeof value === "string" ? (
				<div className="stack md items-start">
					<img
						src={value}
						alt=""
						style={{
							width: width / 3,
							height: height / 3,
							borderRadius:
								dimensions === "logo" ? "100%" : "var(--radius-box)",
						}}
					/>
					<input type="hidden" name={name} value="" />
					<SendouButton
						size="miniscule"
						variant="destructive"
						icon={<TrashIcon />}
						onPress={() => onChange(null)}
					>
						{t("common:actions.delete")}
					</SendouButton>
				</div>
			) : (
				<input
					id={id}
					name={name}
					type="file"
					accept="image/webp"
					onChange={handleFileChange}
				/>
			)}
			{error ? <FormMessage type="error">{error}</FormMessage> : null}
			<FormMessage type="info">{bottomText}</FormMessage>
		</div>
	);
}

// src/lib/components/form/ImageFormField.svelte
<script lang="ts">
	import FileUpload from '$lib/components/FileUpload.svelte';
	import type { FormFieldProps } from '$lib/form/types';
	import { m } from '$lib/paraglide/messages';
	import { userSubmittedImage } from '$lib/utils/urls-img';
	import Button from '../buttons/Button.svelte';
	import BottomText from './BottomText.svelte';
	import Label from './Label.svelte';
	import Trash from '@lucide/svelte/icons/trash';

	type Props = FormFieldProps<'image'> & {
		value: File | string | null;
	};

	let { label, name, dimensions, value = $bindable() }: Props = $props();
	const id = $props.id();

	const { width, height } = $derived(
		dimensions === 'logo' ? { width: 400, height: 400 } : { width: 1000, height: 500 }
	);
</script>

<!--- xxx: when editing, show if validation is in progress -->

<div class="stack xs">
	<Label for={id}>
		{label}
	</Label>
	{#if typeof value === 'string'}
		<div class="stack md items-start">
			<img
				src={userSubmittedImage(value)}
				alt=""
				style="width: {width / 3}px; height: {height / 3}px; border-radius: {dimensions === 'logo'
					? '100%'
					: 'var(--radius-box)'};"
			/>
			<input type="hidden" {name} value="" />
			<Button size="miniscule" variant="destructive" icon={Trash} onclick={() => (value = null)}
				>{m.common_actions_delete()}</Button
			>
		</div>
	{:else}
		<FileUpload
			{name}
			bind:file={value}
			dimensions={{ width, height }}
			radius={dimensions === 'logo' ? 'round' : 'box'}
		/>
	{/if}
	<BottomText
		info={`Recommended size is ${width}x${height}. Note that non-supporters need to wait for moderator validation before the image is shown to others.`}
		fieldId={id}
	/>
</div>
