// app/form/fields/InputGroupFormField.tsx
import * as React from "react";
import { useTranslation } from "react-i18next";
import type { FormFieldItemsWithImage, FormFieldProps } from "../types";
import { FormFieldWrapper } from "./FormFieldWrapper";

type RadioGroupFormFieldProps<V extends string> = Omit<
	FormFieldProps<"radio-group">,
	"items"
> & {
	items: FormFieldItemsWithImage<V>;
	value: V;
	onChange: (value: V) => void;
	disabled?: boolean;
};

export function RadioGroupFormField<V extends string>({
	name,
	label,
	bottomText,
	items,
	error,
	onBlur,
	value,
	onChange,
	minLength,
	disabled,
}: RadioGroupFormFieldProps<V>) {
	const id = React.useId();

	const itemsWithLabels = useItemsWithResolvedLabels(items);

	const required = typeof minLength !== "number" || minLength > 0;

	return (
		<FormFieldWrapper
			id={id}
			name={name}
			label={label}
			required={required}
			error={error}
			bottomText={bottomText}
		>
			<div
				role="radiogroup"
				aria-orientation="vertical"
				aria-labelledby={id}
				className="stack sm items-start"
			>
				{itemsWithLabels.map((item) => (
					<div key={item.value} className="stack horizontal sm items-center">
						<input
							type="radio"
							id={`${id}-${item.value}`}
							name={id}
							value={item.value}
							checked={value === item.value}
							onChange={() => onChange(item.value)}
							onBlur={() => onBlur?.()}
							disabled={disabled}
						/>
						<label
							htmlFor={`${id}-${item.value}`}
							className="stack horizontal sm items-center mb-0 whitespace-nowrap"
						>
							{item.imgSrc ? (
								<img src={item.imgSrc} width={24} height={24} alt="" />
							) : null}
							{item.resolvedLabel}
						</label>
					</div>
				))}
			</div>
		</FormFieldWrapper>
	);
}

type CheckboxGroupFormFieldProps<V extends string> = Omit<
	FormFieldProps<"checkbox-group">,
	"items"
> & {
	items: FormFieldItemsWithImage<V>;
	value: V[];
	onChange: (value: V[]) => void;
	disabled?: boolean;
};

export function CheckboxGroupFormField<V extends string>({
	name,
	label,
	bottomText,
	items,
	error,
	onBlur,
	value,
	onChange,
	minLength,
	disabled,
}: CheckboxGroupFormFieldProps<V>) {
	const id = React.useId();

	const itemsWithLabels = useItemsWithResolvedLabels(items);

	const required = typeof minLength !== "number" || minLength > 0;

	const handleChange = (itemValue: V, checked: boolean) => {
		if (checked) {
			onChange([...value, itemValue]);
		} else {
			onChange(value.filter((v) => v !== itemValue));
		}
	};

	return (
		<FormFieldWrapper
			id={id}
			name={name}
			label={label}
			required={required}
			error={error}
			bottomText={bottomText}
		>
			<div className="stack sm items-start">
				{itemsWithLabels.map((item) => (
					<div key={item.value} className="stack horizontal sm items-center">
						<input
							type="checkbox"
							id={`${id}-${item.value}`}
							value={item.value}
							checked={value.includes(item.value)}
							onChange={(e) => handleChange(item.value, e.target.checked)}
							onClick={() => onBlur?.()}
							disabled={disabled}
						/>
						<label
							htmlFor={`${id}-${item.value}`}
							className="stack horizontal sm items-center mb-0 whitespace-nowrap"
						>
							{item.imgSrc ? (
								<img src={item.imgSrc} width={24} height={24} alt="" />
							) : null}
							{item.resolvedLabel}
						</label>
					</div>
				))}
			</div>
		</FormFieldWrapper>
	);
}

function useItemsWithResolvedLabels<V extends string>(
	items: FormFieldItemsWithImage<V>,
) {
	const { t, i18n } = useTranslation();

	return items.map((item) => {
		const itemLabel = item.label;
		const resolvedLabel =
			typeof itemLabel === "function"
				? itemLabel(i18n.language)
				: typeof itemLabel === "string" && itemLabel.includes(":")
					? t(itemLabel as never)
					: String(itemLabel);

		return {
			...item,
			resolvedLabel,
		};
	});
}

// src/lib/components/form/InputGroupFormField.svelte
<script lang="ts" generics="T extends 'radio' | 'checkbox'">
	import type { FormFieldProps } from '$lib/form/types';
	import BottomText from './BottomText.svelte';
	import Label from './Label.svelte';
	import { getLocale } from '$lib/paraglide/runtime';

	type Props = FormFieldProps<'radio-group'> & {
		value: T extends 'radio' ? string : string[];
		inputType: T;
	};

	let {
		label,
		name,
		bottomText,
		items,
		error,
		onblur, // xxx: better name for onblur? since here it is attached to onclick instead
		inputType,
		minLength,
		value = $bindable()
	}: Props = $props();
	const id = $props.id();

	const itemsWithLabels = $derived(
		items.map((item) => ({
			...item,
			label: typeof item.label === 'function' ? item.label(getLocale()) : item.label
		}))
	);
</script>

<div class="stack xs" role="radiogroup" aria-orientation="vertical" aria-labelledby={id}>
	<Label {id} required={typeof minLength !== 'number' || minLength > 0}>
		{label}
	</Label>
	{#each itemsWithLabels as item (item.label)}
		<div class="stack horizontal sm-plus items-center">
			<!-- some duplication here because when binding "type" has to be static according to Svelte rules -->
			{#if inputType === 'radio'}
				<input
					type="radio"
					bind:group={value}
					id={`${id}-${item.value}`}
					{name}
					value={item.value}
				/>
			{:else}
				<input
					type="checkbox"
					bind:group={value}
					id={`${id}-${item.value}`}
					name={`${name}[]`}
					value={item.value}
					onclick={onblur}
				/>
			{/if}
			<label for={`${id}-${item.value}`} class="stack horizontal sm items-center"
				>{#if item.imgSrc}
					<img src={item.imgSrc} width={24} height={24} alt="" />
				{/if}{item.label}</label
			>
		</div>
	{/each}
	<BottomText info={bottomText} {error} fieldId={id} />
</div>

<style>
	/** TODO: round focus styling */
	input {
		accent-color: var(--color-secondary);
		height: max-content;
		border-radius: 100%;
		margin: auto 0;

		&:focus-visible {
			outline: 2px solid var(--color-secondary);
		}
	}

	label {
		font-weight: var(--semi-bold);
		font-size: var(--fonts-sm);
	}
</style>
