// app/form/fields/MultiSelectFormField.tsx
import type { Key } from "react-aria-components";
import { useTranslation } from "react-i18next";
import { SendouButton } from "~/components/elements/Button";
import { SendouSelect, SendouSelectItem } from "~/components/elements/Select";
import { CrossIcon } from "~/components/icons/Cross";
import type { FormFieldItems, FormFieldProps } from "../types";
import { FormFieldMessages } from "./FormFieldWrapper";

type MultiSelectFormFieldProps<V extends string> = Omit<
	FormFieldProps<"multi-select">,
	"items" | "clearable"
> & {
	items: FormFieldItems<V>;
	value: V[];
	onChange: (value: V[]) => void;
};

export function MultiSelectFormField<V extends string>({
	label,
	name,
	bottomText,
	items,
	error,
	onBlur,
	value,
	onChange,
}: MultiSelectFormFieldProps<V>) {
	const { i18n } = useTranslation();

	const itemsWithResolvedLabels = items.map((item) => ({
		...item,
		id: item.value,
		resolvedLabel:
			typeof item.label === "function"
				? item.label(i18n.language)
				: String(item.label),
	}));

	const itemsPicked = value.map(
		(v) => itemsWithResolvedLabels.find((item) => item.value === v)!,
	);
	const itemsAvailable = itemsWithResolvedLabels.filter(
		(item) => !value.includes(item.value),
	);

	const handleSelect = (key: Key | null) => {
		if (!key) return;
		const selectedValue = key as V;
		onChange([...value, selectedValue]);
		onBlur?.();
	};

	const handleRemove = (itemValue: V) => {
		onChange(value.filter((v) => v !== itemValue));
	};

	return (
		<div className="stack xs">
			<div className="stack sm">
				<SendouSelect
					label={label}
					items={itemsAvailable}
					selectedKey={null}
					onSelectionChange={handleSelect}
					clearable
				>
					{(item) => (
						<SendouSelectItem
							key={item.id}
							id={item.id}
							textValue={item.resolvedLabel}
						>
							{item.resolvedLabel}
						</SendouSelectItem>
					)}
				</SendouSelect>
				{value.length > 0 ? (
					<ol
						className="stack horizontal sm"
						style={{ flexWrap: "wrap", padding: 0 }}
					>
						{itemsPicked.map((item, idx) => (
							<li
								key={item.value}
								// xxx: use CSS
								style={{
									listStyle: "none",
									fontSize: "var(--fonts-xs)",
									fontWeight: "var(--semi-bold)",
									backgroundColor: "var(--color-base-card)",
									padding: "var(--s-1) var(--s-2)",
									borderRadius: "var(--radius-field)",
									display: "flex",
									alignItems: "center",
									gap: "var(--s-2)",
								}}
							>
								{idx + 1}) {item.resolvedLabel}
								<SendouButton
									icon={<CrossIcon />}
									variant="minimal-destructive"
									size="miniscule"
									onPress={() => handleRemove(item.value)}
								/>
							</li>
						))}
					</ol>
				) : null}
				{value.length > 0 ? (
					<input type="hidden" name={name} value={JSON.stringify(value)} />
				) : null}
			</div>
			<FormFieldMessages error={error} bottomText={bottomText} />
		</div>
	);
}

// src/lib/components/form/MultiSelectFormField.svelte
<script lang="ts">
	import type { FormFieldProps } from '$lib/form/types';
	import { slide } from 'svelte/transition';
	import Button from '../buttons/Button.svelte';
	import BottomText from './BottomText.svelte';
	import SelectFormField from './SelectFormField.svelte';
	import X from '@lucide/svelte/icons/x';

	type Props = FormFieldProps<'multi-select'> & {
		value: string[];
	};

	let { name, bottomText, error, onblur, value = $bindable(), items, label }: Props = $props();
	const id = $props.id();

	let selectValue = $derived(null);

	const itemsPicked = $derived(value.map((v) => items.find((item) => item.value === v)!));
	const itemsAvailable = $derived(items.filter((item) => !value.includes(item.value)));
</script>

<div class="stack xs">
	<div class="stack sm">
		<div class="stack horizontal md">
			<SelectFormField
				{id}
				items={itemsAvailable}
				{label}
				{onblur}
				clearable
				bind:value={selectValue}
				onSelect={(selectedValue) => {
					value.push(selectedValue);
					selectValue = null;
				}}
			/>
		</div>
		{#if value.length > 0}
			<ol>
				{#each itemsPicked as item, idx (item.value)}
					<li in:slide={{ duration: 250 }}>
						{idx + 1}) {item.label}
						<Button
							icon={X}
							variant="minimal-destructive"
							size="small"
							onclick={() => {
								value = value.filter((v) => v !== item.value);
								selectValue = null;
							}}
						/>
					</li>
				{/each}
			</ol>
			<input type="hidden" {name} value={JSON.stringify(value)} />
		{/if}
	</div>
	<BottomText info={bottomText} {error} fieldId={id} />
</div>

<style>
	ol {
		display: flex;
		flex-direction: row;
		padding: 0;
		gap: var(--s-2);
		flex-wrap: wrap;
	}

	li {
		all: unset;
		font-size: var(--fonts-xs);
		font-weight: var(--semi-bold);
		background-color: var(--color-base-card);
		padding: var(--s-1) var(--s-2);
		border-radius: var(--radius-field);
		display: flex;
		align-items: center;
		gap: var(--s-2);

		:global(svg) {
			stroke-width: 4px;
		}
	}
</style>
