// app/form/fields/TextareaFormField.tsx
import * as React from "react";
import type { FormFieldProps } from "../types";
import { ariaAttributes } from "../utils";
import { FormFieldWrapper } from "./FormFieldWrapper";

type TextareaFormFieldProps = FormFieldProps<"text-area"> & {
	value: string;
	onChange: (value: string) => void;
};

export function TextareaFormField({
	name,
	label,
	bottomText,
	maxLength,
	error,
	onBlur,
	value,
	onChange,
}: TextareaFormFieldProps) {
	const id = React.useId();

	return (
		<FormFieldWrapper
			id={id}
			name={name}
			label={label}
			error={error}
			bottomText={bottomText}
			valueLimits={
				maxLength ? { current: value?.length ?? 0, max: maxLength } : undefined
			}
		>
			<textarea
				id={id}
				value={value}
				onChange={(e) => onChange(e.target.value)}
				onBlur={onBlur}
				{...ariaAttributes({
					id,
					bottomText,
					error,
				})}
			/>
		</FormFieldWrapper>
	);
}

// src/lib/components/form/TextareaFormField.svelte
<script lang="ts">
	import type { FormFieldProps } from '$lib/form/types';
	import Textarea from '../Textarea.svelte';
	import BottomText from './BottomText.svelte';
	import Label from './Label.svelte';
	import { ariaAttributes } from './utils';

	type Props = FormFieldProps<'text-area'> & {
		value?: string;
		onblur?: () => void;
	};

	let {
		label,
		name,
		bottomText,
		maxLength,
		error,
		onblur,
		value = $bindable('')
	}: Props = $props();
	const id = $props.id();
</script>

<div>
	<Label for={id} withMargin valueLimits={{ current: value.length, max: maxLength }}>
		{label}
	</Label>
	<Textarea
		{name}
		{id}
		{onblur}
		bind:value
		{...ariaAttributes({
			id,
			bottomText,
			error
		})}
	/>
	<BottomText info={bottomText} {error} fieldId={id} />
</div>
