// apps/web/src/lib/components/match-page/MatchBannerTopRow.svelte
<script lang="ts">
import type { Snippet } from "svelte";
import { m } from "#lib/paraglide/messages.js";

interface Score {
	alpha: number;
	bravo: number;
	isFinal: boolean;
	count?: number;
	bestOf?: boolean;
}

interface Props {
	score?: Score;
	children?: Snippet;
}

let { score, children }: Props = $props();
</script>

<div class="root">
	{#if score}
		{@render scoreDisplay(score)}
	{:else}
		<div></div>
	{/if}
	{@render children?.()}
</div>

{#snippet scoreDisplay(score: Score)}
	<div class="values">
		<div>
			{score.alpha}-{score.bravo}
		</div>
		<div class="sub" data-testid={score.isFinal ? "match-final" : undefined}>
			{#if score.isFinal}
				{m.q_match_banner_final()}
			{:else if score.count !== undefined}
				{score.bestOf
					? m.q_match_banner_bestOf({ count: score.count })
					: m.q_match_banner_playAll({ count: score.count })}
			{/if}
		</div>
	</div>
{/snippet}

<style>
	.root {
		display: flex;
		justify-content: space-between;
		padding-inline: var(--s-1-5);
	}

	.values {
		display: flex;
		gap: var(--s-2);
		font-weight: var(--weight-semi);
	}

	.sub {
		color: var(--color-text-high);
	}
</style>

// app/components/match-page/MatchBannerTopRow.tsx
import { useTranslation } from "react-i18next";
import styles from "./MatchBannerTopRow.module.css";

interface MatchBannerTopRowProps {
	score?: {
		alpha: number;
		bravo: number;
		isFinal: boolean;
		count?: number;
		bestOf?: boolean;
	};
	children?: React.ReactNode;
}

export function MatchBannerTopRow({ score, children }: MatchBannerTopRowProps) {
	return (
		<div className={styles.root}>
			{score ? <Score score={score} /> : <div />}
			{children}
		</div>
	);
}

function Score({
	score,
}: {
	score: NonNullable<MatchBannerTopRowProps["score"]>;
}) {
	const { t } = useTranslation(["q"]);

	return (
		<div className={styles.values}>
			<div>
				{score.alpha}-{score.bravo}
			</div>
			<div
				className={styles.sub}
				data-testid={score.isFinal ? "match-final" : undefined}
			>
				{score.isFinal
					? t("q:match.banner.final")
					: score.count !== undefined
						? score.bestOf
							? t("q:match.banner.bestOf", { count: score.count })
							: t("q:match.banner.playAll", { count: score.count })
						: null}
			</div>
		</div>
	);
}
