// apps/web/src/lib/features/user-page/components/UserCard.svelte
<script lang="ts">
import {
	BadgeCheck,
	Flag,
	Megaphone,
	NotebookPen,
	NotebookText,
	Pencil,
	Trash2,
	UserPlus,
	UserRoundCheck,
	VenetianMask,
} from "@lucide/svelte";
import { Button, LinkButton, Popover } from "@sendou/components";
import type { BrandId } from "@sendou/in-game-lists/types";
import { assertUnreachable } from "@sendou/utils/types";
import type { Snippet } from "svelte";
import Avatar from "#lib/components/Avatar.svelte";
import Image from "#lib/components/Image.svelte";
import LocaleTime from "#lib/components/LocaleTime.svelte";
import NoteAvatar from "#lib/components/NoteAvatar.svelte";
import Placement from "#lib/components/Placement.svelte";
import TierImage from "#lib/components/TierImage.svelte";
import type { XRankPlacementRegion } from "#lib/db/tables-json.ts";
import { loggedInUser } from "#lib/features/auth/user-state.ts";
import { getUserCardContext } from "#lib/features/user-page/user-card-context.ts";
import type {
	UserCardData,
	UserCardFriendship,
	UserCardStat,
} from "#lib/features/user-page/user-card-types.ts";
import { getUserCardFriendship } from "#lib/features/user-page/user-card.remote.ts";
import { m } from "#lib/paraglide/messages.js";
import {
	brandImageUrl,
	impersonateUrl,
	lfgPostPage,
	navIconUrl,
	stageBannerImageUrl,
	userCardEditPage,
	userPage,
} from "#lib/utils/urls.ts";
import { dev } from "$app/env";
import { page } from "$app/state";
import MutualFriends from "./MutualFriends.svelte";

const TENTATEK_BRAND_ID: BrandId = "B10";

const STAT_ORDER: Record<UserCardStat["type"], number> = {
	XP: 0,
	SEASON: 1,
	PLUS: 2,
	DIV: 3,
};

interface Props {
	userId?: number;
	data?: UserCardData;
	/** Fetch and show the mutual friends row. Off by default. */
	withMutualFriends?: boolean;
	children: Snippet;
}

let {
	userId,
	data: dataProp,
	withMutualFriends = false,
	children,
}: Props = $props();

const context = getUserCardContext();

const data = $derived(
	dataProp ??
		(typeof userId === "number"
			? context?.userCards()?.get(userId)
			: undefined),
);

const isOwnCard = $derived(loggedInUser()?.id === data?.id);
const returnTo = $derived(`${page.url.pathname}${page.url.search}`);

const stats = $derived(
	data
		? data.stats.toSorted((a, b) => STAT_ORDER[a.type] - STAT_ORDER[b.type])
		: [],
);

let isOpen = $state(false);
// an existing note shows in-place (toggled); with no note the button opens the add modal directly
let isNoteOpen = $state(false);

let friendship = $state<UserCardFriendship | undefined>();
let friendshipRequested = false;

const showNoteView = $derived(isNoteOpen && data?.privateNote != null);

function handleOpenChange(nextIsOpen: boolean) {
	isOpen = nextIsOpen;

	if (!nextIsOpen) return;
	if (friendshipRequested) return;
	if (isOwnCard) return;
	const targetUserId = data?.id;
	if (typeof targetUserId !== "number") return;

	friendshipRequested = true;
	getUserCardFriendship({ userId: targetUserId, withMutualFriends })
		.then((result) => {
			friendship = result;
		})
		.catch(() => {
			// on failure the card just renders without the viewer-relative rows
		});
}

function onNoteButtonPress() {
	if (!data) return;
	if (data.privateNote === null) {
		// xxx: AddPrivateNoteDialog is not ported yet (depends on the unported SendouForm/dialog system)
		return;
	}
	isNoteOpen = !isNoteOpen;
}

function onEditNotePress() {
	// xxx: AddPrivateNoteDialog is not ported yet (depends on the unported SendouForm/dialog system)
}

function onDeleteNotePress() {
	// xxx: delete-note confirm dialog (FormWithConfirm) + the private note write path are not ported yet
}

function onReportPress() {
	// xxx: ReportUserDialog (user-report feature) is not ported yet
}

function onFriendRequestPress() {
	// xxx: friend request send/accept (the /friends write path + success toasts) is not ported yet
}

function bannerStyle(banner: UserCardData["banner"]) {
	switch (banner.type) {
		case "STAGE":
			return `background-image: url(${stageBannerImageUrl(banner.stageId)})`;
		case "URL":
			return `background-image: url(${banner.url})`;
		case "COLOR":
			return `background-color: ${banner.hexCode}`;
		default:
			return assertUnreachable(banner);
	}
}

function customThemeStyle(customTheme: UserCardData["customTheme"]) {
	if (!customTheme) return undefined;

	return Object.entries(customTheme)
		.filter(
			([key, value]) =>
				value !== null && !key.includes("--_size") && !key.includes("--_border"),
		)
		.map(([key, value]) => `${key}: ${value}`)
		.join("; ");
}
</script>

<!--
@component
Click-to-open trigger that shows a popover with the user's card. Card data is resolved by `userId`
from the {@link UserCardContext} (set by pages whose queries spread `{ userCards }` from
`UserCardRepository.findAllByUserIds`); pass `data` directly to bypass the lookup. When no card data
exists for the user, the `children` are rendered plain without a trigger.

Viewer-relative friendship data (`isFriend`) is lazy-loaded via the `getUserCardFriendship` remote
query the first time the card opens. Mutual friends are only fetched and shown when
`withMutualFriends` is set (e.g. the SendouQ looking page); other views (e.g. match pages) skip
both the extra query and the row.
-->

{#snippet divImage(region: XRankPlacementRegion)}
	{#if region === "WEST"}
		<Image
			path={brandImageUrl(TENTATEK_BRAND_ID)}
			alt={m.common_divisions_WEST()}
			width={18}
			height={18}
		/>
	{/if}
{/snippet}

{#snippet statView(stat: UserCardStat)}
	{#if stat.type === "XP"}
		{@const unverified = stat.values.find((value) => !value.isVerified)}
		{@const verified = stat.values.find((value) => value.isVerified)}
		{@const primary = unverified ?? verified}
		{@const secondary = unverified ? verified : undefined}
		<span class="stat xpStat">
			{#if primary}
				<span class="xpPrimary">
					<span class="xpPrimaryIcons"
						>{#if primary.isVerified}<BadgeCheck
								class={primary.region === "WEST"
									? "xpVerifiedIconSmall"
									: "xpVerifiedIconLarge"}
							/>{/if}{@render divImage(primary.region)}</span
					>
					{primary.points}{m.user_card_xp()}
				</span>
			{/if}
			{#if secondary}
				<span class="xpVerified">
					<BadgeCheck class="xpVerifiedIconSmall" />
					{@render divImage(secondary.region)}
					{secondary.points}{m.user_card_xp()}
				</span>
			{/if}
		</span>
	{:else if stat.type === "DIV"}
		<span class="stat">Div {stat.value}</span>
	{:else if stat.type === "PLUS"}
		<span class="stat plusStat">
			<Image path={navIconUrl("plus")} alt="+" size={24} />
			{stat.value}
		</span>
	{:else if stat.type === "SEASON"}
		<span class="seasonStat">
			<TierImage tier={stat.value} width={32} />
			{#if typeof stat.top === "number"}
				<span class="seasonTop">
					<Placement
						placement={stat.top}
						size={14}
						showAsSuperscript={false}
						textOnly
					/>
				</span>
			{/if}
		</span>
	{/if}
{/snippet}

{#snippet friendRequestButton(friendshipData: UserCardFriendship)}
	{#if friendshipData.incomingFriendRequestId !== null}
		<Button
			size="miniscule"
			shape="circle"
			aria-label="Accept friend request"
			onclick={onFriendRequestPress}
		>
			{#snippet icon()}<UserPlus />{/snippet}
		</Button>
	{:else if friendshipData.sentFriendRequest}
		<Button
			size="miniscule"
			shape="circle"
			disabled
			aria-label={m.user_card_friendRequestPending()}
		>
			{#snippet icon()}<UserRoundCheck />{/snippet}
		</Button>
	{:else}
		<Button
			size="miniscule"
			shape="circle"
			aria-label={m.user_card_sendFriendRequest()}
			onclick={onFriendRequestPress}
		>
			{#snippet icon()}<UserPlus />{/snippet}
		</Button>
	{/if}
{/snippet}

{#snippet noteView(note: NonNullable<UserCardData["privateNote"]>)}
	<div class="noteView">
		<div class="noteHeaderGroup">
			<span class="noteHeader">{m.user_card_privateNote()}</span>
			<LocaleTime
				date={note.updatedAt}
				options={{ day: "numeric", month: "numeric", year: "numeric" }}
				class="noteDate"
				inline
			/>
		</div>
		{#if note.text}
			<p class="noteText">{note.text}</p>
		{/if}
		<div class="noteViewActions">
			<Button variant="minimal" size="miniscule" onclick={onEditNotePress}>
				{#snippet icon()}<Pencil />{/snippet}
				{m.common_actions_edit()}
			</Button>
			<Button
				variant="minimal-destructive"
				size="miniscule"
				onclick={onDeleteNotePress}
			>
				{#snippet icon()}<Trash2 />{/snippet}
				{m.common_actions_delete()}
			</Button>
		</div>
	</div>
{/snippet}

{#if !data}
	{@render children()}
{:else}
	<Popover
		{isOpen}
		onOpenChange={handleOpenChange}
		popoverClass="userCardPopover"
	>
		{#snippet trigger(triggerProps)}
			<button type="button" class="trigger" {...triggerProps}>
				{@render children()}
			</button>
		{/snippet}
		<div
			class="card"
			style={customThemeStyle(data.customTheme)}
			data-custom-theme={data.customTheme ? true : undefined}
		>
			<div
				class="banner"
				style={bannerStyle(data.banner)}
				data-testid="user-card-banner"
			></div>
			{#if data.freeAgentPostId !== null}
				<LinkButton
					href={lfgPostPage(data.freeAgentPostId)}
					size="miniscule"
					class="freeAgentBadge"
				>
					{#snippet icon()}<Megaphone />{/snippet}
					{m.user_card_freeAgent()}
				</LinkButton>
			{/if}
			<div class="iconButtons">
				{#if isOwnCard}
					<LinkButton href={userCardEditPage({ returnTo })} size="miniscule">
						{#snippet icon()}<Pencil />{/snippet}
						{m.common_actions_edit()}
					</LinkButton>
				{:else}
					{#if dev}
						<form method="post" action={impersonateUrl(data.id)}>
							<input type="hidden" name="returnTo" value={returnTo} />
							<Button
								type="submit"
								size="miniscule"
								shape="circle"
								aria-label="Impersonate user"
							>
								{#snippet icon()}<VenetianMask />{/snippet}
							</Button>
						</form>
					{/if}
					{#if friendship && !friendship.isFriend}
						{@render friendRequestButton(friendship)}
					{/if}
					<Button
						size="miniscule"
						shape="circle"
						onclick={onNoteButtonPress}
						aria-label={m.user_card_editPrivateNote()}
					>
						{#snippet icon()}
							{#if data.privateNote !== null}
								<NotebookText />
							{:else}
								<NotebookPen />
							{/if}
						{/snippet}
					</Button>
					{#if loggedInUser()}
						<Button
							size="miniscule"
							shape="circle"
							onclick={onReportPress}
							aria-label="Report user"
							testId="report-user-button"
						>
							{#snippet icon()}<Flag />{/snippet}
						</Button>
					{/if}
				{/if}
			</div>
			<div class="identity">
				<NoteAvatar
					sentiment={data.privateNote?.sentiment}
					onclick={isOwnCard ? undefined : onNoteButtonPress}
				>
					<Avatar user={data} size="md" class="avatar" />
				</NoteAvatar>
				<div class="nameGroup">
					<h2 class="username">{data.username}</h2>
					{#if data.customUrl}
						<div class="subtitle">{data.customUrl}</div>
					{/if}
					{#if data.friendCode}
						<span class="friendCode">SW-{data.friendCode}</span>
					{:else}
						<!-- reserve space -->
						<span class="friendCode">{"\u{200b}"}</span>
					{/if}
				</div>
			</div>
			{#if showNoteView && data.privateNote}
				{@render noteView(data.privateNote)}
			{:else}
				{#if stats.length > 0}
					<div class="stats">
						{#each stats as stat, i (stat.type)}
							{#if i > 0}<span class="statDivider"></span>{/if}
							{@render statView(stat)}
						{/each}
					</div>
				{/if}
				{#if !isOwnCard && withMutualFriends}
					<div class="mutualFriends">
						{#if friendship !== undefined}
							{#if friendship.mutualFriends.length === 0}
								<span class="noMutualFriends"
									>{m.user_card_noMutualFriends()}</span
								>
							{:else}
								<MutualFriends mutualFriends={friendship.mutualFriends} />
							{/if}
						{/if}
					</div>
				{/if}
				{#if data.shortBio}
					<p class="bio">{data.shortBio}</p>
				{/if}
				<LinkButton
					href={userPage(data)}
					variant="outlined"
					size="small"
					class="viewUserPage"
				>
					{m.user_card_viewUserPage()}
				</LinkButton>
			{/if}
		</div>
	</Popover>
{/if}

<style>
	/* class is repeated to out-specify the base `.content` styles scoped inside Popover.svelte */
	:global(.userCardPopover.userCardPopover.userCardPopover) {
		border: none;
		background: none;
		padding: 0;
		max-width: none;
		white-space: normal;
		font-size: var(--font-sm);
		font-weight: var(--weight-body);
	}

	/* beside the trigger there is no room for the card on a narrow viewport, so it is placed
	vertically there (the base block-end position) and to the right on wider viewports */
	@media (min-width: 600px) {
		:global(.userCardPopover.userCardPopover.userCardPopover) {
			position-area: inline-end;
			position-try-fallbacks: flip-inline, block-end;
			align-self: anchor-center;
			justify-self: normal;
		}
	}

	.trigger {
		display: inline-flex;
		width: fit-content;
		padding: 0;
		margin: 0;
		border: none;
		background: none;
		color: inherit;
		font: inherit;
		text-align: inherit;
		cursor: pointer;
	}

	.card {
		position: relative;
		display: flex;
		flex-direction: column;
		gap: var(--s-5);
		width: 18rem;
		max-width: calc(100vw - var(--s-4));
		padding: 0 var(--s-4) var(--s-4);
		background-color: var(--color-bg);
		border: 1px solid var(--color-border);
		border-radius: var(--radius-box);
		overflow: hidden;

		& :global(.freeAgentBadge) {
			position: absolute;
			top: var(--s-2);
			inset-inline-start: var(--s-2);
		}

		& :global(.viewUserPage) {
			margin-top: var(--s-1);
			align-self: center;
		}

		& :global(.xpVerifiedIconSmall) {
			width: var(--s-4);
			height: var(--s-4);
			color: var(--color-success);
		}

		& :global(.xpVerifiedIconLarge) {
			width: var(--s-5);
			height: var(--s-5);
			color: var(--color-success);
		}
	}

	.banner {
		height: 6rem;
		margin-inline: calc(-1 * var(--s-4));
		background-size: cover;
		background-position: center;
		background-color: var(--color-bg-higher);
	}

	.iconButtons {
		position: absolute;
		top: var(--s-2);
		inset-inline-end: var(--s-2);
		display: flex;
		gap: var(--s-2);
	}

	.identity {
		display: flex;
		align-items: flex-end;
		gap: var(--s-2-5);
		margin-top: calc(-1 * (var(--s-8)));
		position: relative;

		& :global(.avatar) {
			border: 3px solid var(--color-bg);
			margin-block-end: -3px;
		}
	}

	.nameGroup {
		display: flex;
		flex-direction: column;
		padding-bottom: var(--s-6);
		position: absolute;
		top: 18px;
		inset-inline-start: 92px;
	}

	.username {
		font-size: var(--font-lg);
		font-weight: var(--weight-bold);
		line-height: 1.1;
		max-width: 170px;
		text-overflow: ellipsis;
		white-space: nowrap;
		overflow: hidden;
	}

	.subtitle {
		max-width: 170px;
		font-size: var(--font-xs);
		color: var(--color-text-high);
		text-overflow: ellipsis;
		white-space: nowrap;
		overflow: hidden;
	}

	.friendCode {
		font-size: var(--font-xs);
		color: var(--color-text-high);
	}

	.stats {
		display: flex;
		align-items: center;
		justify-content: center;
		gap: var(--s-2-5);
		font-weight: var(--weight-bold);
	}

	.stat {
		white-space: nowrap;
		flex-shrink: 0;
	}

	.plusStat {
		display: inline-flex;
		align-items: center;
		gap: var(--s-1);
	}

	.xpStat {
		display: inline-flex;
		flex-direction: column;
		align-items: flex-end;
		line-height: 1.1;
	}

	.xpPrimary {
		display: inline-flex;
		align-items: center;
		gap: var(--s-1);
	}

	.xpPrimaryIcons {
		display: inline-flex;
		flex-direction: column;
		align-items: center;

		&:empty {
			display: none;
		}
	}

	.xpVerified {
		display: inline-flex;
		align-items: center;
		gap: var(--s-1);
		font-size: var(--font-2xs);
		color: var(--color-text-high);
	}

	.seasonStat {
		position: relative;
		display: inline-flex;
		flex-shrink: 0;
	}

	.seasonTop {
		position: absolute;
		bottom: calc(-1 * var(--s-1));
		left: 50%;
		transform: translateX(-50%);
		display: inline-flex;
		align-items: center;
		padding: 0 var(--s-1);
		border: 1px solid var(--color-border);
		border-radius: var(--radius-full);
		background-color: var(--color-bg);
		font-size: var(--font-2xs);
		font-weight: var(--weight-bold);
		line-height: 1;
	}

	.statDivider {
		width: 2px;
		min-width: 2px;
		align-self: stretch;
		background-color: var(--color-border);
	}

	.mutualFriends {
		display: flex;
		align-items: center;
		min-height: var(--field-size-sm);
	}

	.noMutualFriends {
		margin-inline: auto;
		font-style: italic;
		font-size: var(--font-xs);
		color: var(--color-text-high);
	}

	.bio {
		font-size: var(--font-xs);
		color: var(--color-text);
		display: -webkit-box;
		-webkit-line-clamp: 2;
		line-clamp: 2;
		-webkit-box-orient: vertical;
		overflow: hidden;
	}

	.noteView {
		display: flex;
		flex-direction: column;
		gap: var(--s-2);
	}

	.noteHeaderGroup {
		display: flex;
		flex-direction: column;
		gap: var(--s-0-5);

		& :global(.noteDate) {
			font-size: var(--font-2xs);
			color: var(--color-text-high);
		}
	}

	.noteHeader {
		font-size: var(--font-xs);
		font-weight: var(--weight-bold);
		color: var(--color-text);
	}

	.noteText {
		font-size: var(--font-xs);
		color: var(--color-text);
		white-space: pre-wrap;
		overflow-wrap: anywhere;
	}

	.noteViewActions {
		margin-block-start: var(--s-2);
		display: flex;
		align-items: center;
		justify-content: center;
		gap: var(--s-4);
	}
</style>

// apps/web-react/app/features/user-card/components/UserCard.tsx
import type { BrandId } from "@sendou/in-game-lists/types";
import clsx from "clsx";
import {
	BadgeCheck,
	Flag,
	Megaphone,
	NotebookPen,
	NotebookText,
	Pencil,
	Trash2,
	UserPlus,
	UserRoundCheck,
	VenetianMask,
} from "lucide-react";
import * as React from "react";
import { Button, Dialog, DialogTrigger, Popover } from "react-aria-components";
import { useTranslation } from "react-i18next";
import { Form, useFetcher, useLocation, useMatches } from "react-router";
import * as R from "remeda";
import { Avatar } from "~/components/Avatar";
import { LinkButton, SendouButton } from "~/components/elements/Button";
import { toastQueue } from "~/components/elements/Toast";
import { FormWithConfirm } from "~/components/FormWithConfirm";
import { Image, TierImage } from "~/components/Image";
import { LocaleTime } from "~/components/LocaleTime";
import { NoteAvatar } from "~/components/NoteAvatar";
import { Placement } from "~/components/Placement";
import { useUser } from "~/features/auth/core/user";
import {
	acceptFriendRequestSchema,
	sendFriendRequestBaseSchema,
} from "~/features/friends/friends-schemas";
import { lfgSearchParams } from "~/features/lfg/lfg-search-params";
import type { XRankPlacementRegion } from "~/features/top-search/top-search-types";
import { userCardEditPage } from "~/features/user-card/user-card-urls";
import { MutualFriends } from "~/features/user-page/components/MutualFriends";
import { ReportUserDialog } from "~/features/user-report/components/ReportUserDialog";
import { useActionSubmit } from "~/hooks/useActionSubmit";
import { useLayoutSize } from "~/hooks/useMainContentWidth";
import { assertUnreachable } from "~/utils/types";
import {
	brandImageUrl,
	FRIENDS_PAGE,
	impersonateUrl,
	LFG_PAGE,
	navIconUrl,
	stageBannerImageUrl,
	userCardFriendshipPage,
	userCardNotePage,
	userPage,
} from "~/utils/urls";
import type { UserCardFriendshipLoaderData } from "../routes/user-card.$id.friendship";
import { userCardFriendshipSearchParams } from "../user-card-search-params";
import type {
	UserCardData,
	UserCardFriendship,
	UserCardStat,
} from "../user-card-types";
import { AddPrivateNoteDialog } from "./AddPrivateNoteDialog";
import styles from "./UserCard.module.css";

const TENTATEK_BRAND_ID: BrandId = "B10";

const STAT_ORDER: Record<UserCardStat["type"], number> = {
	XP: 0,
	SEASON: 1,
	PLUS: 2,
	DIV: 3,
};

/**
 * Click-to-open trigger that shows a popover with the user's card. Card data is resolved from the
 * route tree by `userId` (a parent loader spreads `{ userCards }` from `UserCardRepository.findAllByUserIds`);
 * pass `data` directly to bypass the lookup (e.g. the components showcase). When no card data exists
 * for the user, the `children` are rendered plain without a trigger.
 *
 * Viewer-relative friendship data (`isFriend`) is lazy-loaded from the `/user-card/:id/friendship`
 * route the first time the card opens. Mutual friends are only fetched and shown when
 * `withMutualFriends` is set (e.g. the SendouQ looking page); other views (e.g. match pages) skip
 * both the extra query and the row.
 */
export function UserCard({
	userId,
	data: dataProp,
	withMutualFriends = false,
	children,
}: {
	userId?: number;
	data?: UserCardData;
	/** Fetch and show the mutual friends row. Off by default. */
	withMutualFriends?: boolean;
	children: React.ReactNode;
}) {
	const { t } = useTranslation(["common", "q"]);
	const lookedUpData = useUserCardData(userId);
	const data = dataProp ?? lookedUpData;

	// beside the trigger there is no room for the card on a narrow viewport, so it is placed
	// vertically instead where React Aria can shift it horizontally to keep it on-screen
	const placement = useLayoutSize() === "mobile" ? "bottom" : "right";

	const user = useUser();
	const isOwnCard = user?.id === data?.id;

	const [isOpen, setIsOpen] = React.useState(false);
	// kept at this level (outside the popover) so the modals survive the popover closing when they
	// take focus; the note view inside the card opens them
	const [isNoteDialogOpen, setIsNoteDialogOpen] = React.useState(false);
	const [isDeleteConfirmOpen, setIsDeleteConfirmOpen] = React.useState(false);
	const [isReportDialogOpen, setIsReportDialogOpen] = React.useState(false);

	const fetcher = useFetcher<UserCardFriendshipLoaderData>();
	const friendshipLoadedRef = React.useRef(false);

	const handleOpenChange = (nextIsOpen: boolean) => {
		setIsOpen(nextIsOpen);

		if (!nextIsOpen) return;
		if (friendshipLoadedRef.current) return;
		if (isOwnCard) return;
		if (typeof data?.id !== "number") return;

		friendshipLoadedRef.current = true;
		fetcher.load(
			userCardFriendshipSearchParams.href(userCardFriendshipPage(data.id), {
				mutuals: withMutualFriends,
			}),
		);
	};

	const friendship = fetcher.data;

	// close the popover so only the modal is shown
	const openNoteDialog = () => {
		setIsOpen(false);
		setIsNoteDialogOpen(true);
	};

	const openDeleteConfirm = () => {
		setIsOpen(false);
		setIsDeleteConfirmOpen(true);
	};

	const openReportDialog = () => {
		setIsOpen(false);
		setIsReportDialogOpen(true);
	};

	if (!data) return <>{children}</>;

	return (
		<>
			<DialogTrigger isOpen={isOpen} onOpenChange={handleOpenChange}>
				<Button className={styles.trigger}>{children}</Button>
				<Popover placement={placement} className={styles.popover}>
					<Dialog className={styles.dialog}>
						<CardContent
							data={data}
							friendship={friendship}
							isOwnCard={isOwnCard}
							withMutualFriends={withMutualFriends}
							onEditNote={openNoteDialog}
							onDeleteNote={openDeleteConfirm}
							onReport={user ? openReportDialog : undefined}
						/>
					</Dialog>
				</Popover>
			</DialogTrigger>
			{isNoteDialogOpen ? (
				<AddPrivateNoteDialog
					userId={data.id}
					username={data.username}
					note={data.privateNote}
					onClose={() => setIsNoteDialogOpen(false)}
				/>
			) : null}
			{isReportDialogOpen ? (
				<ReportUserDialog
					userId={data.id}
					username={data.username}
					onClose={() => setIsReportDialogOpen(false)}
				/>
			) : null}
			<FormWithConfirm
				isOpen={isDeleteConfirmOpen}
				onOpenChange={setIsDeleteConfirmOpen}
				action={userCardNotePage(data.id)}
				fields={[["_action", "DELETE"]]}
				dialogHeading={t("q:privateNote.delete.header", {
					name: data.username,
				})}
				submitButtonText={t("common:actions.delete")}
			/>
		</>
	);
}

/**
 * Resolves a user's `UserCardData` from any matched route loader that spread `{ userCards }`
 * (see `UserCardRepository.findAllByUserIds`). Returns `undefined` when no loader on the current route
 * tree carries data for the given user.
 */
export function useUserCardData(
	userId: number | undefined,
): UserCardData | undefined {
	const matches = useMatches();

	if (typeof userId !== "number") return undefined;

	for (const match of matches) {
		const data = match.loaderData as
			| { userCards?: Map<number, UserCardData> }
			| undefined;
		const card = data?.userCards?.get(userId);
		if (card) return card;
	}

	return undefined;
}

function CardContent({
	data,
	friendship,
	isOwnCard,
	withMutualFriends,
	onEditNote,
	onDeleteNote,
	onReport,
}: {
	data: UserCardData;
	/** Lazy-loaded; `undefined` while the friendship fetch is in flight. */
	friendship: UserCardFriendship | undefined;
	isOwnCard: boolean;
	withMutualFriends: boolean;
	onEditNote: () => void;
	onDeleteNote: () => void;
	/** Not passed for logged-out viewers, hiding the report button. */
	onReport: (() => void) | undefined;
}) {
	const { t } = useTranslation(["common", "user"]);
	const location = useLocation();

	const [isNoteOpen, setIsNoteOpen] = React.useState(false);

	const stats = data.stats.toSorted(
		(a, b) => STAT_ORDER[a.type] - STAT_ORDER[b.type],
	);

	const editPageUrl = userCardEditPage({
		returnTo: `${location.pathname}${location.search}`,
	});

	// an existing note shows in-place (toggled); with no note the button opens the add modal directly
	const showNoteView = isNoteOpen && data.privateNote !== null;
	const onNoteButtonPress = () => {
		if (data.privateNote === null) {
			onEditNote();
			return;
		}
		setIsNoteOpen((prev) => !prev);
	};

	return (
		<div
			className={styles.card}
			style={customThemeStyle(data.customTheme)}
			data-custom-theme={data.customTheme ? true : undefined}
		>
			<Banner banner={data.banner} />
			{data.freeAgentPostId !== null ? (
				<LinkButton
					to={`${lfgSearchParams.href(LFG_PAGE, { post: data.freeAgentPostId })}#${data.freeAgentPostId}`}
					size="miniscule"
					icon={<Megaphone />}
					className={styles.freeAgentBadge}
				>
					{t("user:card.freeAgent")}
				</LinkButton>
			) : null}
			<div className={styles.iconButtons}>
				{isOwnCard ? (
					<LinkButton to={editPageUrl} size="miniscule" icon={<Pencil />}>
						{t("common:actions.edit")}
					</LinkButton>
				) : (
					<>
						{process.env.NODE_ENV === "development" ? (
							<ImpersonateButton userId={data.id} />
						) : null}
						{friendship && !friendship.isFriend ? (
							<FriendRequestButton
								targetUserId={data.id}
								sentFriendRequest={friendship.sentFriendRequest}
								incomingFriendRequestId={friendship.incomingFriendRequestId}
							/>
						) : null}
						<SendouButton
							size="miniscule"
							shape="circle"
							icon={
								data.privateNote !== null ? <NotebookText /> : <NotebookPen />
							}
							onPress={onNoteButtonPress}
							aria-label={t("user:card.editPrivateNote")}
						/>
						{onReport ? (
							<SendouButton
								size="miniscule"
								shape="circle"
								icon={<Flag />}
								onPress={onReport}
								aria-label="Report user"
								data-testid="report-user-button"
							/>
						) : null}
					</>
				)}
			</div>
			<div className={styles.identity}>
				<NoteAvatar
					sentiment={data.privateNote?.sentiment}
					onClick={isOwnCard ? undefined : onNoteButtonPress}
				>
					<Avatar user={data} size="md" className={styles.avatar} />
				</NoteAvatar>
				<div className={styles.nameGroup}>
					<h2 className={styles.username}>{data.username}</h2>
					{data.customUrl ? (
						<div className={styles.subtitle}>{data.customUrl}</div>
					) : null}
					{data.friendCode ? (
						<span className={styles.friendCode}>SW-{data.friendCode}</span>
					) : (
						/** reserve space */
						<span className={styles.friendCode}>{"\u200b"}</span>
					)}
				</div>
			</div>
			{showNoteView ? (
				<NoteView
					note={data.privateNote}
					onEdit={onEditNote}
					onDelete={onDeleteNote}
				/>
			) : (
				<>
					{stats.length > 0 ? (
						<div className={styles.stats}>
							{stats.map((stat, i) => (
								<React.Fragment key={stat.type}>
									{i > 0 ? <span className={styles.statDivider} /> : null}
									<Stat stat={stat} />
								</React.Fragment>
							))}
						</div>
					) : null}
					{isOwnCard || !withMutualFriends ? null : (
						<CardMutualFriends friendship={friendship} />
					)}
					{data.shortBio ? <p className={styles.bio}>{data.shortBio}</p> : null}
					<LinkButton
						to={userPage(data)}
						variant="outlined"
						size="small"
						className={styles.viewUserPage}
					>
						{t("user:card.viewUserPage")}
					</LinkButton>
				</>
			)}
		</div>
	);
}

function NoteView({
	note,
	onEdit,
	onDelete,
}: {
	note: UserCardData["privateNote"];
	onEdit: () => void;
	onDelete: () => void;
}) {
	const { t } = useTranslation(["common", "user"]);

	return (
		<div className={styles.noteView}>
			<div className={styles.noteHeaderGroup}>
				<span className={styles.noteHeader}>{t("user:card.privateNote")}</span>
				{note ? (
					<LocaleTime
						date={note.updatedAt}
						options={{ day: "numeric", month: "numeric", year: "numeric" }}
						className={styles.noteDate}
						inline
					/>
				) : null}
			</div>
			{note?.text ? <p className={styles.noteText}>{note.text}</p> : null}
			<div className={styles.noteViewActions}>
				<SendouButton
					variant="minimal"
					size="miniscule"
					icon={<Pencil />}
					onPress={onEdit}
				>
					{t("common:actions.edit")}
				</SendouButton>
				<SendouButton
					variant="minimal-destructive"
					size="miniscule"
					icon={<Trash2 />}
					onPress={onDelete}
				>
					{t("common:actions.delete")}
				</SendouButton>
			</div>
		</div>
	);
}

/**
 * Friend request action on the card, submitting to the `/friends` route action. Normally sends a
 * request and shows a checkmark once one is pending (server-known or just sent); when the shown
 * user has already sent the viewer a request, the same add-friend press accepts it instead.
 * Cancelling a pending request is done on the `/friends` page.
 */
function FriendRequestButton({
	targetUserId,
	sentFriendRequest,
	incomingFriendRequestId,
}: {
	targetUserId: number;
	sentFriendRequest: boolean;
	incomingFriendRequestId: number | null;
}) {
	const { t } = useTranslation(["user"]);
	const fetcher = useFetcher();
	const acceptRequest = useActionSubmit(acceptFriendRequestSchema, {
		action: FRIENDS_PAGE,
		fetcher,
	});
	const sendRequest = useActionSubmit(sendFriendRequestBaseSchema, {
		action: FRIENDS_PAGE,
		fetcher,
	});
	const previousStateRef = React.useRef(fetcher.state);
	const acceptsIncomingRequest = incomingFriendRequestId !== null;

	// Sending a request keeps this button mounted (it becomes the pending checkmark), so the
	// success toast can wait for the server round-trip here — the action can still reject with
	// "Maximum pending friend requests reached". The accept path instead unmounts the button as
	// soon as the revalidated friendship data arrives, which can race the toast render, so that
	// toast is fired directly from the press handler below.
	React.useEffect(() => {
		if (
			!acceptsIncomingRequest &&
			previousStateRef.current === "submitting" &&
			fetcher.state !== "submitting" &&
			fetcher.data === null
		) {
			toastQueue.add(
				{ message: t("user:card.friendRequestSent"), variant: "success" },
				{ timeout: 5000 },
			);
		}
		previousStateRef.current = fetcher.state;
	}, [fetcher.state, fetcher.data, acceptsIncomingRequest, t]);

	if (acceptsIncomingRequest) {
		return (
			<SendouButton
				size="miniscule"
				shape="circle"
				icon={<UserPlus />}
				isDisabled={fetcher.state !== "idle" || fetcher.data === null}
				aria-label="Accept friend request"
				onPress={() => {
					if (incomingFriendRequestId === null) return;
					toastQueue.add(
						{
							message: t("user:card.friendRequestAccepted"),
							variant: "success",
						},
						{ timeout: 5000 },
					);
					acceptRequest.submit("ACCEPT_REQUEST", {
						friendRequestId: incomingFriendRequestId,
					});
				}}
			/>
		);
	}

	const requestPending =
		sentFriendRequest || fetcher.state !== "idle" || fetcher.data === null;

	if (requestPending) {
		return (
			<SendouButton
				size="miniscule"
				shape="circle"
				icon={<UserRoundCheck />}
				isDisabled
				aria-label={t("user:card.friendRequestPending")}
			/>
		);
	}

	return (
		<SendouButton
			size="miniscule"
			shape="circle"
			icon={<UserPlus />}
			aria-label={t("user:card.sendFriendRequest")}
			onPress={() =>
				sendRequest.submit("SEND_REQUEST", { userId: targetUserId })
			}
		/>
	);
}

/** Development only shortcut for logging in as the shown user. */
function ImpersonateButton({ userId }: { userId: number }) {
	const location = useLocation();

	return (
		<Form method="post" action={impersonateUrl(userId)} reloadDocument>
			<input
				type="hidden"
				name="returnTo"
				value={`${location.pathname}${location.search}`}
			/>
			<SendouButton
				type="submit"
				size="miniscule"
				shape="circle"
				icon={<VenetianMask />}
				aria-label="Impersonate user"
			/>
		</Form>
	);
}

/**
 * Mutual friends row with reserved height so the card does not shift when the lazy friendship fetch
 * resolves: empty while loading, "No mutual friends" when there are none, the avatar stack otherwise.
 */
function CardMutualFriends({
	friendship,
}: {
	friendship: UserCardFriendship | undefined;
}) {
	const { t } = useTranslation(["user"]);

	return (
		<div className={styles.mutualFriends}>
			{friendship === undefined ? null : friendship.mutualFriends.length ===
				0 ? (
				<span className={styles.noMutualFriends}>
					{t("user:card.noMutualFriends")}
				</span>
			) : (
				<MutualFriends
					mutualFriends={friendship.mutualFriends}
					withoutPopover
				/>
			)}
		</div>
	);
}

function Banner({ banner }: { banner: UserCardData["banner"] }) {
	const style = (() => {
		switch (banner.type) {
			case "STAGE":
				return {
					backgroundImage: `url(${stageBannerImageUrl(banner.stageId)})`,
				};
			case "URL":
				return { backgroundImage: `url(${banner.url})` };
			case "COLOR":
				return { backgroundColor: banner.hexCode };
			default:
				assertUnreachable(banner);
		}
	})();

	return (
		<div
			className={styles.banner}
			style={style}
			data-testid="user-card-banner"
		/>
	);
}

function Stat({ stat }: { stat: UserCardData["stats"][number] }) {
	const { t } = useTranslation(["user"]);

	switch (stat.type) {
		case "XP": {
			const unverified = stat.values.find((value) => !value.isVerified);
			const verified = stat.values.find((value) => value.isVerified);
			const primary = unverified ?? verified;
			const secondary = unverified ? verified : undefined;

			return (
				<span className={clsx(styles.stat, styles.xpStat)}>
					{primary ? (
						<span className={styles.xpPrimary}>
							<span className={styles.xpPrimaryIcons}>
								{primary.isVerified ? (
									<BadgeCheck
										className={
											primary.region === "WEST"
												? styles.xpVerifiedIconSmall
												: styles.xpVerifiedIconLarge
										}
									/>
								) : null}
								<DivImage region={primary.region} />
							</span>
							{primary.points}
							{t("user:card.xp")}
						</span>
					) : null}
					{secondary ? (
						<span className={styles.xpVerified}>
							<BadgeCheck className={styles.xpVerifiedIconSmall} />
							<DivImage region={secondary.region} />
							{secondary.points}
							{t("user:card.xp")}
						</span>
					) : null}
				</span>
			);
		}
		case "DIV":
			return <span className={styles.stat}>Div {stat.value}</span>;
		case "PLUS":
			return (
				<span className={clsx(styles.stat, styles.plusStat)}>
					<Image path={navIconUrl("plus")} alt="+" size={24} />
					{stat.value}
				</span>
			);
		case "SEASON":
			return (
				<span className={styles.seasonStat}>
					<TierImage tier={stat.value} width={32} />
					{typeof stat.top === "number" ? (
						<span className={styles.seasonTop}>
							<Placement
								placement={stat.top}
								size={14}
								showAsSuperscript={false}
								textOnly
							/>
						</span>
					) : null}
				</span>
			);
		default:
			assertUnreachable(stat);
	}
}

function DivImage({ region }: { region: XRankPlacementRegion }) {
	const { t } = useTranslation(["common"]);

	if (region !== "WEST") return null;

	return (
		<Image
			path={brandImageUrl(TENTATEK_BRAND_ID)}
			alt={t("common:divisions.WEST")}
			width={18}
			height={18}
		/>
	);
}

function customThemeStyle(
	customTheme: UserCardData["customTheme"],
): React.CSSProperties {
	if (!customTheme) return {};

	return R.pickBy(
		customTheme,
		(value, key) =>
			value !== null && !key.includes("--_size") && !key.includes("--_border"),
	) as React.CSSProperties;
}
