// apps/web/src/lib/components/layout/AnythingAdder.svelte
<script lang="ts">
import { Plus } from "@lucide/svelte";
import { Button, Menu, MenuItem } from "@sendou/components";
import Image from "#lib/components/Image.svelte";
import { loggedInUser } from "#lib/features/auth/user-state.ts";
import { canAccessTrophies } from "#lib/features/trophies/trophies-utils.ts";
import { dynamicMessage } from "#lib/modules/i18n/messages.ts";
import { m } from "#lib/paraglide/messages.js";
import { navIconUrl, userPage } from "#lib/utils/urls.ts";

interface Props {
	compact?: boolean;
}

let { compact }: Props = $props();

const user = $derived(loggedInUser());

const items = $derived.by(() => {
	if (!user) return [];

	const all = [
		{ id: "tournament", icon: "medal", href: "/calendar/new/tournament" },
		{ id: "organization", icon: "medal", href: "/org/new" },
		{ id: "calendarEvent", icon: "calendar", href: "/calendar/new" },
		{ id: "build", icon: "builds", href: `${userPage(user)}/builds/new` },
		{ id: "team", icon: "t", href: "/t?new=true" },
		{ id: "scrimPost", icon: "scrims", href: "/scrims/new" },
		{ id: "association", icon: "associations", href: "/associations/new" },
		{ id: "lfgPost", icon: "lfg", href: "/lfg/new" },
		{ id: "art", icon: "art", href: "/art/new" },
		{ id: "vod", icon: "vods", href: "/vods/new" },
		{ id: "plusSuggestion", icon: "plus", href: "/plus/suggestions/new" },
		canAccessTrophies(user)
			? { id: "trophy", icon: "trophies", href: "/trophies/new" }
			: null,
	];

	return all.filter((item) => item !== null);
});
</script>

{#if user}
	<Menu>
		{#snippet trigger(triggerProps)}
			<Button
				size="small"
				shape={compact ? "square" : undefined}
				testId="anything-adder-menu-button"
				{...triggerProps}
			>
				{#snippet icon()}<Plus />{/snippet}
				{#if !compact}{`${m.common_actions_addNew()}…`}{/if}
			</Button>
		{/snippet}
		{#each items as item (item.id)}
			<MenuItem href={item.href}>
				{#snippet icon()}
					<Image path={navIconUrl(item.icon)} alt="" width={20} height={20} />
				{/snippet}
				{dynamicMessage(`common_header_adder_${item.id}`)}
			</MenuItem>
		{/each}
	</Menu>
{/if}

// apps/web-react/app/components/layout/AnythingAdder.tsx
import { Plus } from "lucide-react";
import { useTranslation } from "react-i18next";
import { newArtPage } from "~/features/art/art-urls";
import { useUser } from "~/features/auth/core/user";
import { lfgNewPostPage } from "~/features/lfg/lfg-urls";
import { plusSuggestionsNewPage } from "~/features/plus-suggestions/plus-suggestions-urls";
import { canAccessTrophies } from "~/features/trophies/trophies-utils";
import { userNewBuildPage } from "~/features/user-page/user-page-urls";
import { newVodPage } from "~/features/vods/vods-urls";
import {
	CALENDAR_NEW_PAGE,
	NEW_TEAM_PAGE,
	NEW_TROPHY_PAGE,
	navIconUrl,
	newAssociationsPage,
	newScrimPostPage,
	ORGANIZATION_NEW_PAGE,
	TOURNAMENT_NEW_PAGE,
} from "~/utils/urls";
import { SendouButton } from "../elements/Button";
import {
	SendouMenu,
	SendouMenuItem,
	type SendouMenuItemProps,
} from "../elements/Menu";

export function AnythingAdder({ compact }: { compact?: boolean }) {
	const { t } = useTranslation(["common"]);
	const user = useUser();

	if (!user) {
		return null;
	}

	const items: Array<SendouMenuItemProps> = [
		{
			id: "tournament",
			children: t("header.adder.tournament"),
			imagePath: navIconUrl("medal"),
			href: TOURNAMENT_NEW_PAGE,
		},
		{
			id: "organization",
			children: t("header.adder.organization"),
			imagePath: navIconUrl("medal"),
			href: ORGANIZATION_NEW_PAGE,
		},
		{
			id: "calendarEvent",
			children: t("header.adder.calendarEvent"),
			imagePath: navIconUrl("calendar"),
			href: CALENDAR_NEW_PAGE,
		},
		{
			id: "builds",
			children: t("header.adder.build"),
			imagePath: navIconUrl("builds"),
			href: userNewBuildPage(user),
		},
		{
			id: "team",
			children: t("header.adder.team"),
			imagePath: navIconUrl("t"),
			href: NEW_TEAM_PAGE,
		},
		{
			id: "scrimPost",
			children: t("header.adder.scrimPost"),
			imagePath: navIconUrl("scrims"),
			href: newScrimPostPage(),
		},
		{
			id: "association",
			children: t("header.adder.association"),
			imagePath: navIconUrl("associations"),
			href: newAssociationsPage(),
		},
		{
			id: "lfgPost",
			children: t("header.adder.lfgPost"),
			imagePath: navIconUrl("lfg"),
			href: lfgNewPostPage(),
		},
		{
			id: "art",
			children: t("header.adder.art"),
			imagePath: navIconUrl("art"),
			href: newArtPage(),
		},
		{
			id: "vods",
			children: t("header.adder.vod"),
			imagePath: navIconUrl("vods"),
			href: newVodPage(),
		},
		{
			id: "plus",
			children: t("header.adder.plusSuggestion"),
			imagePath: navIconUrl("plus"),
			href: plusSuggestionsNewPage(),
		},
		canAccessTrophies(user)
			? {
					id: "trophy",
					children: t("header.adder.trophy"),
					imagePath: navIconUrl("trophies"),
					href: NEW_TROPHY_PAGE,
				}
			: null,
	].filter((item) => item !== null);

	return (
		<SendouMenu
			placement="bottom right"
			trigger={
				<SendouButton
					size="small"
					icon={<Plus />}
					shape={compact ? "square" : undefined}
					data-testid="anything-adder-menu-button"
				>
					{compact ? undefined : `${t("common:actions.addNew")}…`}
				</SendouButton>
			}
		>
			{items.map((item) => (
				<SendouMenuItem
					key={item.id}
					data-testid={`menu-item-${item.id}`}
					{...item}
				/>
			))}
		</SendouMenu>
	);
}
