// src/lib/components/ModeMapPoolPicker.svelte
<script lang="ts">
	import { asset } from '$app/paths';
	import { stageIds } from '$lib/constants/in-game/stage-ids';
	import type { ModeShort, StageId } from '$lib/constants/in-game/types';
	import { nullFilledArray } from '$lib/utils/arrays';
	import { stageTranslations } from '$lib/utils/i18n';
	import Divider from './Divider.svelte';
	import Check from '@lucide/svelte/icons/check';

	interface Props {
		mode: ModeShort;
		amountToPick: number;
		pool: StageId[];
		bannedMaps?: StageId[];
		tiebreaker?: StageId;
	}

	let { mode, amountToPick, pool = $bindable(), tiebreaker, bannedMaps }: Props = $props();

	console.log({ mode, amountToPick, pool, tiebreaker, bannedMaps });

	let wigglingStageId = $state<StageId | null>(null);
	$effect(() => {
		if (wigglingStageId === null) return;
		const timeout = setTimeout(() => {
			wigglingStageId = null;
		}, 1000);

		return () => {
			clearTimeout(timeout);
		};
	});

	const stages = $derived([...pool, ...nullFilledArray(amountToPick - pool.length)]);

	function stageClickHandler(stageId: StageId) {
		return () => {
			if (tiebreaker === stageId) return;
			if (bannedMaps?.includes(stageId)) return;
			if (stages.includes(stageId)) {
				pool = pool.filter((s) => s !== stageId);
				return;
			}

			handleUnpickedStageClick(stageId);
		};
	}

	function handleUnpickedStageClick(stageId: StageId) {
		// is there space left?
		if (stages[amountToPick - 1] !== null) {
			wigglingStageId = stageId;
			return;
		}

		// was it already picked?
		if (pool.includes(stageId)) {
			return;
		}

		const newPool = [...pool, stageId].sort((a, b) => a - b);
		pool = newPool;
	}
</script>

<div class="container stack sm">
	<div class="stack sm horizontal justify-center">
		{#each { length: amountToPick }, index}
			{@render mapSlot({ number: index + 1, picked: stages[index] !== null })}
		{/each}
	</div>
	<Divider class="divider">
		<img src={asset(`/img/modes/${mode}.avif`)} height={32} width={32} alt="" />
	</Divider>
	<div class="stack sm horizontal flex-wrap justify-center mt-1">
		{#each stageIds as stageId (stageId)}
			{@render mapButton({
				stageId,
				onclick: stageClickHandler(stageId),
				selected: stages.includes(stageId),
				banned: bannedMaps?.includes(stageId),
				tiebreaker: tiebreaker === stageId,
				wiggling: wigglingStageId === stageId,
				testId: `map-pool-${mode}-${stageId}`
			})}
		{/each}
	</div>
</div>

{#snippet mapSlot({ number, picked }: { number: number; picked: boolean })}
	<div class={['slot', { picked }]}>
		{#if picked}
			<Check />
		{:else}
			{number}
		{/if}
	</div>
{/snippet}

{#snippet mapButton({
	stageId,
	onclick,
	selected = false,
	banned = false,
	tiebreaker = false,
	wiggling = false,
	testId
}: {
	stageId: StageId;
	onclick: () => void;
	selected?: boolean;
	banned?: boolean;
	tiebreaker?: boolean;
	wiggling?: boolean;
	testId?: string;
})}
	<div class="stack items-center relative">
		<button
			class={['map-button', { 'greyed-out': selected || banned || tiebreaker, wiggling }]}
			style="--map-image-url: url('{asset(`/img/stages/${stageId}.avif`)}')"
			{onclick}
			disabled={banned}
			type="button"
			data-testid={testId}
			aria-label={stageTranslations[stageId]()}
		></button>
		{#if selected}
			<Check class="map-button__icon" {onclick} />
		{/if}
		{#if tiebreaker}
			<div class="map-button__text text-info">Tiebreak</div>
		{:else if banned}
			<div class="map-button__text text-error">Banned</div>
		{/if}
		<div class="map-button__label">
			{stageTranslations[stageId]()}
		</div>
	</div>
{/snippet}

<style>
	.container {
		--map-width: 90px;
		--map-height: 50px;

		:global {
			.divider {
				font-size: var(--fonts-xs);
				font-weight: var(--semi-bold);
				text-transform: uppercase;
				display: flex;
				gap: var(--s-2);

				&::before,
				&::after {
					border-bottom: 2px dotted var(--color-primary-transparent);
				}
			}

			.map-button__icon {
				position: absolute;
				top: 8.5px;
				color: var(--color-success);
				width: 36px;
				height: 36px;
				stroke-width: 3px;
				cursor: pointer;
			}
		}
	}

	.slot {
		font-size: var(--fonts-xs);
		display: grid;
		place-items: center;
		color: var(--color-base-content-secondary);
		border-radius: var(--radius-field);
		font-weight: var(--bold);
		width: 24px;
		height: 24px;
		border: 2px dotted var(--color-primary-transparent);

		&.picked {
			border-style: solid;
		}

		:global {
			svg {
				color: var(--color-success);
				width: 16px;
				stroke-width: 3px;
			}
		}
	}

	.map-button {
		background-image: var(--map-image-url);
		background-size: contain;
		height: var(--map-height);
		width: var(--map-width);
		border: none;
		background-color: transparent;
		transition:
			filter,
			opacity 0.2s;
		border-radius: var(--radius-field);
		cursor: pointer;

		&.greyed-out {
			filter: grayscale(100%) !important;
			opacity: 0.4 !important;
		}

		&:focus-visible {
			outline: 1px solid var(--color-secondary);
		}
	}

	@keyframes wiggle {
		0% {
			transform: rotate(0deg);
		}

		25% {
			transform: rotate(5deg);
		}

		75% {
			transform: rotate(-5deg);
		}

		100% {
			transform: rotate(0deg);
		}
	}

	.wiggling {
		animation: wiggle 0.25s infinite;
		animation-iteration-count: 1;
	}

	.map-button:active {
		transform: none;
	}

	.map-button__text {
		position: absolute;
		top: 14px;
		text-transform: uppercase;
		font-weight: var(--bold);
		cursor: not-allowed;
	}

	.map-button__label {
		font-size: var(--fonts-xxxxs);
		color: var(--text-lighter);
		font-weight: var(--semi-bold);
	}
</style>

// app/features/settings/components/ModeMapPoolPicker.tsx
import clsx from "clsx";
import { Check } from "lucide-react";
import * as React from "react";
import { useTranslation } from "react-i18next";
import { Divider } from "~/components/Divider";
import { ModeImage } from "~/components/Image";
import { BANNED_MAPS } from "~/features/match-profile/banned-maps";
import { shortStageName, stageIds } from "~/modules/in-game-lists/stage-ids";
import type { ModeShort, StageId } from "~/modules/in-game-lists/types";
import { nullFilledArray } from "~/utils/arrays";
import { stageImageUrl } from "~/utils/urls";
import styles from "./ModeMapPoolPicker.module.css";

export function ModeMapPoolPicker({
	mode,
	amountToPick,
	pool,
	tiebreaker,
	onChange,
}: {
	mode: ModeShort;
	amountToPick: number;
	pool: StageId[];
	tiebreaker?: StageId;
	onChange: (stages: StageId[]) => void;
}) {
	const [wigglingStageId, setWigglingStageId] = React.useState<StageId | null>(
		null,
	);

	React.useEffect(() => {
		if (wigglingStageId === null) return;
		const timeout = setTimeout(() => {
			setWigglingStageId(null);
		}, 1000);

		return () => {
			clearTimeout(timeout);
		};
	}, [wigglingStageId]);

	const stages: (StageId | null)[] = [
		...pool,
		...nullFilledArray(amountToPick - pool.length),
	];

	const handlePickedStageClick = (stageId: StageId) => {
		onChange(pool.filter((s) => s !== stageId));
	};

	const handleUnpickedStageClick = (stageId: StageId) => {
		// is there space left?
		if (stages[amountToPick - 1] !== null) {
			setWigglingStageId(stageId);
			return;
		}

		// was it already picked?
		if (pool.includes(stageId)) {
			return;
		}

		onChange([...pool, stageId].sort((a, b) => a - b));
	};

	return (
		<div className={clsx(styles.container, "stack sm")}>
			<div className="stack sm horizontal justify-center">
				{nullFilledArray(amountToPick).map((_, index) => {
					return (
						<MapSlot
							key={index}
							number={index + 1}
							picked={stages[index] !== null}
						/>
					);
				})}
			</div>
			<Divider className={styles.divider}>
				<ModeImage mode={mode} size={32} />
			</Divider>
			<div className="stack sm horizontal flex-wrap justify-center mt-1">
				{stageIds.map((stageId) => {
					const isTiebreaker = tiebreaker === stageId;
					const banned = BANNED_MAPS[mode].includes(stageId);
					const selected = stages.includes(stageId);

					const onClick = () => {
						if (isTiebreaker) return;
						if (banned) return;
						if (selected) return handlePickedStageClick(stageId);

						handleUnpickedStageClick(stageId);
					};

					return (
						<MapButton
							key={stageId}
							stageId={stageId}
							onClick={onClick}
							selected={selected}
							banned={banned}
							tiebreaker={isTiebreaker}
							wiggle={wigglingStageId === stageId}
							testId={`map-pool-${mode}-${stageId}`}
						/>
					);
				})}
			</div>
		</div>
	);
}

function MapSlot({ number, picked }: { number: number; picked: boolean }) {
	return (
		<div
			className={clsx(styles.slot, {
				[styles.slotPicked]: picked,
			})}
		>
			{picked ? <Check className={styles.slotIcon} /> : number}
		</div>
	);
}

function MapButton({
	stageId,
	onClick,
	selected,
	banned,
	tiebreaker,
	wiggle,
	testId,
}: {
	stageId: StageId;
	onClick: () => void;
	selected?: boolean;
	banned?: boolean;
	tiebreaker?: boolean;
	wiggle?: boolean;
	testId: string;
}) {
	const { t } = useTranslation(["game-misc"]);

	return (
		<div
			className={clsx("stack items-center relative", styles.mapButtonContainer)}
		>
			<button
				className={clsx(styles.mapButton, {
					[styles.mapButtonWiggle]: wiggle,
					[styles.mapButtonGreyedOut]: selected || banned || tiebreaker,
				})}
				style={{ "--map-image-url": `url("${stageImageUrl(stageId)}.avif")` }}
				onClick={onClick}
				disabled={banned}
				type="button"
				data-testid={testId}
			/>
			{selected ? (
				<Check className={styles.mapButtonIcon} onClick={onClick} />
			) : null}
			{tiebreaker ? (
				<div className={styles.mapButtonText}>Tiebreak</div>
			) : banned ? (
				<div className={clsx(styles.mapButtonText, "text-error")}>Banned</div>
			) : null}
			<div className={styles.mapButtonLabel}>
				{shortStageName(t(`game-misc:STAGE_${stageId}`))}
			</div>
		</div>
	);
}
