// src/routes/builds/+page.svelte
<script lang="ts">
	import { mainWeaponImageUrl, mySlugify, weaponCategoryUrl } from '$lib/utils/urls';
	import OpenGraphMeta from '$lib/components/open-graph-meta.svelte';
	import Image from '$lib/components/image/image.svelte';
	import AddNewButton from '$lib/components/add-new-button.svelte';
	import { resolve } from '$app/paths';
	import { me } from '../me.remote';
	import { weaponCategories, weaponIdIsNotAlt } from '$lib/constants/in-game/weapon-ids';
	import Main from '$lib/components/main.svelte';
	import { weaponCategoryTranslations, weaponTranslations } from '$lib/utils/i18n';
	import type { MainWeaponId } from '$lib/constants/in-game/types';

	const user = $derived(await me());

	function weaponIdToSlug(weaponId: MainWeaponId): string {
		return mySlugify(weaponTranslations[weaponId]());
	}
</script>

<OpenGraphMeta
	title="Builds"
	ogTitle="Splatoon 3 builds for all weapons"
	description="View Splatoon 3 builds for all weapons by the best players. Includes collection of user submitted builds and an aggregation of ability stats."
/>

<Main class="stack md">
	{#if user}
		<div class="stack items-end">
			<AddNewButton
				navIcon="builds"
				href={resolve(`/u/${user.customUrl ?? user.discordId}/builds`)}
			/>
		</div>
	{/if}

	{#each weaponCategories as category (category.name)}
		<div class="category">
			<div class="category-header">
				<Image
					path={weaponCategoryUrl(category.name)}
					width={40}
					height={40}
					alt={weaponCategoryTranslations[category.name]()}
				/>
				{weaponCategoryTranslations[category.name]()}
			</div>
			<div class="category-weapons">
				{#each (category.weaponIds as readonly MainWeaponId[]).filter(weaponIdIsNotAlt) as weaponId, i (weaponId)}
					{#if i !== 0 && weaponId % 10 === 0}
						<div class="category-divider"></div>
					{/if}
					<a
						href={resolve(`/builds/${weaponIdToSlug(weaponId)}`)}
						class="category-weapon"
						data-testid={`weapon-${weaponId}-link`}
					>
						<Image
							class="category-weapon-img"
							path={mainWeaponImageUrl(weaponId)}
							width={28}
							height={28}
						/>
						{weaponTranslations[weaponId]()}
					</a>
				{/each}
			</div>
		</div>
	{/each}
</Main>

<style>
	.category-divider {
		height: 20px;
		margin: auto 0;
		width: 4px;
		border-radius: var(--rounded);
		background-color: var(--bg-lightest);
	}

	.category {
		display: flex;
		flex-direction: column;
		padding: var(--s-3);
		border-radius: var(--rounded);
		background-color: var(--bg-lighter);
		font-size: var(--fonts-sm);
		font-weight: 600;
		gap: var(--s-4);
	}

	.category-header {
		display: flex;
		align-items: center;
		gap: var(--s-2-5);
	}

	.category-weapons {
		display: flex;
		flex-wrap: wrap;
		gap: var(--s-3);
	}

	.category-weapon {
		display: flex;
		align-items: center;
		color: var(--text);
		font-size: var(--fonts-xs);
		font-weight: var(--body);
		gap: var(--s-1);

		:global(.category-weapon-img) {
			border-radius: var(--rounded);
			background-color: var(--bg-darker);
		}
	}
</style>

// app/features/builds/routes/builds.tsx
import type { MetaFunction } from "@remix-run/node";
import { Link } from "@remix-run/react";
import { useTranslation } from "react-i18next";
import { AddNewButton } from "~/components/AddNewButton";
import { Image } from "~/components/Image";
import { Main } from "~/components/Main";
import { useUser } from "~/features/auth/core/user";
import type { MainWeaponId } from "~/modules/in-game-lists/types";
import {
	weaponCategories,
	weaponIdIsNotAlt,
} from "~/modules/in-game-lists/weapon-ids";
import type { SendouRouteHandle } from "~/utils/remix.server";
import {
	BUILDS_PAGE,
	mainWeaponImageUrl,
	mySlugify,
	navIconUrl,
	userNewBuildPage,
	weaponBuildPage,
	weaponCategoryUrl,
} from "~/utils/urls";
import { metaTags } from "../../../utils/remix";

import "~/styles/builds.css";

export const meta: MetaFunction = (args) => {
	return metaTags({
		title: "Builds",
		ogTitle: "Splatoon 3 builds for all weapons",
		description:
			"View Splatoon 3 builds for all weapons by the best players. Includes collection of user submitted builds and an aggregation of ability stats.",
		location: args.location,
	});
};

export const handle: SendouRouteHandle = {
	i18n: "weapons",
	breadcrumb: () => ({
		imgPath: navIconUrl("builds"),
		href: BUILDS_PAGE,
		type: "IMAGE",
	}),
};

export default function BuildsPage() {
	const user = useUser();
	const { t } = useTranslation(["common", "weapons"]);

	const weaponIdToSlug = (weaponId: MainWeaponId) => {
		return mySlugify(t(`weapons:MAIN_${weaponId}`, { lng: "en" }));
	};

	return (
		<Main className="stack md">
			{user ? (
				<div className="stack items-end">
					<AddNewButton navIcon="builds" to={userNewBuildPage(user)} />
				</div>
			) : null}
			{weaponCategories.map((category) => (
				<div key={category.name} className="builds__category">
					<div className="builds__category__header">
						<Image
							path={weaponCategoryUrl(category.name)}
							width={40}
							height={40}
							alt={t(`common:weapon.category.${category.name}`)}
						/>
						{t(`common:weapon.category.${category.name}`)}
					</div>
					<div className="builds__category__weapons">
						{(category.weaponIds as readonly MainWeaponId[])
							.filter(weaponIdIsNotAlt)
							.sort((a, b) =>
								t(`weapons:MAIN_${a}`).localeCompare(t(`weapons:MAIN_${b}`)),
							)
							.map((weaponId) => (
								<Link
									key={weaponId}
									to={weaponBuildPage(weaponIdToSlug(weaponId))}
									className="builds__category__weapon"
									data-testid={`weapon-${weaponId}-link`}
								>
									<Image
										className="builds__category__weapon__img"
										path={mainWeaponImageUrl(weaponId)}
										width={28}
										height={28}
										alt={t(`weapons:MAIN_${weaponId}`)}
									/>
									{t(`weapons:MAIN_${weaponId}`)}
								</Link>
							))}
					</div>
				</div>
			))}
		</Main>
	);
}
