// src/routes/links/+page.svelte
<script lang="ts">
	import DiscordIcon from '$lib/components/icons/discord.svelte';
	import YouTubeIcon from '$lib/components/icons/youtube.svelte';
	import Main from '$lib/components/main.svelte';
	import links from './links.json';

	// links should be sorted in the json like so: links.sort((a, b) => a.title.localeCompare(b.title))
</script>

<Main>
	<div class="stack md container">
		{#each links as link (link.url)}
			<div>
				<h2 class="text-sm">
					<a
						href={link.url}
						target="_blank"
						rel="noopener noreferrer"
						class="stack sm horizontal items-center"
					>
						{link.title}
						{#if link.url.includes('discord')}
							<DiscordIcon class="discord-icon" />
						{:else if link.url.includes('youtube')}
							<YouTubeIcon class="youtube-icon" />
						{/if}
					</a>
				</h2>
				<div class="text-sm text-lighter">{link.description}</div>
			</div>
		{/each}
	</div>
</Main>

<style>
	.container :global(.discord-icon) {
		width: 1rem;
		display: inline;
		fill: #7289da;
	}

	.container :global(.youtube-icon) {
		width: 1rem;
		display: inline;
		fill: #f00;
	}
</style>

// app/features/links/routes/links.tsx
import type { MetaFunction } from "@remix-run/node";
import { Main } from "~/components/Main";
import { DiscordIcon } from "~/components/icons/Discord";
import { YouTubeIcon } from "~/components/icons/YouTube";
import { openGraph } from "~/utils/remix";
import type { SendouRouteHandle } from "~/utils/remix.server";
import { LINKS_PAGE, navIconUrl } from "~/utils/urls";
import links from "../links.json";

export const handle: SendouRouteHandle = {
	breadcrumb: () => ({
		imgPath: navIconUrl("links"),
		href: LINKS_PAGE,
		type: "IMAGE",
	}),
};

export const meta: MetaFunction = (args) => {
	return openGraph({
		title: "Links",
		ogTitle: "Splatoon link collection",
		description:
			"Collection of useful Splatoon guides, Discord servers and other resources.",
		location: args.location,
	});
};

export default function LinksPage() {
	return (
		<Main>
			<div className="stack md">
				{links
					.sort((a, b) => a.title.localeCompare(b.title))
					.map((link) => {
						const isDiscord = link.url.includes("discord");
						const isYoutube = link.url.includes("youtube");

						return (
							<div key={link.url}>
								<h2 className="text-sm">
									<a
										href={link.url}
										target="_blank"
										rel="noopener noreferrer"
										className="stack sm horizontal items-center"
									>
										{link.title}
										{isDiscord ? (
											<DiscordIcon className="discord-icon" />
										) : null}
										{isYoutube ? (
											<YouTubeIcon className="youtube-icon" />
										) : null}
									</a>
								</h2>
								<div className="text-sm text-lighter">{link.description}</div>
							</div>
						);
					})}
			</div>
		</Main>
	);
}
