// apps/web-react/app/components/BuildCard.tsx
import type {
	Ability as AbilityType,
	BuildAbilitiesTuple,
	GearType,
	ModeShort,
} from "@sendou/in-game-lists/types";
import { canonicalWeaponSplId } from "@sendou/in-game-lists/weapon-ids";
import clsx from "clsx";
import {
	HardDriveDownload,
	Lock,
	MessageCircleMore,
	SquarePen,
	Trash,
} from "lucide-react";
import * as React from "react";
import { useTranslation } from "react-i18next";
import { Link } from "react-router";
import type { Tables } from "~/db/tables";
import { useUser } from "~/features/auth/core/user";
import { analyzerPage } from "~/features/build-analyzer/analyzer-urls";
import type { BuildWeaponWithTop500Info } from "~/features/builds/builds-types";
import {
	BuildGraphic,
	type BuildGraphicOwner,
} from "~/features/img-export/components/BuildGraphic";
import { ImageExportDialog } from "~/features/img-export/components/ImageExportDialog";
import type { UserWithPlusTier } from "~/utils/kysely.server";
import { gearTypeToInitial } from "~/utils/strings";
import {
	gearImageUrl,
	mainWeaponImageUrl,
	modeImageUrl,
	mySlugify,
	navIconUrl,
	userBuildsPage,
	weaponBuildPage,
} from "~/utils/urls";
import { Ability } from "./Ability";
import styles from "./BuildCard.module.css";
import { LinkButton, SendouButton } from "./elements/Button";
import { SendouPopover } from "./elements/Popover";
import { SendouSwitch } from "./elements/Switch";
import { FormWithConfirm } from "./FormWithConfirm";
import { Image } from "./Image";
import { LocaleTime } from "./LocaleTime";

interface BuildProps {
	build: Pick<
		Tables["Build"],
		| "id"
		| "title"
		| "description"
		| "clothesGearSplId"
		| "headGearSplId"
		| "shoesGearSplId"
		| "updatedAt"
		| "isPrivate"
	> & {
		abilities: BuildAbilitiesTuple;
		modes: ModeShort[] | null;
		weapons: Array<BuildWeaponWithTop500Info>;
	};
	owner?: Pick<UserWithPlusTier, "discordId" | "username" | "plusTier"> &
		Partial<
			Pick<BuildGraphicOwner, "customUrl" | "discordAvatar" | "customAvatarUrl">
		>;
	/** Set to false when the page context already shows the owner (e.g. their own builds page) */
	showOwner?: boolean;
	canEdit?: boolean;
}

export function BuildCard({
	build,
	owner,
	showOwner = true,
	canEdit = false,
}: BuildProps) {
	const user = useUser();
	const { t } = useTranslation(["weapons", "builds", "common", "game-misc"]);

	const {
		id,
		title,
		description,
		clothesGearSplId,
		headGearSplId,
		shoesGearSplId,
		updatedAt,
		modes,
		weapons,
		abilities,
	} = build;

	const isNoGear = [headGearSplId, clothesGearSplId, shoesGearSplId].some(
		(id) => typeof id !== "number",
	);

	return (
		<div
			className={clsx(styles.card, { [styles.private]: build.isPrivate })}
			data-testid="build-card"
		>
			<div>
				<div className={styles.topRow}>
					{modes && modes.length > 0 && (
						<div className={styles.modes}>
							{modes.map((mode) => (
								<Image
									key={mode}
									alt={t(`game-misc:MODE_LONG_${mode}` as any)}
									title={t(`game-misc:MODE_LONG_${mode}` as any)}
									path={modeImageUrl(mode)}
									width={18}
									height={18}
									testId={`build-mode-${mode}`}
								/>
							))}
						</div>
					)}
					<h2 className={styles.title} data-testid="build-title">
						{title}
					</h2>
				</div>
				<div className={styles.dateAuthorRow}>
					{owner && showOwner ? (
						<>
							<Link to={userBuildsPage(owner)} className={styles.ownerLink}>
								{owner.username}
							</Link>
							<div>•</div>
						</>
					) : null}
					{owner?.plusTier && showOwner ? (
						<>
							<span>+{owner.plusTier}</span>
							<div>•</div>
						</>
					) : null}
					<div className="stack horizontal sm items-center">
						{build.isPrivate ? (
							<div className={styles.privateText}>
								<Lock size={16} /> {t("common:build.private")}
							</div>
						) : null}
						<LocaleTime
							date={updatedAt}
							options={{
								day: "numeric",
								month: "numeric",
								year: "numeric",
							}}
							className="whitespace-nowrap"
						/>
					</div>
				</div>
			</div>
			<div className={styles.weapons}>
				{weapons.map((weapon) => (
					<RoundWeaponImage key={weapon.weaponSplId} weapon={weapon} />
				))}
				{weapons.length === 1 && (
					<div className={styles.weaponText}>
						{t(`weapons:MAIN_${weapons[0].weaponSplId}` as any)}
					</div>
				)}
			</div>
			<div
				className={clsx(styles.gearAbilities, {
					[styles.noGear]: isNoGear,
				})}
			>
				<AbilitiesRowWithGear
					gearType="HEAD"
					abilities={abilities[0]}
					gearId={headGearSplId}
				/>
				<AbilitiesRowWithGear
					gearType="CLOTHES"
					abilities={abilities[1]}
					gearId={clothesGearSplId}
				/>
				<AbilitiesRowWithGear
					gearType="SHOES"
					abilities={abilities[2]}
					gearId={shoesGearSplId}
				/>
			</div>
			<div className={styles.bottomRow}>
				<LinkButton
					to={analyzerPage({
						weaponId: weapons[0].weaponSplId,
						abilities: abilities.flat(),
					})}
					shape="circle"
					variant="minimal"
					size="small"
				>
					<Image
						size={24}
						alt={t("common:pages.analyzer")}
						className={styles.icon}
						path={navIconUrl("analyzer")}
					/>
				</LinkButton>
				{owner ? <BuildImageExportDialog build={build} owner={owner} /> : null}
				{description ? (
					<SendouPopover
						trigger={
							<SendouButton
								shape="circle"
								size="small"
								variant="minimal"
								icon={<MessageCircleMore />}
								className={styles.smallText}
							/>
						}
					>
						{description}
					</SendouPopover>
				) : null}
				{canEdit && (
					<>
						<LinkButton
							shape="circle"
							className={styles.smallText}
							variant="minimal"
							size="small"
							to={`new?buildId=${id}&userId=${user!.id}`}
							testId="edit-build"
							icon={<SquarePen />}
						/>
						<FormWithConfirm
							dialogHeading={t("builds:deleteConfirm", { title })}
							fields={[
								["buildToDeleteId", id],
								["_action", "DELETE_BUILD"],
							]}
						>
							<SendouButton
								shape="circle"
								size="small"
								icon={<Trash />}
								className={styles.smallText}
								variant="minimal-destructive"
								type="submit"
							/>
						</FormWithConfirm>
					</>
				)}
			</div>
		</div>
	);
}

function BuildImageExportDialog({
	build,
	owner,
}: {
	build: BuildProps["build"];
	owner: BuildGraphicOwner;
}) {
	const { t } = useTranslation(["common"]);
	const [showTitle, setShowTitle] = React.useState(true);
	const [showAbilityPoints, setShowAbilityPoints] = React.useState(true);
	const [showAbilityChunks, setShowAbilityChunks] = React.useState(false);

	return (
		<ImageExportDialog
			trigger={
				<SendouButton
					shape="circle"
					size="small"
					variant="minimal"
					icon={<HardDriveDownload />}
					className={styles.smallText}
					aria-label={t("common:imageExport.export")}
				/>
			}
			heading={t("common:imageExport.export")}
			filename={`build-${mySlugify(build.title)}`}
			qrCodePath={analyzerPage({
				weaponId: build.weapons[0].weaponSplId,
				abilities: build.abilities.flat(),
			})}
			settings={
				<>
					<SendouSwitch isSelected={showTitle} onChange={setShowTitle}>
						{t("common:imageExport.buildTitle")}
					</SendouSwitch>
					<SendouSwitch
						isSelected={showAbilityPoints}
						onChange={setShowAbilityPoints}
					>
						{t("common:imageExport.abilityPoints")}
					</SendouSwitch>
					<SendouSwitch
						isSelected={showAbilityChunks}
						onChange={setShowAbilityChunks}
					>
						{t("common:imageExport.abilityChunks")}
					</SendouSwitch>
				</>
			}
		>
			<BuildGraphic
				build={build}
				owner={owner}
				showTitle={showTitle}
				showAbilityPoints={showAbilityPoints}
				showAbilityChunks={showAbilityChunks}
			/>
		</ImageExportDialog>
	);
}

function RoundWeaponImage({ weapon }: { weapon: BuildWeaponWithTop500Info }) {
	const normalizedWeaponSplId = canonicalWeaponSplId(weapon.weaponSplId);

	const { t } = useTranslation(["weapons"]);
	const slug = mySlugify(
		t(`weapons:MAIN_${normalizedWeaponSplId}`, { lng: "en" }),
	);

	return (
		<div key={weapon.weaponSplId} className={styles.weapon}>
			{weapon.isTop500 ? (
				<Image
					className={styles.top500}
					path={navIconUrl("xsearch")}
					alt=""
					height={24}
					width={24}
					testId="top500-crown"
				/>
			) : null}
			<Link to={weaponBuildPage(slug)}>
				<Image
					path={mainWeaponImageUrl(weapon.weaponSplId)}
					alt={t(`weapons:MAIN_${weapon.weaponSplId}`)}
					title={t(`weapons:MAIN_${weapon.weaponSplId}`)}
					height={36}
					width={36}
				/>
			</Link>
		</div>
	);
}

function AbilitiesRowWithGear({
	gearType,
	abilities,
	gearId,
}: {
	gearType: GearType;
	abilities: AbilityType[];
	gearId: number | null;
}) {
	const { t } = useTranslation(["gear"]);
	const translatedGearName = t(
		`gear:${gearTypeToInitial(gearType)}_${gearId}` as any,
	);

	return (
		<>
			{typeof gearId === "number" ? (
				<Image
					height={64}
					width={64}
					alt={translatedGearName}
					title={translatedGearName}
					path={gearImageUrl(gearType, gearId)}
					className={styles.gear}
				/>
			) : null}
			{abilities.map((ability, i) => (
				<Ability key={i} ability={ability} size={i === 0 ? "MAIN" : "SUB"} />
			))}
		</>
	);
}

// src/lib/components/build-card.svelte
<script lang="ts">
	import {
		gearImageUrl,
		modeImageUrl,
		navIconUrl,
		userBuildsPage,
		weaponBuildPage
	} from '$lib/utils/urls';
	import Ability from './ability.svelte';
	import Image from './image/image.svelte';
	import LockIcon from './icons/lock.svelte';
	import type {
		Ability as AbilityType,
		BuildAbilitiesTuple,
		MainWeaponId,
		ModeShort
	} from '$lib/constants/in-game/types';
	import type { GearType, Tables, UserWithPlusTier } from '$lib/server/db/tables';
	import { m } from '$lib/paraglide/messages';
	import { modesLongTranslations, weaponTranslations } from '$lib/utils/i18n';
	import WeaponImage from '$lib/components/image/weapon-image.svelte';
	import { altWeaponIdToId } from '$lib/constants/in-game/weapon-ids';
	import { getLocale } from '$lib/paraglide/runtime';
	import Popover from '$lib/components/popover.svelte';
	import Button from '$lib/components/button.svelte';
	import EditIcon from '$lib/components/icons/edit.svelte';
	import SpeechBubbleIcon from '$lib/components/icons/speech-bubble.svelte';
	import TrashIcon from '$lib/components/icons/trash.svelte';
	import { deleteBuild } from '../../routes/u/[identifier]/builds/delete-build.remote';

	interface BuildWeaponWithTop500Info {
		weaponSplId: MainWeaponId;
		minRank: number | null;
		maxPower: number | null;
	}

	interface BuildProps {
		build: Pick<
			Tables['Build'],
			| 'id'
			| 'title'
			| 'description'
			| 'clothesGearSplId'
			| 'headGearSplId'
			| 'shoesGearSplId'
			| 'updatedAt'
			| 'private'
		> & {
			abilities: BuildAbilitiesTuple;
			unsortedAbilities: BuildAbilitiesTuple;
			modes: ModeShort[] | null;
			weapons: Array<{
				weaponSplId: Tables['BuildWeapon']['weaponSplId'];
				minRank: number | null;
				maxPower: number | null;
			}>;
		};
		owner?: Pick<UserWithPlusTier, 'discordId' | 'username' | 'plusTier'>;
		withAbilitySorting?: boolean;
		canEdit?: boolean;
	}

	let { build, owner, withAbilitySorting = true, canEdit: _canEdit = false }: BuildProps = $props();

	const abilities = $derived(withAbilitySorting ? build.abilities : build.unsortedAbilities);
	const isNoGear = $derived(
		[build.headGearSplId, build.clothesGearSplId, build.shoesGearSplId].some((id) => id === -1)
	);
</script>

<div
	class={[
		'card',
		{
			private: build.private
		}
	]}
	data-testid="build-card"
>
	<div>
		<div class="top-row">
			{#if build.modes && build.modes.length > 0}
				<div class="modes">
					{#each build.modes as mode (mode)}
						<Image
							alt={modesLongTranslations[mode]()}
							title={modesLongTranslations[mode]()}
							path={modeImageUrl(mode)}
							width={18}
							height={18}
							data-testid="build-mode-{mode}"
						/>
					{/each}
				</div>
			{/if}
			<h2 class="title" data-testid="build-title">
				{build.title}
			</h2>
		</div>
		<div class="date-author-row">
			{#if owner}
				<a href={userBuildsPage(owner)} class="owner-link">
					{owner.username}
				</a>
				<div>•</div>
			{/if}
			{#if owner?.plusTier}
				<span>+{owner.plusTier}</span>
				<div>•</div>
			{/if}
			<div class="stack horizontal sm">
				{#if build.private}
					<div class="private-text">
						<LockIcon class="private-icon" />
						{m.common_build_private()}
					</div>
				{/if}
				<time class="whitespace-nowrap">
					{build.updatedAt.toLocaleDateString(getLocale(), {
						day: 'numeric',
						month: 'long',
						year: 'numeric'
					})}
				</time>
			</div>
		</div>
	</div>
	<div class="weapons">
		{#each build.weapons as weapon (weapon.weaponSplId)}
			{@render roundWeaponImage(weapon)}
		{/each}
		{#if build.weapons.length === 1}
			<div class="weapon-text">
				{weaponTranslations[build.weapons[0].weaponSplId]()}
			</div>
		{/if}
	</div>
	<div class="gear-abilities {isNoGear ? 'no-gear' : ''}">
		{@render abilitiesRowWithGear('HEAD', abilities[0], build.headGearSplId)}
		{@render abilitiesRowWithGear('CLOTHES', abilities[1], build.clothesGearSplId)}
		{@render abilitiesRowWithGear('SHOES', abilities[2], build.shoesGearSplId)}
	</div>
	<div class="bottom-row">
		<a href="xxx:">
			<Image alt={m.common_pages_analyzer()} class="icon" path={navIconUrl('analyzer')} />
		</a>
		{#if build.description}
			<Popover>
				{#snippet anchorButton(popovertarget)}
					<Button variant="minimal" class="small-text" {popovertarget}>
						{#snippet icon()}
							<SpeechBubbleIcon />
						{/snippet}
					</Button>
				{/snippet}
				{build.description}
			</Popover>
		{/if}
		{#if true}
			<Button
				class="small-text"
				variant="minimal"
				size="small"
				href="xxx:"
				data-testid="edit-build"
			>
				{#snippet icon()}
					<EditIcon class="icon" />
				{/snippet}
			</Button>
		{/if}
		<Popover>
			{#snippet anchorButton(popovertarget)}
				<Button {popovertarget} variant="minimal-destructive">
					{#snippet icon()}
						<TrashIcon class="icon" />
					{/snippet}
				</Button>
			{/snippet}
			Delete build? <Button
				onclick={async () => {
					console.log('Deleting build', build.id);

					// xxx: optimistic
					await deleteBuild({
						buildId: build.id,
						identifier: 'sendou' // xxx: pass identifier
					});
				}}>Delete</Button
			>
		</Popover>
		<!-- <FormWithConfirm
				dialogHeading={$_('builds.deleteConfirm', { values: { title } })}
				fields={[
					['buildToDeleteId', id],
					['_action', 'DELETE_BUILD']
				]}
			>
				<SendouButton
					icon={TrashIcon}
					class="small-text icon"
					variant="minimal-destructive"
					type="submit"
				/>
			</FormWithConfirm> -->
	</div>
</div>

{#snippet roundWeaponImage(weapon: BuildWeaponWithTop500Info)}
	{@const normalizedWeaponSplId = altWeaponIdToId.get(weapon.weaponSplId) ?? weapon.weaponSplId}
	{@const isTop500 = typeof weapon.maxPower === 'number' && typeof weapon.minRank === 'number'}

	<div class="weapon">
		{#if isTop500}
			<Image
				class="top-500"
				path={navIconUrl('xsearch')}
				alt=""
				title="Max X Power: {weapon.maxPower} | Best Rank: {weapon.minRank}"
				height={24}
				width={24}
				data-testid="top500-crown"
			/>
		{/if}
		<a href={weaponBuildPage(normalizedWeaponSplId)}>
			<WeaponImage weaponSplId={weapon.weaponSplId} size={36} variant="build" />
		</a>
	</div>
{/snippet}

{#snippet abilitiesRowWithGear(gearType: GearType, abilities: AbilityType[], gearId: number)}
	{#if gearId !== -1}
		<Image
			height={64}
			width={64}
			alt="xxx: TODO"
			title="xxx: TODO"
			path={gearImageUrl(gearType, gearId)}
			class="gear"
		/>
	{/if}
	{#each abilities as ability, i (i)}
		<Ability {ability} size={i === 0 ? 'MAIN' : 'SUB'} />
	{/each}
{/snippet}

<style>
	.card {
		position: relative;
		display: flex;
		flex-direction: column;
		padding: var(--s-3);
		border-radius: var(--rounded);
		background-color: var(--bg-lighter);
		gap: var(--s-3);

		:global(.icon) {
			width: 1.2rem;
			height: 1.2rem;
		}

		:global(.gear) {
			border-radius: 50%;
			background-color: var(--bg-darker-very-transparent);
			overflow: visible;
		}
	}

	.private {
		background-color: var(--bg-lighter-transparent);
	}

	.private-text {
		display: flex;
		justify-content: center;
		font-weight: var(--semi-bold);
		gap: var(--s-1);

		:global(.private-icon) {
			width: 16px;
			margin-block-end: var(--s-1);
			stroke-width: 2px;
		}
	}

	.title {
		overflow: hidden;
		height: 2.5rem;
		font-size: var(--fonts-sm);
		line-height: 1.25;
		word-wrap: break-all;
	}

	.top-row {
		display: flex;
		justify-content: space-between;
	}

	.date-author-row {
		display: flex;
		font-size: var(--fonts-xxs);
		gap: var(--s-1);
	}

	.owner-link {
		white-space: nowrap;
		overflow: hidden;
		text-overflow: ellipsis;
	}

	.modes {
		position: absolute;
		right: 0;
		display: flex;
		min-width: max-content;
		margin-top: -21px;
		gap: var(--s-1);
	}

	.weapon {
		position: relative;
		padding: var(--s-0-5);
		border-radius: 50%;
		background-color: var(--bg-darker-very-transparent);

		:global(.top-500) {
			position: absolute;
			top: -14px;
			right: 8px;
		}
	}

	.weapon-text {
		padding-left: var(--s-1);
		color: var(--text-lighter);
		font-size: var(--fonts-xxs);
		font-weight: var(--semi-bold);
	}

	.weapons {
		display: flex;
		flex-wrap: wrap;
		align-items: center;
		justify-content: center;
		gap: var(--s-1);
	}

	.gear-abilities {
		display: grid;
		gap: var(--s-2) var(--s-1);
		grid-template-columns: repeat(5, max-content);
		place-items: center;
	}

	.no-gear {
		grid-template-columns: repeat(4, max-content);
		margin: 0 auto;
		margin-top: 10px;
		margin-bottom: 1rem;
		row-gap: 28px;
	}

	.bottom-row {
		display: flex;
		height: 100%;
		align-items: flex-end;
		justify-content: center;
		gap: var(--s-4);
	}

	/*


	.small-text {
		font-size: var(--fonts-xxs) !important;
	} */
</style>
