// app/components/Main.tsx
import clsx from "clsx";
import type * as React from "react";
import { isRouteErrorResponse, useRouteError } from "react-router";
import { useHasRole } from "~/modules/permissions/hooks";
import styles from "./Main.module.css";

export const Main = ({
	children,
	className,
	classNameOverwrite,
	halfWidth,
	bigger,
	style,
}: {
	children: React.ReactNode;
	className?: string;
	classNameOverwrite?: string;
	halfWidth?: boolean;
	bigger?: boolean;
	style?: React.CSSProperties;
	sideNav?: React.ReactNode;
}) => {
	const error = useRouteError();
	const isMinorSupporter = useHasRole("MINOR_SUPPORT");
	const showLeaderboard =
		import.meta.env.VITE_PLAYWIRE_PUBLISHER_ID &&
		!isMinorSupporter &&
		!isRouteErrorResponse(error);

	const mainElement = (
		<main
			className={
				classNameOverwrite
					? clsx(classNameOverwrite, {
							[styles.narrow]: halfWidth,
							"pt-8-forced": showLeaderboard,
						})
					: clsx(
							styles.main,
							styles.normal,
							{
								[styles.narrow]: halfWidth,
								[styles.wide]: bigger,
								"pt-8-forced": showLeaderboard,
							},
							className,
						)
			}
			style={style}
		>
			{children}
		</main>
	);

	return <div className={styles.container}>{mainElement}</div>;
};

export { styles as mainStyles };

export const containerClassName = (width: "narrow" | "normal" | "wide") => {
	if (width === "narrow") {
		return styles.narrow;
	}

	if (width === "wide") {
		return styles.wide;
	}

	return styles.normal;
};

// src/lib/components/main.svelte
<script lang="ts">
	import type { Snippet } from "svelte";

	interface Props {
		children?: Snippet;
		className?: string;
		classNameOverwrite?: string;
		halfWidth?: boolean;
		bigger?: boolean;
		style?: string;
	}

	let {
		children,
		className,
		classNameOverwrite,
		halfWidth = false,
		bigger = false,
		style,
	}: Props = $props();

	// const isMinorSupporter = useHasRole('MINOR_SUPPORT');
	const isMinorSupporter = false; // xxx: replace with actual role check

	const isRouteErrorResponse = false; // xxx: replace with actual error check if needed

	const showLeaderboard = $derived(
		import.meta.env.VITE_PLAYWIRE_PUBLISHER_ID &&
			!isMinorSupporter &&
			!isRouteErrorResponse,
	);

	export const containerClassName = (
		width: "narrow" | "normal" | "wide",
	): string => {
		if (width === "narrow") {
			return "half-width";
		}

		if (width === "wide") {
			return "bigger";
		}

		return "main";
	};
</script>

<div class="container">
	<main
		class={{
			classNameOverwrite,
			className: className && !classNameOverwrite,
			[containerClassName("normal")]: !classNameOverwrite,
			[containerClassName("narrow")]: halfWidth,
			[containerClassName("wide")]: bigger,
			"pt-8-forced": showLeaderboard,
		}}
		{style}
	>
		{@render children?.()}
	</main>
</div>

<style>
	.container {
		display: flex;
		flex-direction: row;
	}

	.main {
		padding-block: var(--s-4) var(--s-32);
	}
</style>
